import React from 'react';
import { BookingFlowItem, BookingFlowTemplate, Payment } from '../types';
import { titleizeBookingStepGroup } from '../utils/bookingStepColors';
import { attentionStatuses, evidenceReceivedStatuses, failedStatuses } from './bookingStatusSelectors';

export const formatStepDate = (value?: Date | string | null) => { if (!value) return ''; const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : date.toLocaleDateString(); };
export const formatStepDateTime = (value?: Date | string | null) => { if (!value) return ''; const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : date.toLocaleString([], { month: '2-digit', day: '2-digit', year: '2-digit', hour: '2-digit', minute: '2-digit' }); };
export const formatStepDateInput = (value?: Date | string | null) => { if (!value) return ''; const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : date.toISOString().slice(0, 10); };
export const formatStepMoney = (amount?: number, currency?: string) => { const number = Number(amount); return Number.isFinite(number) ? `${number.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${currency || ''}`.trim() : ''; };
export const formatStepPaymentOption = (payment: Payment) => { const id = payment.display_id ? `#${payment.display_id}` : payment._id?.slice(-6) || 'Payment'; const status = payment.status && payment.status !== 'completed' ? ` (${payment.status})` : ''; return [id, formatStepMoney(payment.amount, payment.currency), formatStepDate(payment.paymentDate), String(payment.paymentMethod || '').replace(/_/g, ' ')].filter(Boolean).join(' • ') + status; };
export const getStepStatusCellClass = (status?: BookingFlowItem['status']) => status === 'caution' ? 'bg-orange-200 text-orange-950' : failedStatuses.has(status as any) ? 'bg-red-200 text-red-950' : status && evidenceReceivedStatuses.has(status) ? 'bg-green-100 text-green-950' : 'bg-red-50 text-red-900';
export type SimpleStepStatus = { label: string; className: string; icon: 'missing' | 'failed' | 'attention' | 'fulfilled' };
export const getSimpleStepStatus = (item?: BookingFlowItem): SimpleStepStatus => { if (!item) return { label: 'Missing', className: 'bg-red-50 text-red-600', icon: 'missing' }; const label = item.status?.replace(/_/g, ' ') || 'pending'; if (failedStatuses.has(item.status)) return { label, className: 'bg-red-100 text-red-800', icon: 'failed' }; if (attentionStatuses.has(item.status)) return { label, className: 'bg-amber-50 text-amber-700', icon: 'attention' }; if (evidenceReceivedStatuses.has(item.status)) return { label, className: 'bg-green-50 text-green-700', icon: 'fulfilled' }; return { label, className: 'bg-red-50 text-red-600', icon: 'missing' }; };
export const getStepStatusDateField = (status?: BookingFlowItem['status']): keyof BookingFlowItem | 'dueDate' => status === 'sent' || status === 'sent_for_review' ? 'sentAt' : status === 'received' ? 'receivedAt' : ['reviewed', 'approved', 'caution', 'rejected', 'needs_resubmission'].includes(status || '') ? 'reviewedAt' : status === 'completed' ? 'completedAt' : 'dueDate';
export const getStepItemDisplayValue = (item: BookingFlowItem) => { if (item.status === 'pending' && !item.notes) return ''; const value = item[getStepStatusDateField(item.status) as keyof BookingFlowItem] as Date | string | null | undefined; return formatStepDateTime(value) || (item.status === 'pending' ? '' : item.status.replace(/_/g, ' ')); };
export const getStepTemplateGroup = (template?: Partial<BookingFlowTemplate> | null, fallbackCategory?: string) => { const groupKey = String(template?.readinessGroup || fallbackCategory || template?.category || 'other').trim() || 'other'; return { groupKey, groupLabel: titleizeBookingStepGroup(groupKey), groupColor: (template as any)?.readinessGroupColor }; };
export const getStepItemGroup = (item?: Partial<BookingFlowItem> | null, template?: Partial<BookingFlowTemplate> | null) => { const metadata = item?.metadata || {}; const groupKey = String(metadata.readinessGroup || template?.readinessGroup || item?.category || template?.category || 'other').trim() || 'other'; return { groupKey, groupLabel: titleizeBookingStepGroup(groupKey), groupColor: (template as any)?.readinessGroupColor || metadata.readinessGroupColor }; };
export const solidifyStepAlphaHex = (value?: string) => { if (!value || !/^#[0-9a-fA-F]{8}$/.test(value)) return value; const values = [1, 3, 5].map(index => parseInt(value.slice(index, index + 2), 16)); const alpha = parseInt(value.slice(7, 9), 16) / 255; const blend = (channel: number) => Math.round(channel * alpha + 255 * (1 - alpha)); return `rgb(${values.map(blend).join(', ')})`; };
export const getStepStickyCellStyle = (style: React.CSSProperties | undefined, fallback: string): React.CSSProperties => ({ ...(style || {}), backgroundColor: solidifyStepAlphaHex(String(style?.backgroundColor || '')) || style?.backgroundColor || fallback, backgroundClip: 'padding-box', boxShadow: '4px 0 10px rgba(15, 23, 42, 0.08)' });
