import React, { useMemo, useState } from 'react';
import { FiChevronDown, FiEdit3 } from 'react-icons/fi';
import BookingPaymentManagement from './BookingPaymentManagement';
import ClientBookingWorkflowTab from './ClientBookingWorkflowTab';
import { BookingConfirmationLanguage } from './bookingConfirmationWorkflow';
const Icon: React.FC<{ component: any }> = ({ component: Component }) => <Component />;

const languageLabels: Record<BookingConfirmationLanguage, string> = { pl: 'Polish', cz: 'Czech', en: 'English' };
export const formatBookingDate = (date?: string | Date) => { if (!date) return 'N/A'; const value = new Date(date); if (Number.isNaN(value.getTime())) return 'N/A'; return value.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC' }); };
export const formatHistoryDateTime = (date?: string | Date) => { if (!date) return 'N/A'; const value = new Date(date); if (Number.isNaN(value.getTime())) return 'N/A'; return value.toLocaleString('en-US', { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }); };
export const retreatTown = (retreat: any) => String(retreat?.location_town || retreat?.locationTown || retreat?.generalTown || retreat?.general_town || retreat?.house?.generalTown || retreat?.house?.general_town || retreat?.house?.city || retreat?.houseId?.generalTown || retreat?.houseId?.general_town || retreat?.houseId?.city || retreat?.location || '').trim();

type Props = { bookingId: string; booking: any; client: any; retreat: any; clientName: string; bookingTypeCode: string; retreatCode: string; retreatAddress: string; onEditClient: () => void; onBookingRefresh: () => void; };
const Accordion: React.FC<{ title: string; open: boolean; onToggle: () => void; className?: string; children: React.ReactNode }> = ({ title, open, onToggle, className = '', children }) => <div className={`booking-detail-accordion ${className}`}><button type="button" className="booking-detail-accordion-trigger" onClick={onToggle} aria-expanded={open}><span>{title}</span><span>{open ? 'Hide' : 'Show'}</span></button>{open && <div className="booking-detail-accordion-body">{children}</div>}</div>;

const BookingOverviewPanel: React.FC<Props> = ({ bookingId, booking, client, retreat, clientName, bookingTypeCode, retreatCode, retreatAddress, onEditClient, onBookingRefresh }) => {
  const [clientOpen, setClientOpen] = useState(false); const [paymentsOpen, setPaymentsOpen] = useState(true); const [stepsOpen, setStepsOpen] = useState(false); const [retreatOpen, setRetreatOpen] = useState(false); const [datesOpen, setDatesOpen] = useState(false);
  const history = useMemo(() => [...(booking?.bookingConfirmationHistory || [])].sort((a: any, b: any) => (a.iteration || 0) - (b.iteration || 0)), [booking]);
  const first = history[0]; const latest = history[history.length - 1];
  return <>
    <div className="booking-overview-summary"><div className="booking-overview-retreat"><span className="booking-type-dot">{bookingTypeCode}</span><span className="retreat-code-pill">{retreatCode}</span></div><div className="booking-overview-address">{retreatAddress || 'No retreat address recorded'}</div></div>
    <div className="detail-section pdf-section">
      <div className="section-header"><h3 className="pdf-section-title">Booking Confirmation History</h3><span className="booking-confirm-history-count">{history.length} iteration{history.length === 1 ? '' : 's'}</span></div>
      {!history.length ? <p className="text-sm text-gray-500">No booking confirmation has been sent yet.</p> : <details className="booking-confirm-history-accordion"><summary className="booking-confirm-history-trigger"><div className="booking-confirm-history-compact"><div><span>Original</span><strong>{formatHistoryDateTime(first?.sentAt || first?.createdAt)}</strong></div><div><span>Last update</span><strong>{formatHistoryDateTime(latest?.sentAt || latest?.createdAt)}</strong></div><div><span>Latest reason</span><strong>{latest?.reason || 'N/A'}</strong></div></div><span className="booking-confirm-history-toggle">Show iterations</span></summary><div className="booking-confirm-history"><div className="booking-confirm-history-list">{history.map((entry: any) => <div key={entry._id || `${entry.iteration}-${entry.sentAt}`} className="booking-confirm-history-entry"><div className="booking-confirm-history-entry-main"><strong>Iteration {entry.iteration}</strong><span>{formatHistoryDateTime(entry.sentAt || entry.createdAt)}</span></div><div className="booking-confirm-history-entry-meta"><span>{entry.reason || 'No reason recorded'}</span>{entry.language && <span>{languageLabels[entry.language as BookingConfirmationLanguage] || entry.language}</span>}{entry.sentEmailDisplayId && <span>Email #{entry.sentEmailDisplayId}</span>}{entry.snapshot?.retreatCode && <span>{entry.snapshot.retreatCode}</span>}{entry.snapshot?.paymentRequestDisplayId && <span>Payment request #{entry.snapshot.paymentRequestDisplayId}</span>}</div></div>)}</div></div></details>}
    </div>
    <div className="detail-section pdf-section"><div className="section-header client-section-header"><h3 className="pdf-section-title">Client Information</h3><div className="client-mobile-heading"><div><span className="mobile-section-label">Client</span><h2>{clientName}</h2></div><button className="edit-btn edit-client-btn" onClick={onEditClient} aria-label="Edit client information"><Icon component={FiEdit3} /><span>Edit Client</span></button></div><button className="edit-btn edit-client-btn desktop-client-edit" onClick={onEditClient} title="Edit client information"><Icon component={FiEdit3} /><span>Edit Client</span></button></div><button type="button" className="mobile-client-details-toggle" onClick={() => setClientOpen(v => !v)} aria-expanded={clientOpen}><span>Client details</span><Icon component={FiChevronDown} /></button><div className={`info-grid client-info-grid ${clientOpen ? 'mobile-expanded' : 'mobile-collapsed'}`}><div className="info-item"><label>Name:</label><span>{clientName}</span></div><div className="info-item mobile-hidden-client-field"><label>Email:</label><span>{client?.email || 'N/A'}</span></div><div className="info-item"><label>Phone:</label><span>{client?.phone || 'N/A'}</span></div><div className="info-item mobile-hidden-client-field"><label>City:</label><span>{client?.city || 'N/A'}</span></div><div className="info-item"><label>Country:</label><span>{client?.country || 'N/A'}</span></div></div></div>
    <Accordion title="Payment Information" open={paymentsOpen} onToggle={() => setPaymentsOpen(v => !v)} className="booking-payment-accordion"><BookingPaymentManagement bookingId={bookingId} bookingNumber={booking.bookingNumber} bookingHash={booking.bookingHash} clientId={typeof client === 'object' ? client?._id : client} retreatId={typeof retreat === 'object' ? retreat?._id : retreat} totalAmount={booking.totalAmount || 0} currency={booking.currency || 'EUR'} onPaymentUpdate={onBookingRefresh} /></Accordion>
    <Accordion title="Booking Requirements" open={stepsOpen} onToggle={() => setStepsOpen(v => !v)} className="booking-steps-accordion"><ClientBookingWorkflowTab bookings={[booking]} hideBookingSelector /></Accordion>
    <Accordion title="Retreat Information" open={retreatOpen} onToggle={() => setRetreatOpen(v => !v)} className="retreat-info-accordion"><div className="info-grid"><div className="info-item"><label>Retreat Name:</label><span>{retreat?.name || 'N/A'}</span></div><div className="info-item"><label>Location town:</label><span>{retreatTown(retreat) || 'N/A'}</span></div><div className="info-item"><label>Type:</label><span>{retreat?.type ? retreat.type.charAt(0).toUpperCase() + retreat.type.slice(1) : 'N/A'}</span></div><div className="info-item"><label>Start Date:</label><span>{formatBookingDate(retreat?.startDate || retreat?.dates?.startDate)}</span></div><div className="info-item"><label>End Date:</label><span>{formatBookingDate(retreat?.endDate || retreat?.dates?.endDate)}</span></div></div></Accordion>
    <Accordion title="Booking Dates" open={datesOpen} onToggle={() => setDatesOpen(v => !v)}><div className="info-grid"><div className="info-item"><label>Registration Date:</label><span>{formatBookingDate(booking.registrationDate)}</span></div><div className="info-item"><label>Check-in Date:</label><span>{formatBookingDate(booking.checkInDate)}</span></div><div className="info-item"><label>Check-out Date:</label><span>{formatBookingDate(booking.checkOutDate)}</span></div></div></Accordion>
  </>;
};
export default BookingOverviewPanel;
