import React from 'react';
import { Mail } from 'lucide-react';
import { BookingStepMatrixRow, BookingStepMatrixRowGroup } from './bookingStepRows';
import { getBookingStepColorStyles, getBookingStepToneWithColor } from '../utils/bookingStepColors';
import { getStepStickyCellStyle } from './bookingStepPresentation';
import { BookingStepTypeIcon, getBookingStepType } from './bookingStepTypes';

export const BookingStepGroupHeader = ({ group, bookingIds }: { group: BookingStepMatrixRowGroup; bookingIds: string[] }) => { const tone = getBookingStepToneWithColor(group.key, group.color); const style = getBookingStepColorStyles(tone, 'group'); return <tr><td className={`sticky left-0 z-30 border-b border-r px-3 py-2 text-xs font-bold uppercase ${tone.groupCell} ${tone.groupText}`} style={getStepStickyCellStyle(style, '#f1f5f9')}><span className="inline-flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${tone.dot}`} style={getBookingStepColorStyles(tone, 'dot')} />{group.label}</span></td>{bookingIds.map(id => <td key={id} className={`border-b border-r px-2 py-2 ${tone.groupCell} ${tone.groupText}`} style={style}><span className="sr-only">{group.label}</span></td>)}</tr>; };
export const BookingStepRowHeader = ({ row, number, group, isEditing, saving, onEmail }: { row: BookingStepMatrixRow; number?: number; group: BookingStepMatrixRowGroup; isEditing: boolean; saving: string; onEmail: () => void }) => { const tone = getBookingStepToneWithColor(group.key, group.color); const type = getBookingStepType(row.stepType, row.key); return <td className={`sticky left-0 z-30 border-b border-l-4 border-r px-3 py-2 ${tone.stepCell} ${tone.stepStripe}`} style={getStepStickyCellStyle(getBookingStepColorStyles(tone, 'step'), '#f8fafc')}><div className="flex items-start gap-2"><span className={`inline-flex h-5 min-w-5 items-center justify-center rounded text-[11px] ${tone.badge}`} style={getBookingStepColorStyles(tone, 'badge')}>{number}</span><BookingStepTypeIcon type={row.stepType} stepKey={row.key} className="mt-0.5 h-4 w-4 shrink-0" /><span><span className="block">{row.title}</span><span className="block text-[10px] font-normal opacity-60">{type.label}</span></span></div>{row.templateId && row.emailEnabled && row.emailTemplateId && <button type="button" disabled={!isEditing || saving === `row-email:${row.key}`} onClick={onEmail} className="mt-2 inline-flex items-center gap-1 rounded-md border border-blue-200 bg-blue-50 px-2 py-1 text-xs disabled:opacity-50"><Mail className="h-3.5 w-3.5" />{saving === `row-email:${row.key}` ? 'Sending...' : row.key === 'address_sent' ? 'Send address' : 'Send row'}</button>}</td>; };
