import React from 'react';
import { fireEvent, render, screen } from '@testing-library/react';
import BookingOverviewPanel, { formatBookingDate, formatHistoryDateTime, retreatTown } from './BookingOverviewPanel';
jest.mock('./BookingPaymentManagement', () => ({ __esModule: true, default: ({ onPaymentUpdate }: any) => <button onClick={onPaymentUpdate}>Mock payment</button> }));
jest.mock('./ClientBookingWorkflowTab', () => ({ __esModule: true, default: () => <div>Mock workflow</div> }));
const base = { bookingId: 'b', booking: { bookingNumber: 3, totalAmount: 10, currency: 'USD', registrationDate: '2026-01-01', checkInDate: '2026-02-01', checkOutDate: '2026-02-02', bookingConfirmationHistory: [] }, client: { _id: 'c', email: 'a@b.com', phone: '1', city: 'Prague', country: 'CZ' }, retreat: { _id: 'r', name: 'Retreat', locationTown: 'Mistrovice', type: 'full', startDate: '2026-02-01', endDate: '2026-02-02' }, clientName: 'Ada', bookingTypeCode: 'F', retreatCode: 'RET', retreatAddress: 'Address', onEditClient: jest.fn(), onBookingRefresh: jest.fn() };
describe('BookingOverviewPanel', () => {
  beforeEach(() => jest.clearAllMocks());
  it('formats dates and resolves towns safely', () => { expect(formatBookingDate()).toBe('N/A'); expect(formatBookingDate('bad')).toBe('N/A'); expect(formatBookingDate('2026-01-02')).toContain('January'); expect(formatHistoryDateTime('bad')).toBe('N/A'); expect(formatHistoryDateTime()).toBe('N/A'); expect(retreatTown({ house: { city: 'Town' } })).toBe('Town'); expect(retreatTown(null)).toBe(''); });
  it('renders task-first overview, client rail and open payments', () => { render(<BookingOverviewPanel {...base} />); expect(screen.getByText('Not sent')).toBeInTheDocument(); expect(screen.getByText('a@b.com')).toBeInTheDocument(); expect(screen.getByText('Requirements next up')).toBeInTheDocument(); fireEvent.click(screen.getByText('Mock payment')); expect(base.onBookingRefresh).toHaveBeenCalled(); fireEvent.click(screen.getByText('Edit')); expect(base.onEditClient).toHaveBeenCalled(); });
  it('sorts and renders confirmation history', () => { const history = [{ iteration: 2, sentAt: '2026-02-02' }, { iteration: 1, sentAt: '2026-01-01' }]; render(<BookingOverviewPanel {...base} booking={{ ...base.booking, bookingConfirmationHistory: history }} />); expect(screen.getByText('2 iterations')).toBeInTheDocument(); fireEvent.click(screen.getByText('Show iterations')); expect(screen.getByText('Iteration 1')).toBeInTheDocument(); expect(screen.getByText('Iteration 2')).toBeInTheDocument(); });
  it('toggles operational and information sections while payments remain visible', () => { render(<BookingOverviewPanel {...base} />); fireEvent.click(screen.getByText('Requirements next up')); expect(screen.getByText('Mock workflow')).toBeInTheDocument(); fireEvent.click(screen.getByText('Retreat information')); expect(screen.getByText('Address')).toBeInTheDocument(); fireEvent.click(screen.getByText('Booking dates')); expect(screen.getByText('Booked:')).toBeInTheDocument(); expect(screen.getByText('Mock payment')).toBeInTheDocument(); });
  it('uses missing-value and nested-date fallbacks', () => { render(<BookingOverviewPanel {...base} retreat={{ dates: { startDate: '2026-03-01', endDate: '2026-03-02' } }} client={{}} retreatAddress="" />); fireEvent.click(screen.getByText('Retreat information')); expect(screen.getAllByText('N/A').length).toBeGreaterThan(1); });
});
