import React, { useMemo, useState } from 'react';
import { Retreat } from '../types';

const reasons = [['client_requested','Client requested'],['illness','Illness'],['missing_artifacts','Required artifacts not received'],['medical_delay','Medical delay'],['travel_problem','Travel problem'],['administrative_change','Administrative change'],['other','Other']];
const id = (value: any) => typeof value === 'object' ? value?._id : value;
const code = (r: any) => r.code || r.retreatCode || r.name || 'Retreat';
const date = (v: any) => v ? new Date(v).toLocaleDateString() : '—';

export default function BookingRescheduleDialog({ currentRetreatId, retreats, saving, error, onClose, onSubmit }: { currentRetreatId: string; retreats: Retreat[]; saving: boolean; error?: string; onClose: () => void; onSubmit: (data: { targetRetreatId: string; reason: string; note: string; sendEmail: boolean }) => Promise<void> }) {
  const [targetRetreatId,setTargetRetreatId]=useState(''); const [reason,setReason]=useState('client_requested'); const [note,setNote]=useState(''); const [sendEmail,setSendEmail]=useState(false);
  const options=useMemo(()=>retreats.filter((r:any)=>id(r)!==currentRetreatId && r.status!=='cancelled' && new Date(r.endDate || r.startDate || 0).getTime()>=Date.now()).sort((a:any,b:any)=>new Date(a.startDate).getTime()-new Date(b.startDate).getTime()),[currentRetreatId,retreats]);
  const selected:any=options.find((r:any)=>id(r)===targetRetreatId);
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" role="dialog" aria-modal="true" aria-labelledby="reschedule-title"><form className="w-full max-w-2xl rounded-xl bg-white p-6 shadow-2xl" onSubmit={e=>{e.preventDefault(); void onSubmit({targetRetreatId,reason,note,sendEmail});}}><h2 id="reschedule-title" className="text-xl font-semibold">Reschedule booking</h2><p className="mt-1 text-sm text-gray-600">Completed payments, documents, medical reviews and steps remain. Retreat-relative deadlines will be recalculated.</p>{error&&<div className="mt-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<label className="mt-5 block text-sm font-semibold">Move to retreat<select required value={targetRetreatId} onChange={e=>setTargetRetreatId(e.target.value)} className="mt-2 w-full rounded border border-gray-300 p-3"><option value="">Select a future retreat</option>{options.map((r:any)=><option key={id(r)} value={id(r)}>{code(r)} · {date(r.startDate)} – {date(r.endDate)} · {Math.max(0,Number(r.capacity||0)-Number(r.currentOccupancy||0))} places shown open</option>)}</select></label>{selected&&<div className="mt-3 rounded bg-blue-50 p-3 text-sm text-blue-800">New retreat: <strong>{code(selected)}</strong> · {date(selected.startDate)} – {date(selected.endDate)}</div>}<label className="mt-4 block text-sm font-semibold">Reason<select value={reason} onChange={e=>setReason(e.target.value)} className="mt-2 w-full rounded border border-gray-300 p-3">{reasons.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="mt-4 block text-sm font-semibold">Internal note<textarea required minLength={2} rows={3} value={note} onChange={e=>setNote(e.target.value)} className="mt-2 w-full rounded border border-gray-300 p-3" placeholder="Why is this booking being moved?" /></label><label className="mt-4 flex items-start gap-3 rounded border border-gray-200 p-3 text-sm"><input type="checkbox" checked={sendEmail} onChange={e=>setSendEmail(e.target.checked)} /><span><strong>Send reschedule email after moving</strong><br/><span className="text-gray-500">Off by default. Enable only with permission to email this client.</span></span></label><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} disabled={saving} className="rounded border border-gray-300 px-4 py-2">Cancel</button><button type="submit" disabled={saving||!targetRetreatId||note.trim().length<2} className="rounded bg-gray-950 px-5 py-2 font-semibold text-white disabled:opacity-50">{saving?'Rescheduling…':'Confirm reschedule'}</button></div></form></div>;
}
