import { formatStepDate, formatStepDateInput, formatStepDateTime, formatStepMoney, formatStepPaymentOption, getSimpleStepStatus, getStepItemDisplayValue, getStepItemGroup, getStepStatusCellClass, getStepStatusDateField, getStepStickyCellStyle, getStepTemplateGroup, solidifyStepAlphaHex } from './bookingStepPresentation';

describe('bookingStepPresentation', () => {
  it('formats dates and inputs safely', () => { expect(formatStepDate()).toBe(''); expect(formatStepDate('bad')).toBe(''); expect(formatStepDate('2026-01-02')).toBeTruthy(); expect(formatStepDateTime('bad')).toBe(''); expect(formatStepDateTime('2026-01-02')).toBeTruthy(); expect(formatStepDateInput('2026-01-02')).toBe('2026-01-02'); expect(formatStepDateInput(null)).toBe(''); });
  it('formats money and payment options', () => { expect(formatStepMoney(12, 'EUR')).toContain('12.00 EUR'); expect(formatStepMoney(Number.NaN)).toBe(''); expect(formatStepPaymentOption({ display_id: 5, amount: 10, currency: 'USD', paymentMethod: 'bank_transfer', status: 'pending' } as any)).toContain('#5'); expect(formatStepPaymentOption({ _id: '123456abcdef', status: 'completed' } as any)).not.toContain('(completed)'); expect(formatStepPaymentOption({} as any)).toContain('Payment'); });
  it('maps detailed and simple statuses', () => { expect(getStepStatusCellClass('caution')).toContain('orange'); expect(getStepStatusCellClass('rejected')).toContain('red-200'); expect(getStepStatusCellClass('approved')).toContain('green'); expect(getStepStatusCellClass('sent')).toContain('red-50'); expect(getSimpleStepStatus()).toMatchObject({ label: 'Missing', icon: 'missing' }); expect(getSimpleStepStatus({ status: 'blocked' } as any).icon).toBe('failed'); expect(getSimpleStepStatus({ status: 'in_review' } as any).icon).toBe('attention'); expect(getSimpleStepStatus({ status: 'received' } as any).icon).toBe('fulfilled'); expect(getSimpleStepStatus({ status: 'pending' } as any).icon).toBe('missing'); });
  it('selects status date fields and display values', () => { expect(getStepStatusDateField('sent')).toBe('sentAt'); expect(getStepStatusDateField('received')).toBe('receivedAt'); expect(getStepStatusDateField('approved')).toBe('reviewedAt'); expect(getStepStatusDateField('completed')).toBe('completedAt'); expect(getStepStatusDateField('pending')).toBe('dueDate'); expect(getStepItemDisplayValue({ status: 'pending' } as any)).toBe(''); expect(getStepItemDisplayValue({ status: 'received', receivedAt: '2026-01-02' } as any)).toBeTruthy(); expect(getStepItemDisplayValue({ status: 'sent_for_review' } as any)).toBe('sent for review'); });
  it('resolves template and item readiness groups', () => { expect(getStepTemplateGroup({ readinessGroup: 'medical', readinessGroupColor: '#fff' } as any)).toEqual({ groupKey: 'medical', groupLabel: 'Medical', groupColor: '#fff' }); expect(getStepTemplateGroup(null, 'forms').groupKey).toBe('forms'); expect(getStepTemplateGroup({ readinessGroup: ' ' } as any).groupKey).toBe('other'); expect(getStepItemGroup({ metadata: { readinessGroup: 'client', readinessGroupColor: '#aaa' } } as any).groupKey).toBe('client'); expect(getStepItemGroup({ category: 'medical' } as any, { readinessGroupColor: '#bbb' } as any).groupColor).toBe('#bbb'); });
  it('solidifies alpha backgrounds and creates sticky styles', () => { expect(solidifyStepAlphaHex('#00000080')).toMatch(/^rgb/); expect(solidifyStepAlphaHex('#fff')).toBe('#fff'); expect(solidifyStepAlphaHex()).toBeUndefined(); expect(getStepStickyCellStyle({ backgroundColor: '#00000080', color: 'red' }, 'white')).toMatchObject({ color: 'red', backgroundClip: 'padding-box' }); expect(getStepStickyCellStyle(undefined, 'white').backgroundColor).toBe('white'); });
});
