import React from 'react';
import { FiArrowLeft, FiArrowRight, FiCheck, FiDownload, FiEdit3, FiEye, FiMail, FiMoreHorizontal, FiSend, FiX } from 'react-icons/fi';
import { BookingConfirmationLanguage } from './bookingConfirmationWorkflow';

export type BookingDetailTab = 'overview' | 'activity' | 'payments' | 'requirements' | 'medical' | 'ceremonies' | 'documents' | 'emails' | 'tasks' | 'workflow' | 'notes';
export const bookingDetailTabs: { key: BookingDetailTab; label: string }[] = [
  ['overview', 'Overview'], ['activity', 'Activity'], ['payments', 'Payments'], ['requirements', 'Requirements'], ['medical', 'Medical'], ['ceremonies', 'Ceremonies'], ['documents', 'Documents'], ['emails', 'Emails'], ['tasks', 'Tasks'], ['workflow', 'Booking Requirements'], ['notes', 'Notes'],
].map(([key, label]) => ({ key: key as BookingDetailTab, label }));
const Icon: React.FC<{ component: any }> = ({ component: Component }) => <Component />;

type Props = {
  bookingNumber?: string | number; clientName: string; clientDisplayId?: string | number; clientId?: string; retreatCode: string; retreatId?: string; retreatAddress?: string; bookingTypeCode: string;
  language: BookingConfirmationLanguage; activeTab: BookingDetailTab; requirementsStatus: { missing: number; total: number } | null;
  generating: boolean; previewing: boolean; previewPhase?: 'loading' | 'generating' | null; sending: boolean; preparing: boolean; previewUrl: string; previewFileName: string;
  previousBooking?: { bookingNumber?: string | number; clientName?: string } | null; nextBooking?: { bookingNumber?: string | number; clientName?: string } | null;
  onBack: () => void; onLanguageChange: (value: BookingConfirmationLanguage) => void; onEdit: () => void; onPreview: () => void; onQuickSend: () => void; onReview: () => void; onDownload: () => void; onClosePreview: () => void; onOpenClient: () => void; onOpenRetreat: () => void; onTabChange: (tab: BookingDetailTab) => void;
  onPreviousBooking?: () => void; onNextBooking?: () => void;
};

const BookingDetailShell: React.FC<Props> = (props) => <>
  <div className="detail-header">
    <button onClick={props.onBack} className="back-btn" title="Back to bookings" aria-label="Back to bookings"><Icon component={FiArrowLeft} /></button>
    <div className="booking-title-block"><h1>Booking #{props.bookingNumber || 'N/A'}</h1><div className="booking-title-meta"><strong>{props.clientName}</strong>{props.retreatId ? <button type="button" onClick={props.onOpenRetreat}>{props.retreatCode}</button> : <strong>{props.retreatCode}</strong>}{props.clientDisplayId && (props.clientId ? <button type="button" onClick={props.onOpenClient} title={`Open client #${props.clientDisplayId}`}>Client #{props.clientDisplayId}</button> : <span>Client #{props.clientDisplayId}</span>)}<span>Type {props.bookingTypeCode}</span>{props.retreatAddress && <span className="booking-title-address">{props.retreatAddress}</span>}</div></div>
    <nav className="booking-sibling-navigation" aria-label={`Bookings in ${props.retreatCode}`}>
      <button type="button" disabled={!props.previousBooking} onClick={props.onPreviousBooking} className="booking-sibling-button" aria-label={props.previousBooking ? `Previous booking, #${props.previousBooking.bookingNumber}, ${props.previousBooking.clientName || ''}` : 'No previous booking'} title={props.previousBooking ? `Previous: #${props.previousBooking.bookingNumber} · ${props.previousBooking.clientName || ''}` : 'First booking in this retreat'}><Icon component={FiArrowLeft} /><span><small>Previous</small>{props.previousBooking ? `#${props.previousBooking.bookingNumber || 'N/A'}` : '—'}</span></button>
      <button type="button" disabled={!props.nextBooking} onClick={props.onNextBooking} className="booking-sibling-button is-next" aria-label={props.nextBooking ? `Next booking, #${props.nextBooking.bookingNumber}, ${props.nextBooking.clientName || ''}` : 'No next booking'} title={props.nextBooking ? `Next: #${props.nextBooking.bookingNumber} · ${props.nextBooking.clientName || ''}` : 'Last booking in this retreat'}><span><small>Next</small>{props.nextBooking ? `#${props.nextBooking.bookingNumber || 'N/A'}` : '—'}</span><Icon component={FiArrowRight} /></button>
    </nav>
    <div className="header-actions">
      <select aria-label="Confirmation language" value={props.language} onChange={e => props.onLanguageChange(e.target.value as BookingConfirmationLanguage)} className="language-selector" disabled={props.generating}><option value="pl">PL</option><option value="cz">CZ</option><option value="en">EN</option></select>
      <button onClick={props.onEdit} className="pdf-btn" title="Edit booking" aria-label="Edit booking"><Icon component={FiEdit3} /><span>Edit</span></button>
      <button onClick={props.onPreview} disabled={props.previewing} className="pdf-btn" title="Preview PDF" aria-label="Preview PDF"><Icon component={FiEye} /><span>{props.previewing ? (props.previewPhase === 'generating' ? 'Generating PDF' : 'Loading PDF') : 'Preview'}</span></button>
      <button onClick={props.onQuickSend} disabled={props.sending} className="pdf-btn primary-action" title="Send email with PDF attachment" aria-label="Send email with PDF attachment"><Icon component={FiSend} /><span>{props.sending ? 'Sending' : 'Send'}</span></button>
      <button onClick={props.onReview} disabled={props.preparing} className="pdf-btn" title="Review email with PDF attachment" aria-label="Review email with PDF attachment"><Icon component={FiMail} /><span>{props.preparing ? 'Preparing' : 'Review'}</span></button>
      <button onClick={props.onDownload} disabled={props.generating} className="pdf-btn" title="Download PDF" aria-label="Download PDF"><Icon component={FiDownload} /><span>{props.generating ? 'Generating' : 'Download'}</span></button>
      <details className="booking-more-menu"><summary className="pdf-btn booking-more-button" title="More booking actions" aria-label="More booking actions"><Icon component={FiMoreHorizontal} /><span>More</span></summary><div className="booking-more-menu-popover"><div className="booking-more-language">PDF language<select aria-label="More menu PDF language" value={props.language} onChange={e => props.onLanguageChange(e.target.value as BookingConfirmationLanguage)}><option value="pl">Polish</option><option value="cz">Czech</option><option value="en">English</option></select></div><button type="button" onClick={props.onReview} disabled={props.preparing}>Review email</button><button type="button" onClick={props.onDownload} disabled={props.generating}>Download PDF</button></div></details>
    </div>
  </div>
  {(props.previewing || props.previewUrl) && <div className="booking-pdf-preview-backdrop" role="dialog" aria-modal="true" aria-label="Booking confirmation preview">{props.previewing ? <div className="booking-pdf-loading"><span className="booking-pdf-spinner" aria-hidden="true" /><strong>{props.previewPhase === 'generating' ? 'Generating PDF' : 'Loading PDF'}</strong></div> : <div className="booking-pdf-preview-modal"><div className="booking-pdf-preview-header"><h3>Booking Confirmation Preview</h3><div className="booking-pdf-preview-actions"><a href={props.previewUrl} download={props.previewFileName} className="edit-btn">Download</a><button type="button" onClick={props.onClosePreview} className="booking-pdf-preview-close" aria-label="Close PDF preview"><Icon component={FiX} /></button></div></div><iframe src={props.previewUrl} title={props.previewFileName || 'Booking confirmation preview'} className="booking-pdf-preview-frame" /></div>}</div>}
  <div className="booking-detail-tabs" role="tablist" aria-label="Booking sections">{bookingDetailTabs.map(tab => <button key={tab.key} type="button" className={`booking-detail-tab ${props.activeTab === tab.key ? 'active' : ''}`} onClick={() => props.onTabChange(tab.key)} role="tab" aria-selected={props.activeTab === tab.key}><span>{tab.label}</span>{tab.key === 'requirements' && props.requirementsStatus && (props.requirementsStatus.missing > 0 ? <span className="booking-requirements-tab-badge is-missing" aria-label={`${props.requirementsStatus.missing} missing requirements`}>{props.requirementsStatus.missing}</span> : <span className="booking-requirements-tab-badge is-complete" aria-label="All requirements complete"><Icon component={FiCheck} /></span>)}</button>)}</div>
</>;
export default BookingDetailShell;
