import { communicationsApi } from '../services/api';
import { BookingConfirmationLanguage } from './bookingConfirmationWorkflow';
export const escapeEmailHtml = (value: any) => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char] || char));
export const interpolateEmail = (template: string, variables: Record<string, any>) => String(template || '').replace(/\{\{\s*([\w.]+)\s*\}\}/g, (_match, path) => { const value = path.split('.').reduce((current: any, key: string) => current?.[key], variables); return value == null ? '' : String(value); });
const copy: Record<BookingConfirmationLanguage, any> = {
  en: { subject: 'Booking confirmation', hello: 'Hello', intro: 'We are excited to welcome you to our retreat', attached: 'A PDF copy of your booking confirmation is attached.', more: 'We will email more information as we get closer to the retreat.', closing: 'Warmly,', none: 'None', labels: ['Booking number','Booking type','Status','Client','Retreat','Location town','Dates','Check-in','Check-out','Address','Google map','Special requests'] },
  cz: { subject: 'Potvrzení rezervace', hello: 'Dobrý den', intro: 'Těšíme se, že vás přivítáme na našem pobytu', attached: 'PDF potvrzení rezervace je přiloženo k tomuto e-mailu.', more: 'Další informace vám pošleme e-mailem, až se bude termín pobytu blížit.', closing: 'S pozdravem,', none: 'Žádné', labels: ['Číslo rezervace','Typ rezervace','Stav','Klient','Pobyt','Místo','Termín','Příjezd','Odjezd','Adresa','Google mapa','Speciální požadavky'] },
  pl: { subject: 'Potwierdzenie rezerwacji', hello: 'Dzień dobry', intro: 'Cieszymy się, że będziemy mogli powitać Cię na naszym pobycie', attached: 'Potwierdzenie rezerwacji w PDF jest załączone do tej wiadomości.', more: 'Prześlemy więcej informacji e-mailem bliżej terminu pobytu.', closing: 'Serdecznie,', none: 'Brak', labels: ['Numer rezerwacji','Typ rezerwacji','Status','Klient','Pobyt','Miejscowość','Termin','Przyjazd','Wyjazd','Adres','Mapa Google','Specjalne prośby'] },
};
const name = (client: any) => String(client?.fullName || client?.name || [client?.firstName || client?.fname, client?.lastName || client?.lname].filter(Boolean).join(' ')).trim();
const field = (retreat: any, ...keys: string[]) => { for (const key of keys) { const value = key.split('.').reduce((current, part) => current?.[part], retreat); if (value) return String(value).trim(); } return ''; };
export const localizedDate = (value: any, language: BookingConfirmationLanguage) => { if (!value) return 'N/A'; const date = new Date(value); return Number.isNaN(date.getTime()) ? 'N/A' : date.toLocaleDateString(language === 'cz' ? 'cs-CZ' : language === 'pl' ? 'pl-PL' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC' }); };
export const confirmationVariables = (booking: any, language: BookingConfirmationLanguage) => {
  const client = booking?.clientId || booking?.clientDetails || {}; const retreat = booking?.retreatId || booking?.retreatDetails || {}; const text = copy[language]; const number = String(booking?.bookingNumber || booking?.booking_number || booking?.display_id || booking?.displayId || 'N/A'); const clientName = name(client) || 'N/A'; const firstName = client?.firstName || client?.fname || 'there'; const start = retreat?.startDate || retreat?.dates?.startDate; const end = retreat?.endDate || retreat?.dates?.endDate; const dates = start && end ? `${localizedDate(start, language)} - ${localizedDate(end, language)}` : localizedDate(start || end, language); const town = field(retreat, 'location_town','locationTown','generalTown','house.generalTown','house.city','location') || 'N/A'; const address = field(retreat, 'address','house.address','houseId.address') || town; const map = field(retreat, 'googleMapLink','google_map_link','house.googleMapLink','houseId.googleMapLink') || 'N/A'; const startTime = field(retreat, 'startTime','start_time','dates.startTime'); const endTime = field(retreat, 'endTime','end_time','dates.endTime'); const checkIn = `${localizedDate(start, language)}${startTime ? ` ${startTime}` : ''}`; const checkOut = `${localizedDate(end, language)}${endTime ? ` ${endTime}` : ''}`; const special = booking?.specialRequests || text.none; const bookingType = `${booking?.bookingType === 'booster' ? 'B' : 'F'} / ${retreat?.code || retreat?.retreatCode || 'RET'}`;
  return { client: { firstName, fullName: clientName }, booking: { number, type: bookingType, status: booking?.status || 'pending', specialRequests: special }, retreat: { name: retreat?.name || 'N/A', locationTown: town, dateRange: dates, checkIn, checkOut, startTime, endTime, address, googleMapLink: map }, bookingNumber: number, bookingType, bookingStatus: booking?.status || 'pending', clientFirstName: firstName, clientFullName: clientName, clientName, retreatName: retreat?.name || 'N/A', retreatCode: retreat?.code || retreat?.retreatCode || 'RET', retreatLocationTown: town, locationTown: town, retreatDateRange: dates, retreatCheckIn: checkIn, retreatCheckOut: checkOut, retreatAddress: address, retreatGoogleMapLink: map, specialRequests: special };
};
export const composeBookingConfirmationEmail = async (booking: any, language: BookingConfirmationLanguage) => {
  const variables = confirmationVariables(booking, language); try { const response = await communicationsApi.getTemplateByCategoryAndLanguage('booking_confirmation', language); const template = response.data; if (template?.bodyText && template?.subject) { const bodyText = interpolateEmail(template.bodyText, variables); return { templateId: template._id, bookingFlowStepKey: template.bookingFlowStepKey || 'booking_confirmation_sent', bookingFlowStatusOnSend: template.bookingFlowStatusOnSend || 'sent', subject: interpolateEmail(template.subject, variables), bodyText, bodyHtml: template.bodyHtml ? interpolateEmail(template.bodyHtml, variables) : `<pre>${escapeEmailHtml(bodyText)}</pre>`, variables }; } } catch { /* fallback below */ }
  const text = copy[language]; const values = [variables.bookingNumber, variables.bookingType, variables.bookingStatus, variables.clientName, variables.retreatName, variables.locationTown, variables.retreatDateRange, variables.retreatCheckIn, variables.retreatCheckOut, variables.retreatAddress, variables.retreatGoogleMapLink, variables.specialRequests]; const rows = text.labels.map((label: string, index: number) => [label, values[index]]); const bodyText = [`${text.hello} ${variables.clientFirstName},`, '', `${text.intro} ${variables.locationTown} (${variables.retreatDateRange}).`, '', text.attached, '', ...rows.map(([label, value]: string[]) => `${label}: ${value}`), '', text.more, '', text.closing, 'IbogaSpirit.cz'].join('\n'); const rowHtml = rows.map(([label, value]: string[]) => `<tr><td>${escapeEmailHtml(label)}</td><td>${escapeEmailHtml(value)}</td></tr>`).join(''); return { bookingFlowStepKey: 'booking_confirmation_sent', bookingFlowStatusOnSend: 'sent', subject: `${text.subject} ${variables.bookingNumber}`, bodyText, bodyHtml: `<div><p>${escapeEmailHtml(text.hello)} ${escapeEmailHtml(variables.clientFirstName)},</p><table>${rowHtml}</table><p>${escapeEmailHtml(text.closing)}<br/>IbogaSpirit.cz</p></div>`, variables };
};
