import React from 'react';
import { Link } from 'react-router-dom';
import { FileText, Link2, ListPlus, Mail, Upload } from 'lucide-react';
import { BookingDocument, BookingFlowAction, BookingFlowActionLog, BookingFlowItem, MedicalArtifact } from '../types';
import { ArtifactLinkConfig } from './bookingStepMedicalLinks';
import { BookingStepMatrixRow } from './bookingStepRows';
import { humanizeBookingStepDocumentKey } from './bookingStepControlRules';
import { shouldShowArtifactUploadFallback } from './BookingStepsMatrix.helpers';
import BookingStepActionHistory from './BookingStepActionHistory';

type Props = {
  item: BookingFlowItem; row: BookingStepMatrixRow; actions: BookingFlowAction[]; logs: BookingFlowActionLog[]; isEditing: boolean; saving: string; canRemind: boolean;
  artifactConfig?: ArtifactLinkConfig; configuredDocumentType: string; relatedDocument?: BookingDocument; relatedArtifact?: MedicalArtifact; relatedArtifactId?: string; linkableArtifactCount: number;
  onRun: (action: BookingFlowAction) => void; onUpload: (action: BookingFlowAction, files: FileList | null) => void; onLinkMrr: (action: BookingFlowAction) => void;
  onReminder: () => void; onAutomation: () => void; onLinkArtifact: () => void; onOpenDocuments: () => void;
};

const FileInput = ({ disabled, onChange }: { disabled: boolean; onChange: (files: FileList | null) => void }) => <input aria-label="Upload files" type="file" className="hidden" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx,.heic,.heif" multiple disabled={disabled} onChange={event => { onChange(event.target.files); event.target.value = ''; }} />;
const actionText = (action: BookingFlowAction, count: number, pending: boolean) => pending ? '...' : count > 0 && action.allowRepeat !== false ? `${action.label} again` : action.label;

const BookingStepActionControls: React.FC<Props> = ({ item, row, actions, logs, isEditing, saving, canRemind, artifactConfig, configuredDocumentType, relatedDocument, relatedArtifact, relatedArtifactId, linkableArtifactCount, onRun, onUpload, onLinkMrr, onReminder, onAutomation, onLinkArtifact, onOpenDocuments }) => <>
  {actions.map(action => { const actionLogs = logs.filter(log => (log.actionKey || 'default_email') === action.key); const savingKey = action.type === 'upload' ? `upload:${item._id}:${action.key}` : `action:${item._id}:${action.key}`; const pending = saving === savingKey; return action.type === 'upload' ? <label key={action.key} className={`inline-flex items-center justify-center gap-1 rounded-md border border-blue-200 bg-white px-2 py-1 text-xs font-medium text-blue-700 hover:bg-blue-50 ${!isEditing || pending ? 'cursor-not-allowed opacity-50' : 'cursor-pointer'}`} title={isEditing ? 'Upload document for this booking step' : 'Unlock editing to upload documents'}><Upload className="h-3.5 w-3.5" />{actionText(action, actionLogs.length, pending)}<FileInput disabled={!isEditing || Boolean(saving)} onChange={files => onUpload(action, files)} /></label> : action.type === 'link_mrr' ? <button key={action.key} type="button" disabled={!isEditing || pending} onClick={() => onLinkMrr(action)} className="inline-flex items-center justify-center gap-1 rounded-md border border-indigo-200 bg-indigo-50 px-2 py-1 text-xs font-medium text-indigo-700 hover:bg-indigo-100 disabled:opacity-50" title={isEditing ? 'Link an existing medical review request' : 'Unlock editing to link a medical review request'}><Link2 className="h-3.5 w-3.5" />{actionText(action, actionLogs.length, pending)}</button> : <button key={action.key} type="button" disabled={!isEditing || pending} onClick={() => onRun(action)} className="inline-flex items-center justify-center gap-1 rounded-md border border-blue-200 bg-white px-2 py-1 text-xs font-medium text-blue-700 hover:bg-blue-50 disabled:opacity-50" title={isEditing ? action.type : 'Unlock editing to run actions'}>{action.type === 'email' && <Mail className="h-3.5 w-3.5" />}{actionText(action, actionLogs.length, pending)}</button>; })}
  {canRemind && <><button type="button" disabled={saving === `reminder-preview:${item._id}`} onClick={onReminder} className="inline-flex items-center justify-center gap-1 rounded-md border border-amber-300 bg-amber-50 px-2 py-1 text-xs font-semibold text-amber-900 hover:bg-amber-100 disabled:opacity-50" title={`Preview a reminder for ${item.title}`}><Mail className="h-3.5 w-3.5" />{saving === `reminder-preview:${item._id}` ? 'Preparing...' : `Remind: ${item.title}`}</button><button type="button" onClick={onAutomation} className={`inline-flex items-center justify-center gap-1 rounded-md border px-2 py-1 text-xs font-medium ${item.automationPaused ? 'border-gray-300 bg-gray-100 text-gray-600' : 'border-violet-200 bg-violet-50 text-violet-800 hover:bg-violet-100'}`} title="View automated reminder sequence"><ListPlus className="h-3.5 w-3.5" />{item.automationPaused ? 'Automation paused' : 'Automation'}</button></>}
  {shouldShowArtifactUploadFallback(artifactConfig, isEditing, actions.some(action => action.type === 'upload')) && <label className="inline-flex cursor-pointer items-center justify-center gap-1 rounded-md border border-amber-200 bg-amber-50 px-2 py-1 text-xs font-medium text-amber-800 hover:bg-amber-100" title={`Upload a new ${artifactConfig?.label || 'artifact'} document`}><Upload className="h-3.5 w-3.5" />Upload {artifactConfig?.artifactType === 'medications_form' ? 'form' : 'new'}<FileInput disabled={Boolean(saving)} onChange={files => onUpload({ key: `artifact-upload:${item._id || row.key}`, label: `Upload ${artifactConfig?.label || 'artifact'}`, type: 'upload' }, files)} /></label>}
  {configuredDocumentType && isEditing && !actions.some(action => action.type === 'upload') && <label className="inline-flex cursor-pointer items-center justify-center gap-1 rounded-md border border-blue-200 bg-blue-50 px-2 py-1 text-xs font-medium text-blue-800 hover:bg-blue-100" title={`Upload ${humanizeBookingStepDocumentKey(configuredDocumentType)} for this booking step`}><Upload className="h-3.5 w-3.5" />Upload {humanizeBookingStepDocumentKey(configuredDocumentType)}<FileInput disabled={Boolean(saving)} onChange={files => onUpload({ key: `document-upload:${item._id || row.key}`, label: `Upload ${humanizeBookingStepDocumentKey(configuredDocumentType)}`, type: 'upload' }, files)} /></label>}
  {relatedDocument?._id && <button type="button" onClick={onOpenDocuments} className="inline-flex items-center justify-center gap-1 rounded-md border border-emerald-200 bg-emerald-50 px-2 py-1 text-xs font-medium text-emerald-800 hover:bg-emerald-100" title="Open Document Library"><FileText className="h-3.5 w-3.5" />Document #{relatedDocument.display_id || 'linked'}</button>}
  {relatedArtifactId && <Link to={`/admin/medical-artifacts/${relatedArtifactId}`} className="inline-flex items-center justify-center gap-1 rounded-md border border-purple-200 bg-purple-50 px-2 py-1 text-xs font-medium text-purple-800 hover:bg-purple-100" title={`Open uploaded ${artifactConfig?.label || 'medical artifact'}`}><FileText className="h-3.5 w-3.5" />Artifact #{relatedArtifact?.display_id || relatedArtifactId.slice(-6)}</Link>}
  {!relatedArtifactId && artifactConfig && linkableArtifactCount > 0 && <button type="button" disabled={!isEditing} onClick={onLinkArtifact} className="inline-flex items-center justify-center gap-1 rounded-md border border-amber-200 bg-amber-50 px-2 py-1 text-xs font-medium text-amber-800 hover:bg-amber-100 disabled:opacity-50" title={isEditing ? `Link an existing ${artifactConfig.label} artifact to this step` : 'Unlock editing to link an existing artifact'}><FileText className="h-3.5 w-3.5" />Link existing</button>}
  {logs.length > 0 && <div className="space-y-0.5 text-[11px] text-blue-800">{actions.map(action => ({ action, logs: logs.filter(log => (log.actionKey || 'default_email') === action.key) })).filter(entry => entry.logs.length > 0).map(({ action, logs: actionLogs }) => <BookingStepActionHistory key={action.key} label={action.label} logs={actionLogs} />)}</div>}
</>;

export default BookingStepActionControls;
