import React, { useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { FiX } from 'react-icons/fi';
import { artifactMatches, documentMatches, RequirementDefinition } from './bookingRequirementRows';
import { useBookingRequirements } from './useBookingRequirements';
const CloseIcon: React.FC = () => React.createElement(FiX as any);

export interface BookingRequirementsPanelProps { bookingId: string; clientId?: string; retreatId?: string; refreshKey: number; onStatusChange?: (status: { missing: number; total: number }) => void; }
export const routePrefixForPath = (pathname: string) => { const first = pathname.split('/').filter(Boolean)[0]; return ['admin', 'medical', 'staff', 'user'].includes(first) ? `/${first}` : ''; };
const time = (value?: Date | string) => new Date(value || 0).getTime();
export const formatRequirementDate = (value?: Date | string) => { if (!value) return 'N/A'; const date = new Date(value); return Number.isNaN(date.getTime()) ? 'N/A' : date.toLocaleString('en-US', { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }); };

const BookingRequirementsPanel: React.FC<BookingRequirementsPanelProps> = (props) => {
  const navigate = useNavigate(); const location = useLocation(); const routePrefix = useMemo(() => routePrefixForPath(location.pathname), [location.pathname]);
  const [selected, setSelected] = useState<RequirementDefinition | null>(null); const state = useBookingRequirements(props);
  const initialLoad = state.loading && state.rows.every(row => row.relatedItems.length === 0 && !row.latestArtifact && !row.latestDocument);
  const artifacts = selected ? state.libraryArtifacts.filter(item => item._id && artifactMatches(item, selected)).sort((a, b) => time(b.receivedAt || b.createdAt) - time(a.receivedAt || a.createdAt)) : [];
  const documents = selected ? state.libraryDocuments.filter(item => item._id && documentMatches(item, selected) && item.files?.length).sort((a, b) => time(b.receivedAt || b.createdAt) - time(a.receivedAt || a.createdAt)) : [];
  const link = async (kind: 'artifact' | 'document', id: string) => { if (selected && await state.link(selected, kind, id)) setSelected(null); };
  return <div className="detail-section">
    <div className="section-header"><h3 className="pdf-section-title">Mandatory Booking Requirements</h3><button className="edit-btn" type="button" onClick={state.reload} disabled={state.loading}>{state.loading ? 'Refreshing...' : 'Refresh'}</button></div>
    <p className="text-sm text-gray-600 mb-3">Driven by booking-flow requirements and linked booking artifacts/review requests.</p>{state.error && <div className="alert alert-danger">{state.error}</div>}
    {initialLoad ? <div className="rounded border border-gray-200 bg-gray-50 px-4 py-8 text-center text-sm text-gray-600">Loading booking requirements…</div> : <div className="overflow-x-auto"><table className="min-w-full divide-y divide-gray-200 text-sm"><thead className="bg-gray-50"><tr>{['Requirement', 'Required', 'Status', 'Reviewed', 'Latest File / Review'].map(label => <th className="px-3 py-2 text-left font-medium text-gray-600" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y divide-gray-100 bg-white">{state.rows.map(row => { const flowStatus = row.relatedItems[0]?.status; return <tr key={row.key}>
      <td className="px-3 py-2 font-medium text-gray-900">{row.label}</td><td className="px-3 py-2">{row.required ? 'Yes' : 'No'}</td><td className="px-3 py-2"><span className={`status-badge ${row.uploaded ? 'badge-received' : 'badge-pending'}`}>{flowStatus || (row.uploaded ? 'received' : 'missing')}</span></td><td className="px-3 py-2"><span className={`status-badge ${row.reviewed ? 'badge-approved' : 'badge-pending'}`}>{row.reviewed ? (row.latestReview?.reviewDecision || row.latestReview?.status || 'reviewed') : 'pending'}</span></td><td className="px-3 py-2"><div className="flex flex-wrap gap-2">
      {row.latestArtifact?._id && <button className="text-blue-700 hover:underline" type="button" onClick={() => navigate(`${routePrefix}/medical-artifacts/${row.latestArtifact?._id}`)}>Artifact #{row.latestArtifact.display_id || row.latestArtifact._id}</button>}
      {row.latestDocument?._id && <button className="text-blue-700 hover:underline" type="button" onClick={() => navigate(`${routePrefix}/booking-documents`)}>Document #{row.latestDocument.display_id || row.latestDocument._id}</button>}
      {row.latestReview?._id && <button className="text-blue-700 hover:underline" type="button" onClick={() => navigate(`${routePrefix}/medical-review-requests/${row.latestReview?._id}`)}>Review #{row.latestReview.display_id || row.latestReview._id}</button>}
      {row.linkable !== false && <button className="font-semibold text-indigo-700 hover:underline" type="button" onClick={() => setSelected(row)}>{row.latestArtifact || row.latestDocument ? 'Change linked record' : 'Find and link existing record'}</button>}</div></td>
    </tr>; })}</tbody></table></div>}
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" role="dialog" aria-modal="true" aria-labelledby="requirement-link-title"><section className="max-h-[85vh] w-full max-w-4xl overflow-hidden rounded-xl bg-white shadow-2xl"><header className="flex items-start justify-between gap-4 border-b border-gray-200 px-5 py-4"><div><h2 id="requirement-link-title" className="text-lg font-semibold text-gray-900">Link {selected.label}</h2><p className="mt-1 text-sm text-gray-500">Looking in {selected.library === 'both' ? 'Medical Artifacts and Booking Documents' : selected.library === 'medical_artifacts' ? 'Medical Artifacts' : 'Booking Documents'} for this client. Newest records are shown first.</p></div><button className="rounded-md border border-gray-300 p-2 text-gray-600 hover:bg-gray-50" type="button" onClick={() => setSelected(null)} aria-label="Close record lookup"><CloseIcon /></button></header><div className="max-h-[68vh] space-y-5 overflow-y-auto p-5">
      {(selected.library === 'medical_artifacts' || selected.library === 'both') && <LookupSection title="Medical Artifacts" empty="No matching medical artifacts found for this client." records={artifacts.map((item, index) => ({ id: item._id!, title: `#${item.display_id || item._id} ${item.title || item.documentType || item.artifactType}`, detail: `${item.artifactType || 'artifact'} · ${item.documentStage || 'entry'} · ${formatRequirementDate(item.receivedAt || item.createdAt)} · ${(item.files || []).length} file(s)`, latest: index === 0 }))} kind="artifact" linkingId={state.linkingRecordId} onLink={link} />}
      {(selected.library === 'booking_documents' || selected.library === 'both') && <LookupSection title="Booking Documents" empty="No matching booking documents found for this client." records={documents.map((item, index) => ({ id: item._id!, title: `#${item.display_id || item._id} ${item.title || item.documentType}`, detail: `${item.documentType} · ${formatRequirementDate(item.receivedAt || item.createdAt)} · ${(item.files || []).length} file(s)`, latest: index === 0 }))} kind="document" linkingId={state.linkingRecordId} onLink={link} />}
    </div></section></div>}
  </div>;
};

const LookupSection: React.FC<{ title: string; empty: string; records: Array<{ id: string; title: string; detail: string; latest: boolean }>; kind: 'artifact' | 'document'; linkingId: string; onLink: (kind: 'artifact' | 'document', id: string) => void }> = ({ title, empty, records, kind, linkingId, onLink }) => <div><h3 className="mb-2 text-sm font-semibold uppercase tracking-wide text-gray-600">{title}</h3>{records.length ? <div className="space-y-2">{records.map(record => <div className={`flex flex-col gap-3 rounded-lg border p-3 sm:flex-row sm:items-center sm:justify-between ${record.latest ? kind === 'artifact' ? 'border-indigo-300 bg-indigo-50' : 'border-blue-300 bg-blue-50' : 'border-gray-200'}`} key={record.id}><div><div className="font-semibold text-gray-900">{record.title}</div><div className="mt-1 text-xs text-gray-500">{record.detail}{record.latest ? ' · latest' : ''}</div></div><button className={`rounded-md px-3 py-2 text-sm font-semibold text-white disabled:opacity-50 ${kind === 'artifact' ? 'bg-indigo-700 hover:bg-indigo-800' : 'bg-blue-700 hover:bg-blue-800'}`} type="button" disabled={Boolean(linkingId)} onClick={() => onLink(kind, record.id)}>{linkingId === `${kind}:${record.id}` ? 'Linking...' : `Link ${kind}`}</button></div>)}</div> : <p className="rounded-lg border border-dashed border-gray-300 p-4 text-sm text-gray-500">{empty}</p>}</div>;
export default BookingRequirementsPanel;
