import React from 'react';
import { X } from 'lucide-react';
import { BookingFlowActionLog, BookingFlowItem } from '../types';
import { formatStepDateTime } from './bookingStepPresentation';

export type BookingStepReminderModalState = { item: BookingFlowItem; to: string; subject: string; bodyText: string; dueDate?: string; uploadUrl: string; reminderCount: number; lastReminderAt?: string; duplicateBlocked: boolean; duplicateWarning: boolean; suggestedFollowUpDate: string; history: BookingFlowActionLog[] };
export type BookingStepAutomationModalState = { item: BookingFlowItem; paused: boolean; pauseReason?: string; resumeAt?: string; schedules: Array<{ _id: string; ruleKey: string; actionType: 'send_email' | 'create_staff_task'; scheduledFor: string; status: string; executedAt?: string; lastError?: string }> };

export const BookingStepReminderModal: React.FC<{ state: BookingStepReminderModalState; saving: string; onChange: (state: BookingStepReminderModalState) => void; onClose: () => void; onSend: () => void }> = ({ state, saving, onChange, onClose, onSend }) => <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="flex max-h-[92vh] w-full max-w-3xl flex-col rounded-xl bg-white shadow-2xl">
  <div className="flex items-start justify-between border-b border-gray-200 px-5 py-4"><div><h2 className="text-lg font-semibold text-gray-900">Reminder: {state.item.title}</h2><p className="mt-1 text-sm text-gray-500">Preview and edit before sending to {state.to}.</p></div><button type="button" onClick={onClose} className="rounded-md p-2 text-gray-500 hover:bg-gray-100" aria-label="Close reminder preview"><X className="h-5 w-5" /></button></div>
  <div className="flex-1 space-y-4 overflow-y-auto px-5 py-5">
    {(state.duplicateWarning || state.reminderCount > 0) && <div className={`rounded-lg border p-3 text-sm ${state.duplicateBlocked ? 'border-red-300 bg-red-50 text-red-900' : 'border-amber-300 bg-amber-50 text-amber-900'}`}><strong>{state.reminderCount} previous reminder{state.reminderCount === 1 ? '' : 's'}.</strong>{state.lastReminderAt && ` Last sent ${formatStepDateTime(state.lastReminderAt)}.`}{state.duplicateBlocked && ' Another reminder requires confirmation because the last one was sent less than 24 hours ago.'}</div>}
    <div className="grid gap-3 rounded-lg border border-gray-200 bg-gray-50 p-3 text-sm sm:grid-cols-3"><div><span className="block text-xs uppercase text-gray-500">Deadline</span><strong>{state.dueDate || 'Not set'}</strong></div><div><span className="block text-xs uppercase text-gray-500">Follow up</span><input aria-label="Follow up" type="date" value={state.suggestedFollowUpDate} onChange={(event) => onChange({ ...state, suggestedFollowUpDate: event.target.value })} className="mt-1 rounded border border-gray-300 px-2 py-1" /></div><div><span className="block text-xs uppercase text-gray-500">Upload link</span><a href={state.uploadUrl} target="_blank" rel="noreferrer" className="font-medium text-blue-700 underline">Open client step</a></div></div>
    <label className="block"><span className="mb-1 block text-sm font-medium text-gray-700">Subject</span><input aria-label="Subject" value={state.subject} onChange={(event) => onChange({ ...state, subject: event.target.value })} className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm" /></label>
    <label className="block"><span className="mb-1 block text-sm font-medium text-gray-700">Message</span><textarea aria-label="Message" value={state.bodyText} onChange={(event) => onChange({ ...state, bodyText: event.target.value })} rows={13} className="w-full rounded-md border border-gray-300 px-3 py-2 font-mono text-sm" /></label>
    {state.history.length > 0 && <details className="rounded-lg border border-gray-200 p-3 text-sm"><summary className="cursor-pointer font-medium">Previous reminders</summary><ul className="mt-2 space-y-2 text-gray-600">{state.history.map((log, index) => <li key={log._id || index}>{formatStepDateTime(log.performedAt)}{log.performedByEmail ? ` · ${log.performedByEmail}` : ''}</li>)}</ul></details>}
  </div><div className="flex justify-end gap-2 border-t border-gray-200 px-5 py-4"><button type="button" onClick={onClose} className="rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700">Cancel</button><button type="button" disabled={!state.subject.trim() || !state.bodyText.trim() || saving === `reminder-send:${state.item._id}`} onClick={onSend} className="rounded-md bg-amber-700 px-4 py-2 text-sm font-semibold text-white hover:bg-amber-800 disabled:opacity-50">{saving === `reminder-send:${state.item._id}` ? 'Sending...' : 'Send reminder'}</button></div>
</div></div>;

export const BookingStepAutomationModal: React.FC<{ state: BookingStepAutomationModalState; saving: string; onClose: () => void; onToggle: () => void }> = ({ state, saving, onClose, onToggle }) => <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-2xl rounded-xl bg-white shadow-2xl">
  <div className="flex items-start justify-between border-b border-gray-200 px-5 py-4"><div><h2 className="text-lg font-semibold text-gray-900">Automated reminders: {state.item.title}</h2><p className="mt-1 text-sm text-gray-500">Generated from the step deadline. Completed steps cancel future actions automatically.</p></div><button aria-label="Close automation" type="button" onClick={onClose} className="rounded-md p-2 text-gray-500 hover:bg-gray-100"><X className="h-5 w-5" /></button></div>
  <div className="space-y-4 p-5">{state.paused && <div className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900"><strong>Automation paused.</strong>{state.pauseReason ? ` ${state.pauseReason}` : ''}</div>}<div className="overflow-hidden rounded-lg border border-gray-200"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-3 py-2">When</th><th className="px-3 py-2">Action</th><th className="px-3 py-2">Status</th></tr></thead><tbody className="divide-y divide-gray-100">{state.schedules.map((schedule) => <tr key={schedule._id}><td className="px-3 py-2">{formatStepDateTime(schedule.scheduledFor)}</td><td className="px-3 py-2">{schedule.ruleKey.replace(/_/g, ' ')}</td><td className="px-3 py-2 font-medium">{schedule.status.replace(/_/g, ' ')}</td></tr>)}{state.schedules.length === 0 && <tr><td colSpan={3} className="px-3 py-6 text-center text-gray-500">No automation is scheduled for this step.</td></tr>}</tbody></table></div></div>
  <div className="flex justify-between border-t border-gray-200 px-5 py-4"><button type="button" onClick={onToggle} disabled={saving === `automation-toggle:${state.item._id}`} className={`rounded-md px-4 py-2 text-sm font-semibold ${state.paused ? 'bg-green-700 text-white' : 'border border-gray-300 text-gray-700'}`}>{state.paused ? 'Resume automation' : 'Pause for this client'}</button><button type="button" onClick={onClose} className="rounded-md bg-gray-900 px-4 py-2 text-sm font-semibold text-white">Close</button></div>
</div></div>;
