import React from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import BookingMedicalOverviewPanel, { artifactTitle, medicalOverviewError, medicalRoutePrefix, reviewDecisionClass, reviewDecisionText, shortMedicalDate } from './BookingMedicalOverviewPanel';
import { loadBookingMedicalOverview } from './bookingMedicalOverviewData';
const mockNavigate = jest.fn();
jest.mock('react-router-dom', () => ({ ...jest.requireActual('react-router-dom'), useNavigate: () => mockNavigate }));
jest.mock('./bookingMedicalOverviewData', () => ({ ...jest.requireActual('./bookingMedicalOverviewData'), loadBookingMedicalOverview: jest.fn() }));
jest.mock('./BookingMedicalUpload', () => (props: any) => <button onClick={props.onUploadComplete}>Mock medical upload {props.uploadRequest?.stage}</button>);
const load = loadBookingMedicalOverview as jest.Mock;
const result = (overrides: any = {}) => ({ artifacts: [], reviewsByArtifact: {}, medicationPlan: [], ...overrides });
const view = (props: any = {}, path = '/admin/bookings/b') => render(<MemoryRouter initialEntries={[path]}><BookingMedicalOverviewPanel bookingId="b" refreshKey={0} onUploadComplete={jest.fn()} {...props} /></MemoryRouter>);

describe('BookingMedicalOverviewPanel', () => {
  beforeEach(() => { jest.clearAllMocks(); load.mockResolvedValue(result()); });
  it('loads and renders missing/empty states, then refreshes', async () => { view(); await waitFor(() => expect(load).toHaveBeenCalledWith('b', undefined, undefined)); expect(screen.getAllByText('Missing')).toHaveLength(2); expect(screen.getByText(/Medical upload needs/)).toBeInTheDocument(); await waitFor(() => expect(screen.getByText('Refresh')).toBeInTheDocument()); fireEvent.click(screen.getByText('Refresh')); await waitFor(() => expect(load).toHaveBeenCalledTimes(2)); });
  it('shows API errors and retries', async () => { load.mockRejectedValueOnce({ response: { data: { message: 'offline' } } }).mockResolvedValueOnce(result()); view(); expect(await screen.findByRole('alert')).toHaveTextContent('offline'); fireEvent.click(screen.getByText('Refresh')); await waitFor(() => expect(screen.queryByRole('alert')).not.toBeInTheDocument()); });
  it('renders all-clear and navigates to medication plan', async () => { load.mockResolvedValue(result({ medicationPlan: [{ _id: 'p', description: 'No changes', metadata: { medicationStopPlanAllClear: true } }] })); view(); expect(await screen.findByText(/All good/)).toBeInTheDocument(); fireEvent.click(screen.getByText('Edit medication plan')); expect(mockNavigate).toHaveBeenCalledWith('/admin/bookings/b/medication-stop-plan'); });
  it('renders dated, undated, overdue and completed preparation items', async () => { load.mockResolvedValue(result({ medicationPlan: [{ _id: 'a', title: 'Stop A', description: 'desc', dueDate: '2020-01-01', status: 'pending', metadata: { taperPlan: 'slow' } }, { _id: 'b', title: 'Stop B', status: 'completed', dueDate: '2020-01-01', metadata: {} }, { _id: 'c', title: 'Stop C', metadata: {} }] })); view(); expect(await screen.findByText('Stop A')).toBeInTheDocument(); expect(screen.getByText('slow')).toBeInTheDocument(); expect(screen.getByText('Date not set')).toBeInTheDocument(); expect(screen.getByText('Stop A').closest('.is-overdue')).toBeTruthy(); expect(screen.getByText('Stop B').closest('.is-upcoming')).toBeTruthy(); });
  it('renders artifacts, reviews, navigation and upload callbacks', async () => { const callback = jest.fn(); load.mockResolvedValue(result({ artifacts: [{ _id: 'a', display_id: 4, artifactType: 'ekg', documentType: 'EKG', documentStage: 'entry', files: [{}], createdAt: '2026-01-01' }], reviewsByArtifact: { a: [{ _id: 'r', display_id: 8, status: 'approved', reviewNotes: 'fine', reviewedAt: '2026-02-01' }] } })); view({ clientId: 'c', retreatId: 't', bookingNumber: 99, onUploadComplete: callback }); expect(await screen.findAllByText('Artifact #4')).toHaveLength(1); fireEvent.click(screen.getAllByText('Review #8')[0]); expect(mockNavigate).toHaveBeenCalledWith('/admin/medical-review-requests/r'); fireEvent.click(screen.getAllByText('Upload')[0]); expect(screen.getByText(/Mock medical upload entry/)).toBeInTheDocument(); fireEvent.click(screen.getByText(/Mock medical upload/)); await waitFor(() => expect(callback).toHaveBeenCalled()); expect(load).toHaveBeenCalledTimes(2); });
  it('offers MRR creation for an unreviewed artifact', async () => { load.mockResolvedValue(result({ artifacts: [{ _id: 'a', artifactType: 'ekg', documentType: 'EKG', documentStage: 'entry' }] })); view({}, '/medical/bookings/b'); expect(await screen.findAllByText('Create MRR')).toHaveLength(2); fireEvent.click(screen.getAllByText('Create MRR')[0]); expect(mockNavigate).toHaveBeenCalledWith('/medical/medical-review-requests/new?artifactId=a'); });
});

describe('medical overview helpers', () => {
  it('handles route prefixes and errors', () => { expect(medicalRoutePrefix('/staff/x')).toBe('/staff'); expect(medicalRoutePrefix('/bookings/x')).toBe(''); expect(medicalOverviewError({ response: { data: { message: 'api' } } })).toBe('api'); expect(medicalOverviewError(new Error('local'))).toBe('local'); expect(medicalOverviewError({})).toContain('Unable'); });
  it('maps review decisions', () => { expect(reviewDecisionText()).toBe('No decision'); expect(reviewDecisionText({ decision: 'caution' } as any)).toBe('caution'); expect(reviewDecisionClass({ reviewDecision: 'approved' } as any)).toBe('medical-decision-ok'); expect(reviewDecisionClass({ decision: 'needs info' } as any)).toBe('medical-decision-caution'); expect(reviewDecisionClass({ decision: 'rejected' } as any)).toBe('medical-decision-declined'); expect(reviewDecisionClass()).toBe('medical-decision-pending'); });
  it('formats dates and artifact titles', () => { expect(shortMedicalDate()).toBe('N/A'); expect(shortMedicalDate('bad')).toBe('N/A'); expect(shortMedicalDate('2026-06-01')).toContain('2026'); expect(artifactTitle({ title: 'EKG', ceremonyNumber: 2 } as any)).toBe('EKG - Ceremony #2'); expect(artifactTitle({} as any)).toBe('Medical record'); });
});
