import { artifactStepConfigByKey, getArtifactLinkCandidates, getArtifactStepConfig, getReviewRequestLinkCandidates, getReviewStepConfig, reviewDecisionToClassName, reviewDecisionToLabel, reviewStatusToDecision } from './bookingStepMedicalLinks';

const booking: any = { _id: 'b', bookingNumber: 1240, clientId: { _id: 'c' }, retreatId: 'r' };
describe('bookingStepMedicalLinks', () => {
  it('classifies exact and inferred artifact steps while excluding reviews', () => { expect(getArtifactStepConfig({ key: 'ekg_received', title: 'EKG' } as any)?.artifactType).toBe('ekg'); expect(getArtifactStepConfig({ key: 'custom', title: 'Medication form' } as any)?.artifactType).toBe('medications_form'); expect(getArtifactStepConfig({ key: 'entry_ekg_upload', title: 'Upload' } as any)?.artifactType).toBe('ekg'); expect(getArtifactStepConfig({ key: 'liver_received_custom', title: 'Liver received' } as any)?.artifactType).toBe('liver_panel'); expect(getArtifactStepConfig({ key: 'ekg_review', title: 'EKG review sent' } as any)).toBeUndefined(); expect(getArtifactStepConfig({ key: 'other', title: 'Other' } as any)).toBeUndefined(); });
  it('classifies exact and inferred review steps', () => { expect(getReviewStepConfig({ key: 'ekg_sent_for_review', title: '' })?.requestType).toBe('ekg_review'); expect(getReviewStepConfig({ key: 'custom', title: 'Send liver medical review' })?.requestType).toBe('liver_panel_review'); expect(getReviewStepConfig({ key: 'custom', title: 'Medication review sent' })?.requestType).toBe('medications_review'); expect(getReviewStepConfig({ key: 'custom', title: 'Generic review' })).toBeUndefined(); });
  it('maps all review decisions to labels and colors', () => { expect(['approved', 'rejected', 'caution', 'needs_resubmission', 'pending'].map(value => reviewStatusToDecision(value as any))).toEqual(['OK', 'NOT OK', 'caution', 'more_info_needed', '']); expect(reviewDecisionToLabel('NOT OK')).toBe('Declined'); expect(reviewDecisionToLabel('more_info_needed')).toBe('More info needed'); expect(reviewDecisionToLabel('x')).toBe(''); expect(reviewDecisionToClassName('OK')).toContain('green'); expect(reviewDecisionToClassName('NOT OK')).toContain('red'); expect(reviewDecisionToClassName('caution')).toContain('yellow'); expect(reviewDecisionToClassName('more_info_needed')).toContain('amber'); expect(reviewDecisionToClassName('')).toBe(''); });
  it('finds and sorts artifacts through booking, client, retreat, booking number, and unlinked fallback', () => { const config = artifactStepConfigByKey.ekg_received; const artifacts: any[] = [{ _id: 'wrong', artifactType: 'liver_panel' }, { _id: 'old', artifactType: 'ekg', clientId: 'c', createdAt: '2026-01-01' }, { _id: 'new', documentStage: 'entry', documentType: 'EKG', retreatId: 'r', createdAt: '2026-02-01' }, { _id: 'number', artifactType: 'ekg', title: 'Booking 1240 document' }, { _id: 'booking', artifactType: 'ekg', bookingId: 'b' }, { artifactType: 'ekg' }]; expect(getArtifactLinkCandidates(booking, artifacts, config).map(value => value._id)).toEqual(['new', 'old', 'number', 'booking']); expect(getArtifactLinkCandidates(booking, artifacts)).toEqual([]); });
  it('finds review requests and rejects conflicting links and medical context', () => { const config = getReviewStepConfig({ key: 'ekg_sent_for_review', title: '' })!; const requests: any[] = [{ _id: 'new', clientId: 'c', requestType: 'ekg_review', requestedAt: '2026-02-01' }, { _id: 'old', retreatId: 'r', requestType: 'ekg_review', requestedAt: '2026-01-01' }, { _id: 'item', bookingFlowItemId: 'i', requestType: 'ekg_review' }, { _id: 'other-item', bookingFlowItemId: 'x', clientId: 'c', requestType: 'ekg_review' }, { _id: 'wrong-type', clientId: 'c', requestType: 'liver_panel_review' }, { _id: 'wrong-artifact', clientId: 'c', requestType: 'ekg_review', artifactIds: [{ bookingId: 'other', artifactType: 'ekg' }] }]; expect(getReviewRequestLinkCandidates(booking, requests, config, 'i').map(value => value._id)).toEqual(['new', 'old', 'item']); expect(getReviewRequestLinkCandidates(booking, requests, undefined, 'i').map(value => value._id)).toContain('new'); });
});
