import { normalizeBookingStepKey, resolveConfiguredBookingStepActions } from './bookingStepActions';

const maps = (template: any = null, library: any = null) => [new Map(template ? [[template.key, template], [template._id, template]] : []), new Map(library ? [[library.key, library]] : [])] as any;
const action = (key: string, overrides: any = {}) => ({ key, label: key, type: 'manual', ...overrides });

describe('bookingStepActions', () => {
  it('normalizes keys and returns no actions without an item', () => { expect(normalizeBookingStepKey(' Contract Sent! ')).toBe('contract_sent'); expect(resolveConfiguredBookingStepActions(undefined, new Map(), new Map())).toEqual([]); });
  it('prefers item actions, filters inactive actions, sorts, and does not mutate source', () => { const source = [action('late', { order: 5 }), action('hidden', { active: false }), action('first', { order: -1 })]; const item: any = { key: 'step', title: 'Step', actions: source }; const result = resolveConfiguredBookingStepActions(item, new Map(), new Map()); expect(result.map(value => value.key)).toEqual(['first', 'late']); expect(source.map(value => value.key)).toEqual(['late', 'hidden', 'first']); });
  it('uses metadata before template and library actions', () => { const [templates, libraries] = maps({ _id: 't', key: 'step', actions: [action('template')] }, { key: 'step', actions: [action('library')] }); const item: any = { key: 'step', title: 'Step', templateId: 't', metadata: { actions: [action('metadata')] } }; expect(resolveConfiguredBookingStepActions(item, templates, libraries)[0].key).toBe('metadata'); });
  it('uses populated template actions then library actions', () => { const populated: any = { key: 'step', title: 'Step', templateId: { key: 'step', actions: [action('populated')] } }; expect(resolveConfiguredBookingStepActions(populated, new Map(), new Map())[0].key).toBe('populated'); const [templates, libraries] = maps(null, { key: 'step', actions: [action('library')] }); expect(resolveConfiguredBookingStepActions({ key: 'step', title: 'Step' } as any, templates, libraries)[0].key).toBe('library'); });
  it('adds a legacy email using item, template, or library configuration', () => { const [templates] = maps({ _id: 't', key: 'step', emailEnabled: true, emailTemplateId: 'email' }); const result = resolveConfiguredBookingStepActions({ key: 'step', title: 'Step', templateId: 't' } as any, templates, new Map()); expect(result[0]).toMatchObject({ key: 'default_email', emailTemplateId: 'email', type: 'email' }); });
  it('does not duplicate a configured email with a template id', () => { const item: any = { key: 'step', title: 'Step', emailEnabled: true, emailTemplateId: 'email', actions: [action('custom', { type: 'email', emailTemplateId: 'other' })] }; expect(resolveConfiguredBookingStepActions(item, new Map(), new Map())).toHaveLength(1); });
  it('adds contract fallback by key or title, but not when email exists', () => { expect(resolveConfiguredBookingStepActions({ key: 'contract_sent', title: 'Step' } as any, new Map(), new Map())[0].key).toBe('send_contract'); expect(resolveConfiguredBookingStepActions({ key: 'custom', title: 'Contract was sent', actions: [action('link')] } as any, new Map(), new Map())[0].key).toBe('send_contract'); const item: any = { key: 'contract_sent', title: 'Contract', actions: [action('email', { type: 'email' })] }; expect(resolveConfiguredBookingStepActions(item, new Map(), new Map()).map(value => value.key)).toEqual(['email']); });
});
