import React from 'react'; import { fireEvent, render, screen } from '@testing-library/react'; import BookingStepsToolbar from './BookingStepsToolbar';
const cb = () => ({ onViewMode: jest.fn(), onUnlock: jest.fn(), onSaveAndLock: jest.fn(), onRefresh: jest.fn(), onGenerate: jest.fn() });
const view = (p: any = {}) => { const c = cb(); render(<BookingStepsToolbar viewMode="detail" isEditing={false} saving="" message="" {...c} {...p} />); return c; };
describe('BookingStepsToolbar', () => {
  it('changes view and invokes toolbar actions', () => { const c = view(); fireEvent.click(screen.getByText('Simple')); expect(c.onViewMode).toHaveBeenCalledWith('simple'); fireEvent.click(screen.getByText('Detail')); expect(c.onViewMode).toHaveBeenCalledWith('detail'); fireEvent.click(screen.getByText('Unlock Editing')); expect(c.onUnlock).toHaveBeenCalled(); fireEvent.click(screen.getByText('Refresh')); expect(c.onRefresh).toHaveBeenCalled(); fireEvent.click(screen.getByText('Generate Missing Steps')); expect(c.onGenerate).toHaveBeenCalled(); });
  it('saves and locks editing', () => { const c = view({ isEditing: true }); fireEvent.click(screen.getByText('Save & Lock')); expect(c.onSaveAndLock).toHaveBeenCalled(); });
  it('shows saving and generating states', () => { const { rerender } = render(<BookingStepsToolbar viewMode="detail" isEditing saving="save-all" message="" {...cb()} />); expect(screen.getByText('Saving...')).toBeDisabled(); rerender(<BookingStepsToolbar viewMode="detail" isEditing={false} saving="generate" message="" {...cb()} />); expect(screen.getByText('Generating...')).toBeDisabled(); });
  it('renders simple description and message tones', () => { const { rerender } = render(<BookingStepsToolbar viewMode="simple" isEditing={false} saving="" message="Done" {...cb()} />); expect(screen.getByText(/Simple view/)).toBeInTheDocument(); expect(screen.getByText('Done')).toHaveClass('text-blue-800'); rerender(<BookingStepsToolbar viewMode="simple" isEditing={false} saving="" message="Unable to load" {...cb()} />); expect(screen.getByText('Unable to load')).toHaveClass('text-red-700'); });
});
