import React, { useMemo, useState } from 'react';
import BookingPaymentManagement from './BookingPaymentManagement';
import ClientBookingWorkflowTab from './ClientBookingWorkflowTab';
export const formatBookingDate = (date?: string | Date) => { if (!date) return 'N/A'; const value = new Date(date); if (Number.isNaN(value.getTime())) return 'N/A'; return value.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC' }); };
export const formatHistoryDateTime = (date?: string | Date) => { if (!date) return 'N/A'; const value = new Date(date); if (Number.isNaN(value.getTime())) return 'N/A'; return value.toLocaleString('en-US', { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }); };
export const retreatTown = (retreat: any) => String(retreat?.location_town || retreat?.locationTown || retreat?.generalTown || retreat?.general_town || retreat?.house?.generalTown || retreat?.house?.general_town || retreat?.house?.city || retreat?.houseId?.generalTown || retreat?.houseId?.general_town || retreat?.houseId?.city || retreat?.location || '').trim();

type Props = { bookingId: string; booking: any; client: any; retreat: any; clientName: string; bookingTypeCode: string; retreatCode: string; retreatAddress: string; onEditClient: () => void; onBookingRefresh: () => void; };
const Accordion: React.FC<{ title: string; open: boolean; onToggle: () => void; className?: string; children: React.ReactNode }> = ({ title, open, onToggle, className = '', children }) => <div className={`booking-detail-accordion ${className}`}><button type="button" className="booking-detail-accordion-trigger" onClick={onToggle} aria-expanded={open}><span>{title}</span><span>{open ? 'Hide' : 'Show'}</span></button>{open && <div className="booking-detail-accordion-body">{children}</div>}</div>;

const BookingOverviewPanel: React.FC<Props> = ({ bookingId, booking, client, retreat, clientName, bookingTypeCode, retreatCode, retreatAddress, onEditClient, onBookingRefresh }) => {
  const [stepsOpen, setStepsOpen] = useState(false); const [retreatOpen, setRetreatOpen] = useState(false); const [datesOpen, setDatesOpen] = useState(false);
  const history = useMemo(() => [...(booking?.bookingConfirmationHistory || [])].sort((a: any, b: any) => (a.iteration || 0) - (b.iteration || 0)), [booking]);
  const latest = history[history.length - 1];
  return <div className="booking-overview-layout"><main className="booking-overview-main">
    <section className="booking-overview-payments"><BookingPaymentManagement bookingId={bookingId} bookingNumber={booking.bookingNumber} clientName={clientName} bookingHash={booking.bookingHash} clientId={typeof client === 'object' ? client?._id : client} retreatId={typeof retreat === 'object' ? retreat?._id : retreat} totalAmount={booking.totalAmount || 0} currency={booking.currency || 'EUR'} onPaymentUpdate={onBookingRefresh} /></section>
    <Accordion title="Requirements next up" open={stepsOpen} onToggle={() => setStepsOpen(v => !v)} className="booking-steps-accordion"><ClientBookingWorkflowTab bookings={[booking]} hideBookingSelector /></Accordion>
    <Accordion title="Retreat information" open={retreatOpen} onToggle={() => setRetreatOpen(v => !v)} className="retreat-info-accordion"><div className="info-grid"><div className="info-item"><label>Retreat:</label><span>{retreat?.name || retreatCode}</span></div><div className="info-item"><label>Location:</label><span>{retreatAddress || retreatTown(retreat) || 'N/A'}</span></div><div className="info-item"><label>Type:</label><span>{retreat?.type ? retreat.type.charAt(0).toUpperCase() + retreat.type.slice(1) : 'N/A'}</span></div><div className="info-item"><label>Start:</label><span>{formatBookingDate(retreat?.startDate || retreat?.dates?.startDate)}</span></div><div className="info-item"><label>End:</label><span>{formatBookingDate(retreat?.endDate || retreat?.dates?.endDate)}</span></div></div></Accordion>
    <Accordion title="Booking dates" open={datesOpen} onToggle={() => setDatesOpen(v => !v)}><div className="info-grid"><div className="info-item"><label>Booked:</label><span>{formatBookingDate(booking.registrationDate || booking.createdAt)}</span></div><div className="info-item"><label>Check-in:</label><span>{formatBookingDate(booking.checkInDate)}</span></div><div className="info-item"><label>Check-out:</label><span>{formatBookingDate(booking.checkOutDate)}</span></div></div></Accordion>
  </main><aside className="booking-overview-aside"><section className="booking-overview-fact"><div className="booking-overview-fact-heading"><h3>Client</h3><button type="button" onClick={onEditClient}>Edit</button></div><strong>{clientName}</strong><span className="booking-overview-fact-label">Email</span><span>{client?.email || 'N/A'}</span><span className="booking-overview-fact-label">Phone</span><span>{client?.phone || 'N/A'}</span><span className="booking-overview-fact-label">Country</span><span>{client?.country || 'N/A'}</span></section>
    <section className="booking-overview-fact"><h3>Confirmation</h3>{!history.length ? <span>Not sent</span> : <><span>Sent {formatHistoryDateTime(latest?.sentAt || latest?.createdAt)}</span><span>{history.length} iteration{history.length === 1 ? '' : 's'}</span><details><summary>Show iterations</summary><div className="booking-confirm-history-list">{history.map((entry: any) => <div key={entry._id || `${entry.iteration}-${entry.sentAt}`} className="booking-confirm-history-entry"><strong>Iteration {entry.iteration}</strong><span>{formatHistoryDateTime(entry.sentAt || entry.createdAt)}</span></div>)}</div></details></>}</section>
    <section className="booking-overview-fact"><h3>Dates</h3><span>Retreat {formatBookingDate(retreat?.startDate || retreat?.dates?.startDate)} – {formatBookingDate(retreat?.endDate || retreat?.dates?.endDate)}</span><span>Booked {formatBookingDate(booking.registrationDate || booking.createdAt)}</span></section>
  </aside></div>;
};
export default BookingOverviewPanel;
