import React from 'react';
import { ListPlus, Lock, Maximize2, Minimize2, RefreshCw, Unlock } from 'lucide-react';

type Props = { viewMode: 'detail' | 'simple'; isEditing: boolean; isFullScreen: boolean; saving: string; message: string; showRequirementsOnly?: boolean; onShowRequirementsOnly?: (value: boolean) => void; onViewMode: (mode: 'detail' | 'simple') => void; onUnlock: () => void; onSaveAndLock: () => void; onFullScreen: () => void; onRefresh: () => void; onGenerate: () => void };

const BookingStepsToolbar: React.FC<Props> = ({ viewMode, isEditing, isFullScreen, saving, message, showRequirementsOnly = false, onShowRequirementsOnly = () => undefined, onViewMode, onUnlock, onSaveAndLock, onFullScreen, onRefresh, onGenerate }) => <>
  <div className="flex flex-col gap-3 rounded-lg border border-gray-200 bg-white p-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-lg font-semibold text-gray-900">Retreat Readiness</h2><p className="text-sm text-gray-500">{viewMode === 'detail' ? isEditing ? 'Editing is unlocked. Changes stay unlocked until you explicitly lock readiness.' : 'Read-only mode prevents accidental changes. Unlock editing to update status, date, notes, or actions.' : 'Simple view shows only complete, pending, and problem status by color.'}</p></div><div className="flex flex-wrap gap-2">
    <div className="inline-flex rounded-md border border-gray-300 bg-white p-0.5"><button type="button" onClick={() => onViewMode('detail')} className={`rounded px-3 py-1.5 text-sm font-medium ${viewMode === 'detail' ? 'bg-gray-900 text-white' : 'text-gray-700 hover:bg-gray-50'}`}>Detail</button><button type="button" onClick={() => onViewMode('simple')} className={`rounded px-3 py-1.5 text-sm font-medium ${viewMode === 'simple' ? 'bg-gray-900 text-white' : 'text-gray-700 hover:bg-gray-50'}`}>Simple</button></div>
    <label className={`inline-flex cursor-pointer items-center gap-2 rounded-md border px-3 py-2 text-sm font-medium ${showRequirementsOnly ? 'border-blue-300 bg-blue-50 text-blue-800' : 'border-gray-300 bg-white text-gray-700 hover:bg-gray-50'}`}><input type="checkbox" className="h-4 w-4 accent-blue-600" checked={showRequirementsOnly} onChange={(event) => onShowRequirementsOnly(event.target.checked)} />Show requirements only</label>
    {viewMode === 'detail' && (isEditing ? <button type="button" onClick={onSaveAndLock} disabled={saving === 'save-all'} className="inline-flex items-center gap-2 rounded-md bg-gray-900 px-3 py-2 text-sm font-semibold text-white hover:bg-gray-800 disabled:opacity-50"><Lock className="h-4 w-4" />{saving === 'save-all' ? 'Saving...' : 'Save & Lock'}</button> : <button type="button" onClick={onUnlock} className="inline-flex items-center gap-2 rounded-md bg-gray-900 px-3 py-2 text-sm font-semibold text-white hover:bg-gray-800"><Unlock className="h-4 w-4" />Unlock Editing</button>)}
    <button type="button" onClick={onFullScreen} className="inline-flex items-center gap-2 rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-700 hover:bg-gray-50" aria-label={isFullScreen ? 'Exit full screen readiness view' : 'Open full screen readiness view'}>{isFullScreen ? <Minimize2 className="h-4 w-4" /> : <Maximize2 className="h-4 w-4" />}{isFullScreen ? 'Exit full view' : 'Full view'}</button>
    <button type="button" onClick={onRefresh} className="inline-flex items-center gap-2 rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-700 hover:bg-gray-50"><RefreshCw className="h-4 w-4" />Refresh</button><button type="button" onClick={onGenerate} disabled={saving === 'generate'} title="Create booking steps that are configured for this retreat but do not exist yet" className="inline-flex items-center justify-center gap-2 rounded-md bg-blue-600 px-3 py-2 text-sm font-semibold text-white hover:bg-blue-700 disabled:opacity-50"><ListPlus className={`h-4 w-4 ${saving === 'generate' ? 'animate-pulse' : ''}`} />{saving === 'generate' ? 'Generating...' : 'Generate Missing Steps'}</button>
  </div></div>
  {message && <div className={`rounded-md border px-4 py-2 text-sm ${message.startsWith('Unable') ? 'border-red-200 bg-red-50 text-red-700' : 'border-blue-200 bg-blue-50 text-blue-800'}`}>{message}</div>}
</>;
export default BookingStepsToolbar;
