import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { MedicalArtifact, MedicalReviewRequest } from '../types';
import BookingMedicalUpload from './BookingMedicalUpload';
import { groupMedicalArtifacts, latestArtifactReview, loadBookingMedicalOverview, medicalStageLabels, medicalStageOrder, requiredEntryRows, reviewedMedicalStatuses } from './bookingMedicalOverviewData';

export interface BookingMedicalOverviewPanelProps { bookingId: string; clientId?: string; retreatId?: string; refreshKey: number; onUploadComplete: () => void; bookingNumber?: number | string; }
export const medicalRoutePrefix = (pathname: string) => { const first = pathname.split('/').filter(Boolean)[0]; return ['admin', 'medical', 'staff', 'user'].includes(first) ? `/${first}` : ''; };
export const medicalOverviewError = (error: any) => error?.response?.data?.message || error?.message || 'Unable to load booking medical records.';
export const reviewDecisionText = (review?: MedicalReviewRequest) => review?.reviewDecision || review?.decision || (review?.status && reviewedMedicalStatuses.has(review.status) ? review.status : 'No decision');
export const reviewDecisionClass = (review?: MedicalReviewRequest) => { const value = String(reviewDecisionText(review)).toLowerCase(); if (value.includes('ok') || value.includes('approved') || value.includes('completed')) return 'medical-decision-ok'; if (value.includes('caution') || value.includes('need')) return 'medical-decision-caution'; if (value.includes('not') || value.includes('declined') || value.includes('reject')) return 'medical-decision-declined'; return 'medical-decision-pending'; };
export const shortMedicalDate = (value?: Date | string) => { if (!value) return 'N/A'; const date = new Date(value); return Number.isNaN(date.getTime()) ? 'N/A' : date.toLocaleString('en-US', { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }); };
export const artifactTitle = (artifact: MedicalArtifact) => [artifact.title || artifact.documentType || artifact.artifactType || 'Medical record', artifact.ceremonyNumber ? `Ceremony #${artifact.ceremonyNumber}` : ''].filter(Boolean).join(' - ');

const ReviewLine: React.FC<{ review?: MedicalReviewRequest; artifactId?: string; prefix: string; navigate: (path: string) => void }> = ({ review, artifactId, prefix, navigate }) => <div className="booking-medical-review-line"><span className={`booking-medical-decision ${reviewDecisionClass(review)}`}>{reviewDecisionText(review)}</span>{review?._id ? <button className="booking-medical-link" type="button" onClick={() => navigate(`${prefix}/medical-review-requests/${review._id}`)}>Review #{review.display_id || review._id}</button> : <span className="booking-medical-missing-review"><span className="booking-medical-muted">No medical review linked yet</span>{artifactId && <button className="booking-medical-create-review" type="button" onClick={() => navigate(`${prefix}/medical-review-requests/new?artifactId=${artifactId}`)}>Create MRR</button>}</span>}{review?.reviewedAt && <span className="booking-medical-muted">{shortMedicalDate(review.reviewedAt)}</span>}{(review?.reviewNotes || review?.overallNotes || review?.medicalStaffNotes) && <span className="booking-medical-notes">{review.reviewNotes || review.overallNotes || review.medicalStaffNotes}</span>}</div>;

const BookingMedicalOverviewPanel: React.FC<BookingMedicalOverviewPanelProps> = ({ bookingId, clientId, retreatId, refreshKey, onUploadComplete, bookingNumber }) => {
  const navigate = useNavigate(); const location = useLocation(); const prefix = useMemo(() => medicalRoutePrefix(location.pathname), [location.pathname]);
  const [artifacts, setArtifacts] = useState<MedicalArtifact[]>([]); const [reviews, setReviews] = useState<Record<string, MedicalReviewRequest[]>>({}); const [plan, setPlan] = useState<any[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [uploadRequest, setUploadRequest] = useState<{ stage: NonNullable<MedicalArtifact['documentStage']>; key: number } | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const result = await loadBookingMedicalOverview(bookingId, clientId, retreatId); setArtifacts(result.artifacts); setReviews(result.reviewsByArtifact); setPlan(result.medicationPlan); } catch (cause) { setError(medicalOverviewError(cause)); } finally { setLoading(false); } }, [bookingId, clientId, retreatId]);
  useEffect(() => { load(); }, [load, refreshKey]);
  const stages = groupMedicalArtifacts(artifacts); const required = requiredEntryRows(artifacts, reviews); const allClear = plan.find(item => item.metadata?.medicationStopPlanAllClear);
  return <div className="booking-medical-panel">
    <section className="detail-section"><div className="section-header"><h3 className="pdf-section-title">Important medical dates</h3><button className="edit-btn" type="button" onClick={() => navigate(`${prefix}/bookings/${bookingId}/medication-stop-plan`)}>Edit medication plan</button></div>
      {allClear ? <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-900"><strong>✓ All good — nothing to prepare</strong><p className="mt-1 text-sm">{allClear.description}</p></div> : plan.length ? <div className="space-y-2">{plan.map(item => { const due = item.dueDate ? new Date(item.dueDate) : null; const overdue = Boolean(due && due.getTime() < Date.now() && !['completed', 'approved'].includes(item.status)); return <div key={item._id} className={`grid gap-2 rounded-xl border p-4 md:grid-cols-[150px_1fr_auto] ${overdue ? 'is-overdue border-rose-200 bg-rose-50' : 'is-upcoming border-amber-200 bg-amber-50'}`}><strong className={overdue ? 'text-rose-700' : 'text-amber-800'}>{due ? due.toLocaleDateString() : 'Date not set'}</strong><div><strong>{item.title}</strong><p className="mt-1 text-sm text-slate-600">{item.description}</p>{item.metadata?.taperPlan && <small className="mt-1 block text-slate-500">{item.metadata.taperPlan}</small>}</div><span className="text-sm font-semibold capitalize text-slate-600">{String(item.status || 'pending').replace(/_/g, ' ')}</span></div>; })}</div> : <div className="rounded-xl border border-dashed border-slate-300 p-4 text-sm text-slate-600">No medication preparation decision has been recorded yet.</div>}
    </section>
    <section className="detail-section"><div className="section-header"><h3 className="pdf-section-title">Required Entry Medical Items</h3><div className="flex gap-2"><button className="edit-btn" type="button" onClick={() => navigate(`${prefix}/bookings/${bookingId}/medication-stop-plan`)}>Medication stop plan</button><button className="edit-btn" type="button" onClick={load} disabled={loading}>{loading ? 'Refreshing...' : 'Refresh'}</button></div></div>{error && <div className="alert alert-danger" role="alert">{error}</div>}
      <div className="booking-medical-required-grid">{required.map(({ documentType, artifact, review }) => <div className={`booking-medical-required-card ${artifact ? 'is-present' : 'is-missing'}`} key={documentType}><div><div className="booking-medical-required-title">Entry {documentType}</div><div className="booking-medical-muted">Lookup: entry document + booking #{bookingNumber || bookingId}</div></div>{artifact ? <><button className="booking-medical-link" type="button" onClick={() => navigate(`${prefix}/medical-artifacts/${artifact._id}`)}>Artifact #{artifact.display_id || artifact._id}</button><ReviewLine review={review} artifactId={artifact._id} prefix={prefix} navigate={navigate} /></> : <span className="booking-medical-decision medical-decision-declined">Missing</span>}</div>)}</div>
    </section>
    <section className="detail-section"><h3 className="pdf-section-title">Medical Records by Stage</h3><div className="booking-medical-stage-list">{medicalStageOrder.map(stage => { const records = stages[stage || 'other'] || []; return <details className="booking-medical-stage" key={stage} open={stage === 'entry'}><summary><span>{medicalStageLabels[stage]}</span><span className="flex items-center gap-3"><span>{records.length}</span>{clientId && retreatId && <button className="btn btn-sm btn-primary" type="button" onClick={event => { event.preventDefault(); event.stopPropagation(); setUploadRequest({ stage: stage || 'other', key: Date.now() }); }}>Upload</button>}</span></summary>{records.length ? <div className="booking-medical-record-list">{records.map(artifact => <div className="booking-medical-record" key={artifact._id || `${artifact.documentType}-${artifact.receivedAt}`}><div className="booking-medical-record-main"><button className="booking-medical-link booking-medical-title-link" type="button" disabled={!artifact._id} onClick={() => artifact._id && navigate(`${prefix}/medical-artifacts/${artifact._id}`)}>#{artifact.display_id || artifact._id || 'New'} {artifactTitle(artifact)}</button><div className="booking-medical-meta"><span>{artifact.documentType}</span><span>{artifact.artifactType || 'artifact'}</span><span>{shortMedicalDate(artifact.receivedAt || artifact.createdAt)}</span><span>{(artifact.files || []).length} file(s)</span></div></div><ReviewLine review={latestArtifactReview(artifact, reviews)} artifactId={artifact._id} prefix={prefix} navigate={navigate} /></div>)}</div> : <div className="booking-medical-empty">No {medicalStageLabels[stage].toLowerCase()} records found.</div>}</details>; })}</div></section>
    {clientId && retreatId ? <BookingMedicalUpload bookingId={bookingId} bookingNumber={bookingNumber} clientId={clientId} retreatId={retreatId} uploadRequest={uploadRequest} onUploadComplete={() => { onUploadComplete(); load(); }} /> : <section className="detail-section"><p className="text-sm text-gray-500">Medical upload needs a linked client and retreat on this booking.</p></section>}
  </div>;
};
export default BookingMedicalOverviewPanel;
