import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { bookingFlowApi, ceremoniesApi, medicalArtifactsApi, medicalReviewRequestsApi } from '../services/api';
import { CeremonyParticipant, MedicalArtifact, MedicalReviewRequest } from '../types';
import { buildBookingFlowArtifactFilters } from './bookingFlowLookup';
import { mergeArtifacts, objectId } from './bookingRequirementRows';
import { compareMedicalArtifacts, indexMedicalReviews, latestArtifactReview, relevantMedicalArtifact } from './bookingMedicalOverviewData';
import { medicalRoutePrefix, reviewDecisionClass, shortMedicalDate } from './BookingMedicalOverviewPanel';

export const ceremonyError = (cause: any) => cause?.response?.data?.message || cause?.message || 'Unable to load ceremony information.';
export const clearanceClass = (value?: string) => value === 'approved' ? 'medical-decision-ok' : value === 'not_approved' ? 'medical-decision-declined' : value === 'conditional' ? 'medical-decision-caution' : 'medical-decision-pending';
export const ceremonyStageArtifacts = (artifacts: MedicalArtifact[], number: number | undefined, stage: MedicalArtifact['documentStage']) => artifacts.filter(item => item.documentStage === stage && (!number || item.ceremonyNumber === number));
export const loadBookingCeremonies = async (bookingId: string, clientId: string, retreatId?: string) => {
  const [participationResponse, itemsResponse] = await Promise.all([ceremoniesApi.getClientParticipations(clientId), bookingFlowApi.getItems({ bookingId })]); const filters = buildBookingFlowArtifactFilters(itemsResponse.data || []);
  const responses = await Promise.all([medicalArtifactsApi.getAll({ bookingId, ...filters }), medicalArtifactsApi.getAll({ bookingId }), retreatId ? medicalArtifactsApi.getAll({ clientId, retreatId, ...filters }) : Promise.resolve({ data: [] }), medicalArtifactsApi.getAll({ clientId, ...filters })]);
  const artifacts = mergeArtifacts(responses.map(response => response.data || [])).filter(item => relevantMedicalArtifact(item, bookingId, retreatId)).sort(compareMedicalArtifacts); const ids = artifacts.map(item => item._id).filter(Boolean) as string[]; const reviewResponse = ids.length ? await medicalReviewRequestsApi.getByArtifacts(ids) : { data: [] };
  const all = participationResponse.data || []; const participations = retreatId ? all.filter((item: any) => objectId(item.retreatId) === retreatId) : all;
  return { participations, artifacts, reviews: indexMedicalReviews(reviewResponse.data || []) };
};

const BookingCeremoniesPanel: React.FC<{ bookingId: string; clientId?: string; retreatId?: string; refreshKey: number }> = ({ bookingId, clientId, retreatId, refreshKey }) => {
  const navigate = useNavigate(); const location = useLocation(); const prefix = useMemo(() => medicalRoutePrefix(location.pathname), [location.pathname]); const [participations, setParticipations] = useState<CeremonyParticipant[]>([]); const [artifacts, setArtifacts] = useState<MedicalArtifact[]>([]); const [reviews, setReviews] = useState<Record<string, MedicalReviewRequest[]>>({}); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { if (!clientId) return; setLoading(true); setError(''); try { const result = await loadBookingCeremonies(bookingId, clientId, retreatId); setParticipations(result.participations); setArtifacts(result.artifacts); setReviews(result.reviews); } catch (cause) { setError(ceremonyError(cause)); } finally { setLoading(false); } }, [bookingId, clientId, retreatId]); useEffect(() => { load(); }, [load, refreshKey]);
  const chips = (number: number | undefined, stage: MedicalArtifact['documentStage']) => { const matches = ceremonyStageArtifacts(artifacts, number, stage); return matches.length ? <div>{matches.map(item => <button key={item._id || `${stage}-${item.documentType}-${item.receivedAt}`} type="button" className={reviewDecisionClass(latestArtifactReview(item, reviews))} onClick={() => item._id && navigate(`${prefix}/medical-artifacts/${item._id}`)}>{item.documentType} #{item.display_id || item._id}</button>)}</div> : <span>None</span>; };
  return <section className="detail-section"><div className="section-header"><h3>Ceremonies</h3><button type="button" onClick={load} disabled={loading}>{loading ? 'Refreshing...' : 'Refresh'}</button></div>{error && <div role="alert">{error}</div>}{participations.length ? participations.map((participation: any) => { const ceremony = participation.ceremonyId || {}; return <article key={participation._id || objectId(ceremony)}><header><strong>Ceremony #{ceremony.ceremonyNumber || participation.ceremonyNumber || 'N/A'}</strong><span>{shortMedicalDate(ceremony.date)}{ceremony.startTime ? ` - ${ceremony.startTime}` : ''}</span><span className={clearanceClass(participation.medicalClearance)}>{participation.medicalClearance || 'pending'}</span></header><div><label>Spoons</label><strong>{participation.spoonsTaken || 0}</strong><span>{participation.firstSpoonTime || 'No time recorded'}</span></div><div><label>Pre-ceremony labs</label>{chips(ceremony.ceremonyNumber, 'pre_ceremony')}</div><div><label>In-ceremony labs</label>{chips(ceremony.ceremonyNumber, 'in_ceremony')}</div><div><label>Post-ceremony labs</label>{chips(ceremony.ceremonyNumber, 'post_ceremony')}</div>{(participation.medicalClearanceNotes || participation.individualNotes || participation.postCeremonyNotes) && <p>{participation.medicalClearanceNotes || participation.individualNotes || participation.postCeremonyNotes}</p>}</article>; }) : <p>No ceremony participation records found for this booking retreat.</p>}</section>;
};
export default BookingCeremoniesPanel;
