import React from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { bookingFlowApi, ceremoniesApi, medicalArtifactsApi, medicalReviewRequestsApi } from '../services/api';
import BookingCeremoniesPanel, { ceremonyError, ceremonyStageArtifacts, clearanceClass, loadBookingCeremonies } from './BookingCeremoniesPanel';
const mockNavigate = jest.fn();
jest.mock('react-router-dom', () => ({ ...jest.requireActual('react-router-dom'), useNavigate: () => mockNavigate }));
jest.mock('../services/api', () => ({ bookingFlowApi: { getItems: jest.fn() }, ceremoniesApi: { getClientParticipations: jest.fn() }, medicalArtifactsApi: { getAll: jest.fn() }, medicalReviewRequestsApi: { getByArtifacts: jest.fn() } }));
const apiDefaults = () => { (bookingFlowApi.getItems as jest.Mock).mockResolvedValue({ data: [] }); (ceremoniesApi.getClientParticipations as jest.Mock).mockResolvedValue({ data: [] }); (medicalArtifactsApi.getAll as jest.Mock).mockResolvedValue({ data: [] }); (medicalReviewRequestsApi.getByArtifacts as jest.Mock).mockResolvedValue({ data: [] }); };
const view = (props: any = {}, path = '/admin/bookings/b') => render(<MemoryRouter initialEntries={[path]}><BookingCeremoniesPanel bookingId="b" clientId="c" refreshKey={0} {...props} /></MemoryRouter>);
describe('ceremony data helpers', () => {
  beforeEach(() => { jest.clearAllMocks(); apiDefaults(); });
  it('loads scoped participations, artifacts, and reviews', async () => { (ceremoniesApi.getClientParticipations as jest.Mock).mockResolvedValue({ data: [{ _id: 'p', retreatId: 'r' }, { _id: 'x', retreatId: 'x' }] }); (medicalArtifactsApi.getAll as jest.Mock).mockResolvedValue({ data: [{ _id: 'a', bookingId: 'b', documentStage: 'pre_ceremony' }, { _id: 'wrong', bookingId: 'x' }] }); (medicalReviewRequestsApi.getByArtifacts as jest.Mock).mockResolvedValue({ data: [{ _id: 'review', artifactIds: ['a'] }] }); const result = await loadBookingCeremonies('b', 'c', 'r'); expect(result.participations.map((item: any) => item._id)).toEqual(['p']); expect(result.artifacts.map(item => item._id)).toEqual(['a']); expect(result.reviews.a[0]._id).toBe('review'); });
  it('skips optional retreat and review calls', async () => { await loadBookingCeremonies('b', 'c'); expect(medicalArtifactsApi.getAll).toHaveBeenCalledTimes(3); expect(medicalReviewRequestsApi.getByArtifacts).not.toHaveBeenCalled(); });
  it('filters stages and maps states/errors', () => { const artifacts: any = [{ documentStage: 'pre_ceremony', ceremonyNumber: 1 }, { documentStage: 'pre_ceremony', ceremonyNumber: 2 }]; expect(ceremonyStageArtifacts(artifacts, 1, 'pre_ceremony')).toHaveLength(1); expect(ceremonyStageArtifacts(artifacts, undefined, 'pre_ceremony')).toHaveLength(2); expect(clearanceClass('approved')).toContain('ok'); expect(clearanceClass('not_approved')).toContain('declined'); expect(clearanceClass('conditional')).toContain('caution'); expect(clearanceClass()).toContain('pending'); expect(ceremonyError({ response: { data: { message: 'api' } } })).toBe('api'); expect(ceremonyError(new Error('local'))).toBe('local'); expect(ceremonyError({})).toContain('Unable'); });
});
describe('BookingCeremoniesPanel', () => {
  beforeEach(() => { jest.clearAllMocks(); apiDefaults(); });
  it('does not load without a client', async () => { render(<MemoryRouter><BookingCeremoniesPanel bookingId="b" refreshKey={0} /></MemoryRouter>); expect(await screen.findByText(/No ceremony participation/)).toBeInTheDocument(); expect(ceremoniesApi.getClientParticipations).not.toHaveBeenCalled(); });
  it('renders empty state and refreshes', async () => { view(); await waitFor(() => expect(ceremoniesApi.getClientParticipations).toHaveBeenCalled()); await waitFor(() => expect(screen.getByText('Refresh')).toBeInTheDocument()); fireEvent.click(screen.getByText('Refresh')); await waitFor(() => expect(ceremoniesApi.getClientParticipations).toHaveBeenCalledTimes(2)); });
  it('shows loading errors and recovers', async () => { (ceremoniesApi.getClientParticipations as jest.Mock).mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce({ data: [] }); view(); expect(await screen.findByRole('alert')).toHaveTextContent('offline'); fireEvent.click(screen.getByText('Refresh')); await waitFor(() => expect(screen.queryByRole('alert')).not.toBeInTheDocument()); });
  it('renders ceremony fields, notes, chips and navigation', async () => { (ceremoniesApi.getClientParticipations as jest.Mock).mockResolvedValue({ data: [{ _id: 'p', ceremonyId: { ceremonyNumber: 2, date: '2026-06-01', startTime: '20:00' }, medicalClearance: 'approved', spoonsTaken: 3, firstSpoonTime: '21:00', individualNotes: 'watch' }] }); (medicalArtifactsApi.getAll as jest.Mock).mockResolvedValue({ data: [{ _id: 'a', bookingId: 'b', ceremonyNumber: 2, documentStage: 'pre_ceremony', documentType: 'EKG', display_id: 7 }] }); view({}, '/medical/bookings/b'); expect(await screen.findByText('Ceremony #2')).toBeInTheDocument(); expect(screen.getByText('watch')).toBeInTheDocument(); expect(screen.getAllByText('None')).toHaveLength(2); fireEvent.click(screen.getByText('EKG #7')); expect(mockNavigate).toHaveBeenCalledWith('/medical/medical-artifacts/a'); });
  it('renders defaults when ceremony details are absent', async () => { (ceremoniesApi.getClientParticipations as jest.Mock).mockResolvedValue({ data: [{ _id: 'p' }] }); view(); expect(await screen.findByText('Ceremony #N/A')).toBeInTheDocument(); expect(screen.getByText('No time recorded')).toBeInTheDocument(); expect(screen.getByText('pending')).toBeInTheDocument(); });
});
