import React from 'react';
import { fireEvent, render, screen } from '@testing-library/react';
import BookingDetailShell, { bookingDetailTabs } from './BookingDetailShell';

const callbacks = () => ({ onBack: jest.fn(), onLanguageChange: jest.fn(), onEdit: jest.fn(), onPreview: jest.fn(), onQuickSend: jest.fn(), onReview: jest.fn(), onDownload: jest.fn(), onClosePreview: jest.fn(), onOpenRetreat: jest.fn(), onTabChange: jest.fn() });
const props = (overrides: any = {}) => ({ bookingNumber: 4, clientName: 'Ada', clientDisplayId: 7, retreatCode: 'RET', retreatId: 'r', bookingTypeCode: 'F', language: 'en' as const, activeTab: 'overview' as const, requirementsStatus: null, generating: false, previewing: false, sending: false, preparing: false, previewUrl: '', previewFileName: '', ...callbacks(), ...overrides });

describe('BookingDetailShell', () => {
  it('renders summary and invokes every primary action', () => { const values = props(); render(<BookingDetailShell {...values} />); expect(screen.getByText('Booking #4')).toBeInTheDocument(); expect(screen.getByText('#7')).toBeInTheDocument(); fireEvent.click(screen.getByLabelText('Back to bookings')); fireEvent.click(screen.getByLabelText('Edit booking')); fireEvent.click(screen.getByLabelText('Preview PDF')); fireEvent.click(screen.getByLabelText('Send email with PDF attachment')); fireEvent.click(screen.getByLabelText('Review email with PDF attachment')); fireEvent.click(screen.getByLabelText('Download PDF')); fireEvent.click(screen.getByText('RET')); expect(values.onBack).toHaveBeenCalled(); expect(values.onEdit).toHaveBeenCalled(); expect(values.onPreview).toHaveBeenCalled(); expect(values.onQuickSend).toHaveBeenCalled(); expect(values.onReview).toHaveBeenCalled(); expect(values.onDownload).toHaveBeenCalled(); expect(values.onOpenRetreat).toHaveBeenCalled(); });
  it('changes language and tabs', () => { const values = props(); render(<BookingDetailShell {...values} />); fireEvent.change(screen.getByLabelText('Confirmation language'), { target: { value: 'cz' } }); fireEvent.click(screen.getByRole('tab', { name: 'Medical' })); expect(values.onLanguageChange).toHaveBeenCalledWith('cz'); expect(values.onTabChange).toHaveBeenCalledWith('medical'); expect(screen.getAllByRole('tab')).toHaveLength(bookingDetailTabs.length); });
  it('renders missing identifiers as fallbacks', () => { render(<BookingDetailShell {...props({ bookingNumber: '', clientDisplayId: '', retreatId: '' })} />); expect(screen.getByText('Booking #N/A')).toBeInTheDocument(); expect(screen.queryByText('Client ID')).not.toBeInTheDocument(); expect(screen.getByText('RET').tagName).toBe('STRONG'); });
  it('shows missing and complete requirement badges', () => { const { rerender } = render(<BookingDetailShell {...props({ requirementsStatus: { missing: 3, total: 5 } })} />); expect(screen.getByLabelText('3 missing requirements')).toBeInTheDocument(); rerender(<BookingDetailShell {...props({ requirementsStatus: { missing: 0, total: 5 } })} />); expect(screen.getByLabelText('All requirements complete')).toBeInTheDocument(); });
  it('renders and closes the PDF preview', () => { const values = props({ previewUrl: 'blob:test', previewFileName: 'file.pdf' }); render(<BookingDetailShell {...values} />); expect(screen.getByRole('dialog')).toBeInTheDocument(); expect(screen.getByTitle('file.pdf')).toHaveAttribute('src', 'blob:test'); expect(screen.getByRole('link', { name: 'Download' })).toHaveAttribute('download', 'file.pdf'); fireEvent.click(screen.getByLabelText('Close PDF preview')); expect(values.onClosePreview).toHaveBeenCalled(); });
  it('reflects all busy states and disables actions', () => { render(<BookingDetailShell {...props({ generating: true, previewing: true, sending: true, preparing: true })} />); expect(screen.getByLabelText('Download PDF')).toBeDisabled(); expect(screen.getByLabelText('Preview PDF')).toBeDisabled(); expect(screen.getByLabelText('Send email with PDF attachment')).toBeDisabled(); expect(screen.getByLabelText('Review email with PDF attachment')).toBeDisabled(); expect(screen.getByLabelText('Confirmation language')).toBeDisabled(); });
});
