import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { MedicalArtifact, MedicalReviewRequest } from '../types';
import BookingMedicalUpload from './BookingMedicalUpload';
import { groupMedicalArtifacts, latestArtifactReview, loadBookingMedicalOverview, medicalStageLabels, medicalStageOrder, requiredEntryRows, reviewedMedicalStatuses } from './bookingMedicalOverviewData';

export interface BookingMedicalOverviewPanelProps { bookingId: string; clientId?: string; retreatId?: string; refreshKey: number; onUploadComplete: () => void; bookingNumber?: number | string; }
export const medicalRoutePrefix = (pathname: string) => { const first = pathname.split('/').filter(Boolean)[0]; return ['admin', 'medical', 'staff', 'user'].includes(first) ? `/${first}` : ''; };
export const medicalOverviewError = (error: any) => error?.response?.data?.message || error?.message || 'Unable to load booking medical records.';
export const reviewDecisionText = (review?: MedicalReviewRequest) => review?.reviewDecision || review?.decision || (review?.status && reviewedMedicalStatuses.has(review.status) ? review.status : 'No decision');
export const reviewDecisionClass = (review?: MedicalReviewRequest) => { const value = String(reviewDecisionText(review)).toLowerCase(); if (value.includes('ok') || value.includes('approved') || value.includes('completed')) return 'medical-decision-ok'; if (value.includes('caution') || value.includes('need')) return 'medical-decision-caution'; if (value.includes('not') || value.includes('declined') || value.includes('reject')) return 'medical-decision-declined'; return 'medical-decision-pending'; };
export const shortMedicalDate = (value?: Date | string) => { if (!value) return 'N/A'; const date = new Date(value); return Number.isNaN(date.getTime()) ? 'N/A' : date.toLocaleString('en-US', { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }); };
export const artifactTitle = (artifact: MedicalArtifact) => [artifact.title || artifact.documentType || artifact.artifactType || 'Medical record', artifact.ceremonyNumber ? `Ceremony #${artifact.ceremonyNumber}` : ''].filter(Boolean).join(' - ');

const ReviewLine: React.FC<{ review?: MedicalReviewRequest; artifactId?: string; prefix: string; navigate: (path: string) => void }> = ({ review, artifactId, prefix, navigate }) => <div className="booking-medical-review-line"><span className={`booking-medical-decision ${reviewDecisionClass(review)}`}>{reviewDecisionText(review)}</span>{review?._id ? <button type="button" onClick={() => navigate(`${prefix}/medical-review-requests/${review._id}`)}>Review #{review.display_id || review._id}</button> : <span>No medical review linked yet {artifactId && <button type="button" onClick={() => navigate(`${prefix}/medical-review-requests/new?artifactId=${artifactId}`)}>Create MRR</button>}</span>}{review?.reviewedAt && <span>{shortMedicalDate(review.reviewedAt)}</span>}{(review?.reviewNotes || review?.overallNotes || review?.medicalStaffNotes) && <span>{review.reviewNotes || review.overallNotes || review.medicalStaffNotes}</span>}</div>;

const BookingMedicalOverviewPanel: React.FC<BookingMedicalOverviewPanelProps> = ({ bookingId, clientId, retreatId, refreshKey, onUploadComplete, bookingNumber }) => {
  const navigate = useNavigate(); const location = useLocation(); const prefix = useMemo(() => medicalRoutePrefix(location.pathname), [location.pathname]);
  const [artifacts, setArtifacts] = useState<MedicalArtifact[]>([]); const [reviews, setReviews] = useState<Record<string, MedicalReviewRequest[]>>({}); const [plan, setPlan] = useState<any[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [uploadRequest, setUploadRequest] = useState<{ stage: NonNullable<MedicalArtifact['documentStage']>; key: number } | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const result = await loadBookingMedicalOverview(bookingId, clientId, retreatId); setArtifacts(result.artifacts); setReviews(result.reviewsByArtifact); setPlan(result.medicationPlan); } catch (cause) { setError(medicalOverviewError(cause)); } finally { setLoading(false); } }, [bookingId, clientId, retreatId]);
  useEffect(() => { load(); }, [load, refreshKey]);
  const stages = groupMedicalArtifacts(artifacts); const required = requiredEntryRows(artifacts, reviews); const allClear = plan.find(item => item.metadata?.medicationStopPlanAllClear);
  return <div className="booking-medical-panel">
    <section className="detail-section"><div className="section-header"><h3>Important medical dates</h3><button type="button" onClick={() => navigate(`${prefix}/bookings/${bookingId}/medication-stop-plan`)}>Edit medication plan</button></div>
      {allClear ? <div><strong>✓ All good — nothing to prepare</strong><p>{allClear.description}</p></div> : plan.length ? plan.map(item => { const due = item.dueDate ? new Date(item.dueDate) : null; const overdue = Boolean(due && due.getTime() < Date.now() && !['completed', 'approved'].includes(item.status)); return <div key={item._id} className={overdue ? 'is-overdue' : 'is-upcoming'}><strong>{due ? due.toLocaleDateString() : 'Date not set'}</strong><div><strong>{item.title}</strong><p>{item.description}</p>{item.metadata?.taperPlan && <small>{item.metadata.taperPlan}</small>}</div><span>{String(item.status || 'pending').replace(/_/g, ' ')}</span></div>; }) : <div>No medication preparation decision has been recorded yet.</div>}
    </section>
    <section className="detail-section"><div className="section-header"><h3>Required Entry Medical Items</h3><button type="button" onClick={load} disabled={loading}>{loading ? 'Refreshing...' : 'Refresh'}</button></div>{error && <div role="alert">{error}</div>}
      {required.map(({ documentType, artifact, review }) => <div key={documentType}><strong>Entry {documentType}</strong><span>Lookup: entry document + booking #{bookingNumber || bookingId}</span>{artifact ? <><button type="button" onClick={() => navigate(`${prefix}/medical-artifacts/${artifact._id}`)}>Artifact #{artifact.display_id || artifact._id}</button><ReviewLine review={review} artifactId={artifact._id} prefix={prefix} navigate={navigate} /></> : <span>Missing</span>}</div>)}
    </section>
    <section className="detail-section"><h3>Medical Records by Stage</h3>{medicalStageOrder.map(stage => { const records = stages[stage || 'other'] || []; return <details key={stage} open={stage === 'entry'}><summary><span>{medicalStageLabels[stage]}</span><span>{records.length}{clientId && retreatId && <button type="button" onClick={event => { event.preventDefault(); event.stopPropagation(); setUploadRequest({ stage: stage || 'other', key: Date.now() }); }}>Upload</button>}</span></summary>{records.length ? records.map(artifact => <div key={artifact._id || `${artifact.documentType}-${artifact.receivedAt}`}><button type="button" disabled={!artifact._id} onClick={() => artifact._id && navigate(`${prefix}/medical-artifacts/${artifact._id}`)}>#{artifact.display_id || artifact._id || 'New'} {artifactTitle(artifact)}</button><span>{artifact.documentType} · {artifact.artifactType || 'artifact'} · {shortMedicalDate(artifact.receivedAt || artifact.createdAt)} · {(artifact.files || []).length} file(s)</span><ReviewLine review={latestArtifactReview(artifact, reviews)} artifactId={artifact._id} prefix={prefix} navigate={navigate} /></div>) : <div>No {medicalStageLabels[stage].toLowerCase()} records found.</div>}</details>; })}</section>
    {clientId && retreatId ? <BookingMedicalUpload bookingId={bookingId} bookingNumber={bookingNumber} clientId={clientId} retreatId={retreatId} uploadRequest={uploadRequest} onUploadComplete={() => { onUploadComplete(); load(); }} /> : <section><p>Medical upload needs a linked client and retreat on this booking.</p></section>}
  </div>;
};
export default BookingMedicalOverviewPanel;
