import React from 'react'; import { fireEvent, render, screen } from '@testing-library/react'; import BookingStepsActionFilter from './BookingStepsActionFilter';
const rows: any = [{ key: 'a', title: 'Contract' }, { key: 'b', title: 'Questionnaire' }];
const base = (p: any = {}) => ({ rows, visibleRows: rows, draft: ['a'], search: '', position: { top: 1, left: 2 }, onDraft: jest.fn(), onSearch: jest.fn(), onClose: jest.fn(), onApply: jest.fn(), ...p });
describe('BookingStepsActionFilter', () => {
  it('searches, toggles rows and closes', () => { const p = base(); render(<BookingStepsActionFilter {...p} />); fireEvent.change(screen.getByPlaceholderText('Search actions'), { target: { value: 'con' } }); expect(p.onSearch).toHaveBeenCalledWith('con'); fireEvent.click(screen.getByLabelText('Select Questionnaire')); expect(p.onDraft).toHaveBeenCalledWith(['a', 'b']); fireEvent.click(screen.getByLabelText('Close action filter')); expect(p.onClose).toHaveBeenCalled(); });
  it('selects and clears all', () => { const p = base(); const { rerender } = render(<BookingStepsActionFilter {...p} />); fireEvent.click(screen.getByLabelText('Select all actions')); expect(p.onDraft).toHaveBeenCalledWith(rows.map((r: any) => r.key)); rerender(<BookingStepsActionFilter {...base({ draft: ['a', 'b'], onDraft: p.onDraft })} />); fireEvent.click(screen.getByLabelText('Select all actions')); expect(p.onDraft).toHaveBeenLastCalledWith([]); });
  it('applies all as null and partial as keys', () => { const apply = jest.fn(); const { rerender } = render(<BookingStepsActionFilter {...base({ draft: ['a', 'b'], onApply: apply })} />); fireEvent.click(screen.getByText('Apply filter')); expect(apply).toHaveBeenCalledWith(null); rerender(<BookingStepsActionFilter {...base({ draft: ['a'], onApply: apply })} />); fireEvent.click(screen.getByText('Apply filter')); expect(apply).toHaveBeenLastCalledWith(['a']); });
  it('renders empty search and cancel', () => { const close = jest.fn(); render(<BookingStepsActionFilter {...base({ visibleRows: [], onClose: close })} />); expect(screen.getByText('No actions match your search.')).toBeInTheDocument(); fireEvent.click(screen.getByText('Cancel')); expect(close).toHaveBeenCalled(); });
});
