import { blobBase64, confirmationAction, confirmationLanguage, confirmationReason, fileSize, historyReason, sendFailureDetails, sentEmailReceipt } from './bookingConfirmationWorkflow';
describe('booking confirmation workflow helpers', () => {
  it.each([['CZ', 'cz'], ['cs', 'cz'], ['Polski', 'pl'], ['POLSKA', 'pl'], ['English', 'en'], ['', 'en']] as const)('maps %s language to %s', (input, expected) => expect(confirmationLanguage({ preferredLanguage: input })).toBe(expected));
  it('prefers the explicit language property', () => expect(confirmationLanguage({ language: 'PL', preferredLanguage: 'CZ' })).toBe('pl'));
  it('selects original/updated history rules', () => { expect(confirmationReason({})).toContain('Original'); expect(confirmationAction({})).toBe('created'); expect(confirmationReason({ bookingConfirmationHistory: [{}] })).toContain('Updated'); expect(confirmationAction({ bookingConfirmationHistory: [{}] })).toBe('updated'); });
  it('resolves and trims history reasons', () => { expect(historyReason('  Manual  ', 'current', {})).toBe('Manual'); expect(historyReason('', ' Current ', {})).toBe('Current'); expect(historyReason('', '', {})).toContain('Original'); });
  it('formats byte sizes', () => { expect(fileSize(0)).toBe('0 B'); expect(fileSize(NaN)).toBe('0 B'); expect(fileSize(12)).toBe('12 B'); expect(fileSize(2048)).toBe('2.0 KB'); expect(fileSize(1024 ** 4)).toBe('1024.0 GB'); });
  it('formats detailed and minimal receipts', () => { expect(sentEmailReceipt({})).toBe('Email queued.\nCC: none'); const result = sentEmailReceipt({ status: 'sent', display_id: 2, gmailMessageId: 'g', cc: ['a'], attachments: [{}], errorMessage: 'late' }); expect(result).toContain('Log #2'); expect(result).toContain('CC: a'); expect(result).toContain('Attachments: 1'); expect(result).toContain('Error: late'); });
  it('formats API and local send failures with diagnostics', () => { const api = sendFailureDetails({ response: { status: 413, data: { message: 'large', limitBytes: 2048, receivedBytes: 4096 } } }, 1024, 2048); expect(api).toContain('large'); expect(api).toContain('Status: 413'); expect(api).toContain('PDF attachment size: 1.0 KB'); expect(api).toContain('API limit: 2.0 KB'); expect(sendFailureDetails(new Error('offline'))).toBe('offline'); expect(sendFailureDetails({})).toContain('Unable'); });
  it('encodes blobs as base64', async () => { await expect(blobBase64(new Blob(['hello'], { type: 'text/plain' }))).resolves.toBe('aGVsbG8='); });
  it('rejects when FileReader fails', async () => { const original = global.FileReader; class BrokenReader { onloadend: any; onerror: any; result = null; readAsDataURL() { this.onerror(new Error('broken')); } } (global as any).FileReader = BrokenReader; await expect(blobBase64(new Blob(['x']))).rejects.toThrow('broken'); global.FileReader = original; });
});
