import React from 'react';
import { X } from 'lucide-react';
import { User } from '../services/usersApi';
import { BookingFlowAction, BookingFlowItem, MedicalArtifact, MedicalReviewRequest } from '../types';
import { ArtifactLinkConfig, ReviewStepConfig } from './bookingStepMedicalLinks';
import { getBookingStepClientName, getBookingStepNumber } from './bookingStepIdentity';
import { BookingStepMatrixRow } from './bookingStepRows';
import { formatStepDateTime } from './bookingStepPresentation';

export type BookingStepReviewRequestModalState = { item: BookingFlowItem; booking: any; artifactId: string; requestType: NonNullable<MedicalReviewRequest['requestType']>; label: string; advisorId: string };
export type BookingStepArtifactLinkModalState = { item: BookingFlowItem; booking: any; row: BookingStepMatrixRow; config: ArtifactLinkConfig; candidates: MedicalArtifact[]; selectedArtifactId: string };
export type BookingStepReviewLinkModalState = { item: BookingFlowItem; booking: any; row: BookingStepMatrixRow; config?: ReviewStepConfig; action?: BookingFlowAction; candidates: MedicalReviewRequest[]; selectedRequestId: string };

const CloseButton = ({ onClose, label }: { onClose: () => void; label: string }) => <button type="button" onClick={onClose} className="rounded-md p-1 text-gray-500 hover:bg-gray-100 hover:text-gray-800" aria-label={label}><X className="h-5 w-5" /></button>;

export const BookingStepReviewLinkModal = ({ state, saving, onChange, onClose, onLink }: { state: BookingStepReviewLinkModalState; saving: string; onChange: (state: BookingStepReviewLinkModalState) => void; onClose: () => void; onLink: () => void }) => <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4"><div className="w-full max-w-3xl rounded-lg bg-white p-5 shadow-xl">
  <div className="mb-4 flex items-start justify-between gap-4"><div><h3 className="text-lg font-semibold text-gray-900">Link existing medical review request</h3><p className="mt-1 text-sm text-gray-600">{state.row.title} for {getBookingStepClientName(state.booking)} · Booking #{getBookingStepNumber(state.booking)}</p><p className="mt-1 text-xs text-gray-500">Select an existing request, then link it to this booking step.</p></div><CloseButton onClose={onClose} label="Close review request link" /></div>
  <div className="max-h-[60vh] overflow-auto rounded-md border border-gray-200"><table className="min-w-full divide-y divide-gray-200 text-sm"><thead className="bg-gray-50"><tr>{['Select', 'Request', 'Details', 'Action'].map(label => <th key={label} className="px-3 py-2 text-left font-medium text-gray-600">{label}</th>)}</tr></thead><tbody className="divide-y divide-gray-100 bg-white">{state.candidates.map(request => <tr key={request._id} className={state.selectedRequestId === request._id ? 'bg-indigo-50' : ''}><td className="px-3 py-2 align-top"><input aria-label={`Select MRR ${request.display_id || request._id?.slice(-6)}`} type="radio" name="review-request-link-selection" checked={state.selectedRequestId === request._id} onChange={() => onChange({ ...state, selectedRequestId: request._id || '' })} /></td><td className="px-3 py-2 align-top font-medium text-gray-900">MRR #{request.display_id || request._id?.slice(-6)} {request.requestType ? `· ${request.requestType}` : ''}</td><td className="px-3 py-2 align-top text-gray-600"><div>{request.status?.replace(/_/g, ' ') || 'pending'}{request.reviewDecision ? ` · ${request.reviewDecision}` : ''}</div><div>{request.assignedToEmail || request.assignedTo || 'Unassigned'}</div><div>{formatStepDateTime(request.requestedAt || request.createdAt)}</div></td><td className="px-3 py-2 align-top"><button type="button" disabled={saving === `link-mrr:${state.item._id}` || state.selectedRequestId !== request._id} onClick={onLink} className="inline-flex items-center gap-2 rounded-md bg-indigo-600 px-3 py-2 text-sm font-medium text-white hover:bg-indigo-700 disabled:opacity-50">{saving === `link-mrr:${state.item._id}` ? 'Linking...' : 'Link to step'}</button></td></tr>)}</tbody></table></div>
</div></div>;

export const BookingStepArtifactLinkModal = ({ state, saving, onChange, onClose, onLink }: { state: BookingStepArtifactLinkModalState; saving: string; onChange: (state: BookingStepArtifactLinkModalState) => void; onClose: () => void; onLink: () => void }) => <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4"><div className="w-full max-w-2xl rounded-lg bg-white p-5 shadow-xl">
  <div className="mb-4 flex items-start justify-between gap-4"><div><h3 className="text-lg font-semibold text-gray-900">Link existing artifact</h3><p className="mt-1 text-sm text-gray-600">Select an existing {state.config.label.toLowerCase()} artifact for {state.row.title} on booking #{getBookingStepNumber(state.booking)}.</p></div><CloseButton onClose={onClose} label="Close artifact link" /></div>
  <div className="max-h-[60vh] overflow-auto rounded-md border border-gray-200"><table className="min-w-full divide-y divide-gray-200 text-sm"><thead className="bg-gray-50"><tr>{['Select', 'Artifact', 'Details', 'Action'].map(label => <th key={label} className="px-3 py-2 text-left font-medium text-gray-600">{label}</th>)}</tr></thead><tbody className="divide-y divide-gray-100 bg-white">{state.candidates.map(artifact => <tr key={artifact._id} className={state.selectedArtifactId === artifact._id ? 'bg-amber-50' : ''}><td className="px-3 py-2 align-top"><input aria-label={`Select artifact ${artifact.display_id || artifact._id?.slice(-6)}`} type="radio" name="artifact-link-selection" checked={state.selectedArtifactId === artifact._id} onChange={() => onChange({ ...state, selectedArtifactId: artifact._id || '' })} /></td><td className="px-3 py-2 align-top font-medium text-gray-900">#{artifact.display_id || artifact._id?.slice(-6)} {artifact.title || artifact.documentType || artifact.artifactType}</td><td className="px-3 py-2 align-top text-gray-600"><div>{artifact.documentStage || 'entry'} · {artifact.documentType || artifact.artifactType}</div><div>{formatStepDateTime(artifact.receivedAt || artifact.createdAt)}</div><div>{(artifact.files || []).length} file(s)</div></td><td className="px-3 py-2 align-top"><button type="button" disabled={saving === `link:${state.item._id}` || state.selectedArtifactId !== artifact._id} onClick={onLink} className="inline-flex items-center gap-2 rounded-md bg-amber-600 px-3 py-2 text-sm font-medium text-white hover:bg-amber-700 disabled:opacity-50">{saving === `link:${state.item._id}` ? 'Linking...' : 'Link to step'}</button></td></tr>)}</tbody></table></div>
</div></div>;

export const BookingStepReviewRequestModal = ({ state, advisors, saving, onChange, onClose, onCreate }: { state: BookingStepReviewRequestModalState; advisors: User[]; saving: string; onChange: (state: BookingStepReviewRequestModalState) => void; onClose: () => void; onCreate: () => void }) => <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4"><div className="w-full max-w-lg rounded-lg bg-white p-5 shadow-xl">
  <div className="mb-4 flex items-start justify-between gap-4"><div><h3 className="text-lg font-semibold text-gray-900">Create Medical Review Request</h3><p className="mt-1 text-sm text-gray-600">{state.label} for {getBookingStepClientName(state.booking)} · Booking #{getBookingStepNumber(state.booking)}</p></div><CloseButton onClose={onClose} label="Close medical review request" /></div>
  <div className="space-y-4"><div className="rounded-md border border-gray-200 bg-gray-50 p-3 text-sm text-gray-700"><div><span className="font-medium text-gray-900">Artifact:</span> {state.artifactId}</div><div><span className="font-medium text-gray-900">Request type:</span> {state.requestType.replace(/_/g, ' ')}</div></div><div><label htmlFor="medical-advisor" className="mb-2 block text-sm font-medium text-gray-700">Medical Advisor <span className="text-red-600">*</span></label><select id="medical-advisor" value={state.advisorId} onChange={event => onChange({ ...state, advisorId: event.target.value })} className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"><option value="">Select medical advisor</option>{advisors.map(advisor => <option key={advisor._id} value={advisor._id}>{[advisor.firstName, advisor.lastName].filter(Boolean).join(' ') || advisor.email} ({advisor.email})</option>)}</select>{advisors.length === 0 && <p className="mt-1 text-xs text-red-600">No active medical advisors are available.</p>}</div></div>
  <div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} disabled={saving === `mrr:${state.item._id}`} className="rounded-md border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50">Cancel</button><button type="button" onClick={onCreate} disabled={!state.advisorId || saving === `mrr:${state.item._id}`} className="rounded-md bg-indigo-600 px-3 py-2 text-sm font-medium text-white hover:bg-indigo-700 disabled:opacity-50">{saving === `mrr:${state.item._id}` ? 'Creating...' : 'Create MRR'}</button></div>
</div></div>;
