import React from 'react';
import { fireEvent, render, screen } from '@testing-library/react';
import { BookingStepAutomationModal, BookingStepReminderModal } from './BookingStepCommunicationModals';

const reminder: any = { item: { _id: 'i', title: 'Contract' }, to: 'a@test.com', subject: 'Subject', bodyText: 'Body', dueDate: '', uploadUrl: '/step', reminderCount: 1, lastReminderAt: '2026-08-12', duplicateBlocked: true, duplicateWarning: true, suggestedFollowUpDate: '2026-08-15', history: [{ _id: 'h', performedAt: '2026-08-01', performedByEmail: 'admin@test.com' }] };
describe('BookingStepCommunicationModals', () => {
  it('renders, edits, sends and closes reminder preview', () => { const change = jest.fn(); const close = jest.fn(); const send = jest.fn(); render(<BookingStepReminderModal state={reminder} saving="" onChange={change} onClose={close} onSend={send} />); expect(screen.getByText('Reminder: Contract')).toBeInTheDocument(); expect(screen.getByText(/1 previous reminder/)).toBeInTheDocument(); expect(screen.getByText(/admin@test.com/)).toBeInTheDocument(); fireEvent.change(screen.getByLabelText('Subject'), { target: { value: 'Changed' } }); expect(change).toHaveBeenCalledWith(expect.objectContaining({ subject: 'Changed' })); fireEvent.change(screen.getByLabelText('Follow up'), { target: { value: '2026-08-20' } }); expect(change).toHaveBeenCalledWith(expect.objectContaining({ suggestedFollowUpDate: '2026-08-20' })); fireEvent.click(screen.getByText('Send reminder')); expect(send).toHaveBeenCalled(); fireEvent.click(screen.getByLabelText('Close reminder preview')); expect(close).toHaveBeenCalled(); });
  it('disables incomplete and sending reminders', () => { const { rerender } = render(<BookingStepReminderModal state={{ ...reminder, subject: '' }} saving="" onChange={jest.fn()} onClose={jest.fn()} onSend={jest.fn()} />); expect(screen.getByText('Send reminder')).toBeDisabled(); rerender(<BookingStepReminderModal state={reminder} saving="reminder-send:i" onChange={jest.fn()} onClose={jest.fn()} onSend={jest.fn()} />); expect(screen.getByText('Sending...')).toBeDisabled(); });
  it('renders paused automation, schedules and actions', () => { const close = jest.fn(); const toggle = jest.fn(); render(<BookingStepAutomationModal state={{ item: { _id: 'i', title: 'Contract' }, paused: true, pauseReason: 'Asked', schedules: [{ _id: 's', ruleKey: 'send_email', scheduledFor: '2026-08-20', status: 'pending', actionType: 'send_email' }] } as any} saving="" onClose={close} onToggle={toggle} />); expect(screen.getByText(/Automation paused/).parentElement).toHaveTextContent('Asked'); expect(screen.getByText('send email')).toBeInTheDocument(); fireEvent.click(screen.getByText('Resume automation')); expect(toggle).toHaveBeenCalled(); fireEvent.click(screen.getByLabelText('Close automation')); expect(close).toHaveBeenCalled(); });
  it('renders empty active automation', () => { render(<BookingStepAutomationModal state={{ item: { _id: 'i', title: 'Contract' }, paused: false, schedules: [] } as any} saving="automation-toggle:i" onClose={jest.fn()} onToggle={jest.fn()} />); expect(screen.getByText('No automation is scheduled for this step.')).toBeInTheDocument(); expect(screen.getByText('Pause for this client')).toBeDisabled(); });
});
