import React, { useEffect, useMemo, useState } from 'react';
import { clientFoodFormsApi, ClientFoodForm } from '../services/clientFoodFormsApi';
const label = (key: string) => key.replace(/([A-Z])/g, ' $1').replace(/^./, (value) => value.toUpperCase());
const ClientFoodFormsPage: React.FC = () => {
  const [rows, setRows] = useState<ClientFoodForm[]>([]); const [selected, setSelected] = useState<ClientFoodForm | null>(null); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { setRows((await clientFoodFormsApi.getAll()).data); } finally { setLoading(false); } }; useEffect(() => { load(); }, []);
  const visible = useMemo(() => rows.filter((row) => `${row.display_id} ${row.email} ${row.signature_name} ${row.client_id}`.toLowerCase().includes(search.toLowerCase())), [rows, search]);
  const setStatus = async (row: ClientFoodForm, status: ClientFoodForm['status']) => { const updated = (await clientFoodFormsApi.update(row._id, { status })).data; setRows((all) => all.map((item) => item._id === updated._id ? updated : item)); setSelected(updated); };
  const remove = async (row: ClientFoodForm) => { if (!window.confirm(`Delete food form #${row.display_id}?`)) return; await clientFoodFormsApi.delete(row._id); setSelected(null); await load(); };
  return <div className="p-6"><div className="mb-6"><h1 className="text-2xl font-bold text-gray-900">Client Food Forms</h1><p className="mt-1 text-gray-600">Submitted dietary preferences, allergies, and kitchen requirements.</p></div><input className="mb-4 w-full max-w-md rounded-lg border border-gray-300 px-4 py-2" placeholder="Search name, email, client, or reference" value={search} onChange={(event) => setSearch(event.target.value)} />{loading ? <p>Loading food forms…</p> : <div className="overflow-hidden rounded-xl border border-gray-200 bg-white"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr>{['Reference', 'Client', 'Submitted', 'Language', 'Status', 'Actions'].map((title) => <th key={title} className="px-4 py-3 text-left text-xs font-semibold uppercase text-gray-500">{title}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{visible.map((row) => <tr key={row._id}><td className="px-4 py-3 font-semibold">#{row.display_id}</td><td className="px-4 py-3"><div>{row.signature_name}</div><div className="text-xs text-gray-500">{row.email}</div></td><td className="px-4 py-3">{row.submitted_at ? new Date(row.submitted_at).toLocaleString() : '—'}</td><td className="px-4 py-3 uppercase">{row.language}</td><td className="px-4 py-3"><select value={row.status} onChange={(event) => setStatus(row, event.target.value as ClientFoodForm['status'])} className="rounded border border-gray-300 px-2 py-1"><option value="submitted">Received</option><option value="reviewed">Reviewed</option><option value="draft">Draft</option></select></td><td className="px-4 py-3"><button className="mr-3 text-blue-700" onClick={() => setSelected(row)}>View</button><button className="text-red-700" onClick={() => remove(row)}>Delete</button></td></tr>)}</tbody></table>{!visible.length && <p className="p-6 text-gray-500">No food forms found.</p>}</div>}{selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" role="dialog" aria-modal="true"><section className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-xl bg-white p-6"><div className="mb-5 flex justify-between"><div><h2 className="text-xl font-bold">Food form #{selected.display_id}</h2><p className="text-sm text-gray-500">{selected.signature_name} · {selected.email}</p></div><button onClick={() => setSelected(null)}>Close</button></div><dl className="grid gap-4 sm:grid-cols-2">{Object.entries(selected.answers || {}).map(([key, value]) => <div key={key} className="rounded-lg bg-gray-50 p-3"><dt className="text-xs font-semibold uppercase text-gray-500">{label(key)}</dt><dd className="mt-1 whitespace-pre-wrap text-gray-900">{Array.isArray(value) ? value.join(', ') : String(value || '—')}</dd></div>)}</dl></section></div>}</div>;
};
export default ClientFoodFormsPage;
