import React, { useState, useEffect, useCallback } from 'react';
import { retreatExpensesApi, expenseTypesApi } from '../services/api';
import { RetreatExpense, ExpenseType, ExpenseSummary } from '../types';
import { FiPlus, FiEdit2, FiTrash2, FiRefreshCw, FiHome } from 'react-icons/fi';
import './ClientsGrid.css';

// Simple wrapper to fix TypeScript icon issues
const Icon: React.FC<{ icon: any; className?: string }> = ({ icon: IconComponent, className }) => {
  return <IconComponent className={className} />;
};

interface ExpensesTabProps {
  retreatId: string;
}

interface ExpenseFormData {
  expenseTypeId: string;
  amount: number;
  currency: 'EUR' | 'USD' | 'CZK' | 'PLN';
  description: string;
  vendor: string;
  expenseDate: string;
  status: 'pending' | 'approved' | 'paid' | 'rejected';
}

const ExpensesTab: React.FC<ExpensesTabProps> = ({ retreatId }) => {
  const [expenses, setExpenses] = useState<RetreatExpense[]>([]);
  const [expenseTypes, setExpenseTypes] = useState<ExpenseType[]>([]);
  const [summary, setSummary] = useState<ExpenseSummary | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [showAddForm, setShowAddForm] = useState(false);
  const [editingExpense, setEditingExpense] = useState<RetreatExpense | null>(null);
  const [formData, setFormData] = useState<ExpenseFormData>({
    expenseTypeId: '',
    amount: 0,
    currency: 'CZK',
    description: '',
    vendor: '',
    expenseDate: new Date().toISOString().split('T')[0],
    status: 'pending'
  });

  const getStatusColor = (status: string) => {
    const colors: Record<string, string> = {
      pending: 'bg-yellow-100 text-yellow-800',
      approved: 'bg-blue-100 text-blue-800',
      paid: 'bg-green-100 text-green-800',
      rejected: 'bg-red-100 text-red-800'
    };
    return colors[status] || 'bg-yellow-100 text-yellow-800';
  };

  const formatAmount = (amount: number, currency: string) => {
    return `${amount.toLocaleString()} ${currency}`;
  };

  const getCategoryIcon = (category: string) => {
    const categoryIcons: Record<string, string> = {
      house: '🏠',
      food: '🍽️',
      transportation: '🚗',
      misc: '🧾',
      supplies: '📦',
      other: '📦'
    };
    return categoryIcons[category] || '📦';
  };

  const getExpenseTypeName = (expense: RetreatExpense) => {
    const expenseType = expense.expenseTypeId;
    if (typeof expenseType === 'object' && expenseType.name) {
      return expenseType.name;
    }
    return '';
  };

  const getExpenseTypeCategory = (expense: RetreatExpense) => {
    const expenseType = expense.expenseTypeId;
    if (typeof expenseType === 'object' && expenseType.category) {
      return expenseType.category;
    }
    return '';
  };

  const formatDate = (date: string | Date) => {
    if (!date) return '';
    return new Date(date).toLocaleDateString();
  };

  const handleEditExpense = (expense: RetreatExpense) => {
    setEditingExpense(expense);
    setFormData({
      expenseTypeId: typeof expense.expenseTypeId === 'string' ? expense.expenseTypeId : expense.expenseTypeId._id || '',
      amount: expense.amount,
      currency: expense.currency,
      description: expense.description || '',
      vendor: expense.vendor || '',
      expenseDate: new Date(expense.expenseDate).toISOString().split('T')[0],
      status: expense.status
    });
    setShowAddForm(true);
  };

  const fetchData = useCallback(async () => {
    try {
      setIsLoading(true);
      const [expensesResponse, typesResponse, summaryResponse] = await Promise.all([
        retreatExpensesApi.getByRetreat(retreatId),
        expenseTypesApi.getAll(),
        retreatExpensesApi.getRetreatSummary(retreatId)
      ]);

      setExpenses(expensesResponse.data);
      setExpenseTypes(typesResponse.data.filter(type => type.isActive !== false));
      setSummary(summaryResponse.data);
    } catch (error) {
      console.error('Error fetching expenses data:', error);
    } finally {
      setIsLoading(false);
    }
  }, [retreatId]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const handleDeleteExpense = useCallback(async (expenseId: string) => {
    if (window.confirm('Are you sure you want to delete this expense?')) {
      try {
        await retreatExpensesApi.delete(expenseId);
        await fetchData();
      } catch (error) {
        console.error('Error deleting expense:', error);
        alert('Error deleting expense');
      }
    }
  }, [fetchData]);


  const handleFormSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const submitData = {
        ...formData,
        retreatId,
        expenseDate: new Date(formData.expenseDate),
        isAutoGenerated: false
      };

      if (editingExpense) {
        await retreatExpensesApi.update(editingExpense._id!, submitData);
      } else {
        await retreatExpensesApi.create(submitData);
      }

      setShowAddForm(false);
      setEditingExpense(null);
      setFormData({
        expenseTypeId: '',
        amount: 0,
        currency: 'CZK',
        description: '',
        vendor: '',
        expenseDate: new Date().toISOString().split('T')[0],
        status: 'pending'
      });
      await fetchData();
    } catch (error) {
      console.error('Error saving expense:', error);
      alert('Error saving expense');
    }
  };

  const handleAutoGenerateHouseCost = async () => {
    try {
      await retreatExpensesApi.autoGenerateHouseCost(retreatId);
      await fetchData();
    } catch (error) {
      console.error('Error auto-generating house cost:', error);
      alert('Error auto-generating house cost');
    }
  };

  const formatCurrency = (amount: number, currency: string) => {
    return `${amount.toLocaleString()} ${currency}`;
  };

  if (isLoading) {
    return (
      <div className="loading-container">
        <div className="loading-spinner">💰</div>
        <p>Loading expenses...</p>
      </div>
    );
  }

  return (
    <div className="expenses-tab">
      {/* Summary Cards */}
      {summary && (
        <div className="expenses-summary">
          <div className="summary-cards">
            <div className="summary-card">
              <div className="summary-number">{formatCurrency(summary.totalExpenses, 'CZK')}</div>
              <div className="summary-label">Total Expenses</div>
            </div>
            <div className="summary-card">
              <div className="summary-number">{formatCurrency(summary.totalExpensesUSD || 0, 'USD')}</div>
              <div className="summary-label">Total USD</div>
            </div>
            <div className="summary-card">
              <div className="summary-number">{summary.count}</div>
              <div className="summary-label">Total Items</div>
            </div>
            <div className="summary-card">
              <div className="summary-number">{Object.keys(summary.expensesByCategory).length}</div>
              <div className="summary-label">Categories</div>
            </div>
            <div className="summary-card">
              <div className="summary-number">{summary.expensesByStatus.pending || 0}</div>
              <div className="summary-label">Pending</div>
            </div>
          </div>

          {/* Category Breakdown */}
          <div className="category-breakdown">
            <h4>💼 By Category</h4>
            <div className="category-list">
              {Object.entries(summary.expensesByCategory).map(([category, amount]) => (
                <div key={category} className="category-item">
                  <span className="category-name">{category}</span>
                  <span className="category-amount">
                    {formatCurrency(amount, 'CZK')}
                    {summary.expensesByCategoryUSD?.[category] !== undefined && (
                      <span className="ml-2 text-gray-500">
                        {formatCurrency(summary.expensesByCategoryUSD[category], 'USD')}
                      </span>
                    )}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Actions */}
      <div className="flex gap-2 mb-6">
        <button
          onClick={() => setShowAddForm(true)}
          className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 flex items-center gap-2 disabled:opacity-50"
          disabled={showAddForm}
        >
          <Icon icon={FiPlus} className="w-4 h-4" />
          Add Expense
        </button>
        <button
          onClick={handleAutoGenerateHouseCost}
          className="bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 flex items-center gap-2"
        >
          <Icon icon={FiHome} className="w-4 h-4" />
          Auto-Generate House Cost
        </button>
        <button
          onClick={fetchData}
          className="bg-gray-600 text-white px-4 py-2 rounded-lg hover:bg-gray-700 flex items-center gap-2"
        >
          <Icon icon={FiRefreshCw} className="w-4 h-4" />
          Refresh
        </button>
      </div>

      {/* Add/Edit Form */}
      {showAddForm && (
        <div className="expense-form">
          <h3>{editingExpense ? 'Edit Expense' : 'Add New Expense'}</h3>
          <form onSubmit={handleFormSubmit}>
            <div className="form-grid">
              <div className="form-group">
                <label>Expense Type</label>
                <select
                  value={formData.expenseTypeId}
                  onChange={(e) => setFormData({...formData, expenseTypeId: e.target.value})}
                  required
                >
                  <option value="">Select expense type...</option>
                  {expenseTypes.map(type => (
                    <option key={type._id} value={type._id}>
                      {type.name} ({type.category})
                    </option>
                  ))}
                </select>
              </div>

              <div className="form-group">
                <label>Amount</label>
                <input
                  type="number"
                  value={formData.amount}
                  onChange={(e) => setFormData({...formData, amount: Number(e.target.value)})}
                  required
                />
              </div>

              <div className="form-group">
                <label>Currency</label>
                <select
                  value={formData.currency}
                  onChange={(e) => setFormData({...formData, currency: e.target.value as 'EUR' | 'USD' | 'CZK' | 'PLN'})}
                >
                  <option value="EUR">EUR (Euro)</option>
                  <option value="USD">USD (US Dollar)</option>
                  <option value="CZK">CZK (Czech Koruna)</option>
                  <option value="PLN">PLN (Polish Złoty)</option>
                </select>
              </div>

              <div className="form-group">
                <label>Status</label>
                <select
                  value={formData.status}
                  onChange={(e) => setFormData({...formData, status: e.target.value as any})}
                >
                  <option value="pending">Pending</option>
                  <option value="approved">Approved</option>
                  <option value="paid">Paid</option>
                  <option value="rejected">Rejected</option>
                </select>
              </div>

              <div className="form-group full-width">
                <label>Description</label>
                <input
                  type="text"
                  value={formData.description}
                  onChange={(e) => setFormData({...formData, description: e.target.value})}
                />
              </div>

              <div className="form-group">
                <label>Vendor</label>
                <input
                  type="text"
                  value={formData.vendor}
                  onChange={(e) => setFormData({...formData, vendor: e.target.value})}
                />
              </div>

              <div className="form-group">
                <label>Date</label>
                <input
                  type="date"
                  value={formData.expenseDate}
                  onChange={(e) => setFormData({...formData, expenseDate: e.target.value})}
                  required
                />
              </div>
            </div>

            <div className="form-actions">
              <button
                type="button"
                onClick={() => {
                  setShowAddForm(false);
                  setEditingExpense(null);
                }}
                className="cancel-btn"
              >
                Cancel
              </button>
              <button type="submit" className="save-btn">
                {editingExpense ? 'Update Expense' : 'Add Expense'}
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Expenses Table */}
      <div className="bg-white rounded-lg shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Expense Type
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Category
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Amount
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  USD Amount
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Description
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Vendor
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Date
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Status
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Type
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Actions
                </th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {expenses.map((expense) => (
                <tr key={expense._id} className="hover:bg-gray-50">
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                    {getExpenseTypeName(expense)}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                    {getExpenseTypeCategory(expense) && (
                      <span className="flex items-center">
                        <span className="mr-1">{getCategoryIcon(getExpenseTypeCategory(expense))}</span>
                        {getExpenseTypeCategory(expense)}
                      </span>
                    )}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                    {formatAmount(expense.amount, expense.currency)}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                    {formatCurrency(expense.usd_amount || 0, 'USD')}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 max-w-xs truncate">
                    {expense.description}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                    {expense.vendor}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                    {formatDate(expense.expenseDate)}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${getStatusColor(expense.status)}`}>
                      {expense.status}
                    </span>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {expense.isAutoGenerated ? 'Auto' : 'Manual'}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => handleEditExpense(expense)}
                        className="text-indigo-600 hover:text-indigo-900"
                        title="Edit"
                      >
                        <Icon icon={FiEdit2} className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => handleDeleteExpense(expense._id!)}
                        className="text-red-600 hover:text-red-900"
                        title="Delete"
                      >
                        <Icon icon={FiTrash2} className="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          {expenses.length === 0 && (
            <div className="text-center py-8 text-gray-500">
              No expenses found
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ExpensesTab;
