import React, { useState, useEffect, useCallback, useRef } from 'react';
import { AgGridReact } from 'ag-grid-react';
import { ColDef, GridApi, GridReadyEvent, ICellRendererParams, ModuleRegistry, AllCommunityModule } from 'ag-grid-community';
import { retreatExpensesApi, expenseTypesApi } from '../services/api';
import { RetreatExpense, ExpenseType, ExpenseSummary } from '../types';
import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-alpine.css';
import './ClientsGrid.css';

ModuleRegistry.registerModules([AllCommunityModule]);

interface ExpensesTabProps {
  retreatId: string;
}

interface ExpenseFormData {
  expenseTypeId: string;
  amount: number;
  currency: 'EUR' | 'USD' | 'CZK' | 'PLN';
  description: string;
  vendor: string;
  expenseDate: string;
  status: 'pending' | 'approved' | 'paid' | 'rejected';
}

const ExpensesTab: React.FC<ExpensesTabProps> = ({ retreatId }) => {
  const [expenses, setExpenses] = useState<RetreatExpense[]>([]);
  const [expenseTypes, setExpenseTypes] = useState<ExpenseType[]>([]);
  const [summary, setSummary] = useState<ExpenseSummary | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [showAddForm, setShowAddForm] = useState(false);
  const [editingExpense, setEditingExpense] = useState<RetreatExpense | null>(null);
  const [formData, setFormData] = useState<ExpenseFormData>({
    expenseTypeId: '',
    amount: 0,
    currency: 'CZK',
    description: '',
    vendor: '',
    expenseDate: new Date().toISOString().split('T')[0],
    status: 'pending'
  });
  const gridApiRef = useRef<GridApi | null>(null);

  const StatusCellRenderer = (params: ICellRendererParams) => {
    const status = params.value?.toLowerCase() || 'pending';
    const statusClass = `status-${status}`;
    return `<span class="status-badge ${statusClass}">${params.value || 'Pending'}</span>`;
  };

  const AmountCellRenderer = (params: ICellRendererParams) => {
    const amount = params.value || 0;
    const currency = params.data.currency || 'CZK';
    return `${amount.toLocaleString()} ${currency}`;
  };

  const CategoryCellRenderer = (params: ICellRendererParams) => {
    const expenseType = params.data.expenseTypeId;
    if (typeof expenseType === 'object' && expenseType.category) {
      const categoryIcons = {
        accommodation: '🏠',
        transport: '🚗',
        food: '🍽️',
        activities: '🎯',
        staff: '👥',
        utilities: '⚡',
        general: '📦'
      };
      const category = expenseType.category as keyof typeof categoryIcons;
      const categoryIcon = categoryIcons[category] || '📦';
      return `${categoryIcon} ${category}`;
    }
    return '';
  };

  const ActionsCellRenderer = (params: ICellRendererParams) => {
    return `
      <div class="cell-actions">
        <button class="edit-btn" data-action="edit" data-id="${params.data._id}">✏️</button>
        <button class="delete-btn" data-action="delete" data-id="${params.data._id}">🗑️</button>
      </div>
    `;
  };

  const columnDefs: ColDef[] = [
    {
      headerName: 'Expense Type',
      field: 'expenseTypeId.name',
      width: 150,
      pinned: 'left',
      cellStyle: { fontWeight: 'bold' }
    },
    {
      headerName: 'Category',
      field: 'expenseTypeId.category',
      width: 120,
      cellRenderer: CategoryCellRenderer
    },
    {
      headerName: 'Amount',
      field: 'amount',
      width: 120,
      cellRenderer: AmountCellRenderer
    },
    {
      headerName: 'Description',
      field: 'description',
      width: 200
    },
    {
      headerName: 'Vendor',
      field: 'vendor',
      width: 150
    },
    {
      headerName: 'Date',
      field: 'expenseDate',
      width: 120,
      cellRenderer: (params: ICellRendererParams) => {
        return params.value ? new Date(params.value).toLocaleDateString() : '';
      }
    },
    {
      headerName: 'Status',
      field: 'status',
      width: 120,
      cellRenderer: StatusCellRenderer
    },
    {
      headerName: 'Type',
      field: 'isAutoGenerated',
      width: 100,
      cellRenderer: (params: ICellRendererParams) => {
        return params.value ? '<span style="color: #666;">Auto</span>' : '<span style="color: #333;">Manual</span>';
      }
    },
    {
      headerName: 'Actions',
      field: 'actions',
      width: 100,
      cellRenderer: ActionsCellRenderer,
      sortable: false,
      filter: false
    }
  ];

  const defaultColDef: ColDef = {
    sortable: true,
    filter: true,
    resizable: true,
  };

  const fetchData = useCallback(async () => {
    try {
      setIsLoading(true);
      const [expensesResponse, typesResponse, summaryResponse] = await Promise.all([
        retreatExpensesApi.getByRetreat(retreatId),
        expenseTypesApi.getAll(),
        retreatExpensesApi.getRetreatSummary(retreatId)
      ]);

      setExpenses(expensesResponse.data);
      setExpenseTypes(typesResponse.data.filter(type => type.isActive !== false));
      setSummary(summaryResponse.data);
    } catch (error) {
      console.error('Error fetching expenses data:', error);
    } finally {
      setIsLoading(false);
    }
  }, [retreatId]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const onGridReady = useCallback((params: GridReadyEvent) => {
    gridApiRef.current = params.api;
    params.api.sizeColumnsToFit();
  }, []);

  const handleDeleteExpense = useCallback(async (expenseId: string) => {
    if (window.confirm('Are you sure you want to delete this expense?')) {
      try {
        await retreatExpensesApi.delete(expenseId);
        await fetchData();
      } catch (error) {
        console.error('Error deleting expense:', error);
        alert('Error deleting expense');
      }
    }
  }, [fetchData]);

  const onCellClicked = useCallback((event: any) => {
    const target = event.event?.target;
    if (target?.dataset?.action === 'edit') {
      const expenseId = target.dataset.id;
      const expense = expenses.find(e => e._id === expenseId);
      if (expense) {
        setEditingExpense(expense);
        setFormData({
          expenseTypeId: typeof expense.expenseTypeId === 'string' ? expense.expenseTypeId : expense.expenseTypeId._id || '',
          amount: expense.amount,
          currency: expense.currency,
          description: expense.description || '',
          vendor: expense.vendor || '',
          expenseDate: new Date(expense.expenseDate).toISOString().split('T')[0],
          status: expense.status
        });
        setShowAddForm(true);
      }
    } else if (target?.dataset?.action === 'delete') {
      const expenseId = target.dataset.id;
      handleDeleteExpense(expenseId);
    }
  }, [expenses, handleDeleteExpense]);


  const handleFormSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const submitData = {
        ...formData,
        retreatId,
        expenseDate: new Date(formData.expenseDate),
        isAutoGenerated: false
      };

      if (editingExpense) {
        await retreatExpensesApi.update(editingExpense._id!, submitData);
      } else {
        await retreatExpensesApi.create(submitData);
      }

      setShowAddForm(false);
      setEditingExpense(null);
      setFormData({
        expenseTypeId: '',
        amount: 0,
        currency: 'CZK',
        description: '',
        vendor: '',
        expenseDate: new Date().toISOString().split('T')[0],
        status: 'pending'
      });
      await fetchData();
    } catch (error) {
      console.error('Error saving expense:', error);
      alert('Error saving expense');
    }
  };

  const handleAutoGenerateHouseCost = async () => {
    try {
      await retreatExpensesApi.autoGenerateHouseCost(retreatId);
      await fetchData();
    } catch (error) {
      console.error('Error auto-generating house cost:', error);
      alert('Error auto-generating house cost');
    }
  };

  const formatCurrency = (amount: number, currency: string) => {
    return `${amount.toLocaleString()} ${currency}`;
  };

  if (isLoading) {
    return (
      <div className="loading-container">
        <div className="loading-spinner">💰</div>
        <p>Loading expenses...</p>
      </div>
    );
  }

  return (
    <div className="expenses-tab">
      {/* Summary Cards */}
      {summary && (
        <div className="expenses-summary">
          <div className="summary-cards">
            <div className="summary-card">
              <div className="summary-number">{formatCurrency(summary.totalExpenses, 'CZK')}</div>
              <div className="summary-label">Total Expenses</div>
            </div>
            <div className="summary-card">
              <div className="summary-number">{summary.count}</div>
              <div className="summary-label">Total Items</div>
            </div>
            <div className="summary-card">
              <div className="summary-number">{Object.keys(summary.expensesByCategory).length}</div>
              <div className="summary-label">Categories</div>
            </div>
            <div className="summary-card">
              <div className="summary-number">{summary.expensesByStatus.pending || 0}</div>
              <div className="summary-label">Pending</div>
            </div>
          </div>

          {/* Category Breakdown */}
          <div className="category-breakdown">
            <h4>💼 By Category</h4>
            <div className="category-list">
              {Object.entries(summary.expensesByCategory).map(([category, amount]) => (
                <div key={category} className="category-item">
                  <span className="category-name">{category}</span>
                  <span className="category-amount">{formatCurrency(amount, 'CZK')}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Actions */}
      <div className="expenses-actions">
        <button
          onClick={() => setShowAddForm(true)}
          className="add-btn"
          disabled={showAddForm}
        >
          ➕ Add Expense
        </button>
        <button
          onClick={handleAutoGenerateHouseCost}
          className="auto-btn"
        >
          🏠 Auto-Generate House Cost
        </button>
        <button onClick={fetchData} className="refresh-btn">
          🔄 Refresh
        </button>
      </div>

      {/* Add/Edit Form */}
      {showAddForm && (
        <div className="expense-form">
          <h3>{editingExpense ? 'Edit Expense' : 'Add New Expense'}</h3>
          <form onSubmit={handleFormSubmit}>
            <div className="form-grid">
              <div className="form-group">
                <label>Expense Type</label>
                <select
                  value={formData.expenseTypeId}
                  onChange={(e) => setFormData({...formData, expenseTypeId: e.target.value})}
                  required
                >
                  <option value="">Select expense type...</option>
                  {expenseTypes.map(type => (
                    <option key={type._id} value={type._id}>
                      {type.name} ({type.category})
                    </option>
                  ))}
                </select>
              </div>

              <div className="form-group">
                <label>Amount</label>
                <input
                  type="number"
                  value={formData.amount}
                  onChange={(e) => setFormData({...formData, amount: Number(e.target.value)})}
                  required
                />
              </div>

              <div className="form-group">
                <label>Currency</label>
                <select
                  value={formData.currency}
                  onChange={(e) => setFormData({...formData, currency: e.target.value as 'EUR' | 'USD' | 'CZK' | 'PLN'})}
                >
                  <option value="EUR">EUR (Euro)</option>
                  <option value="USD">USD (US Dollar)</option>
                  <option value="CZK">CZK (Czech Koruna)</option>
                  <option value="PLN">PLN (Polish Złoty)</option>
                </select>
              </div>

              <div className="form-group">
                <label>Status</label>
                <select
                  value={formData.status}
                  onChange={(e) => setFormData({...formData, status: e.target.value as any})}
                >
                  <option value="pending">Pending</option>
                  <option value="approved">Approved</option>
                  <option value="paid">Paid</option>
                  <option value="rejected">Rejected</option>
                </select>
              </div>

              <div className="form-group full-width">
                <label>Description</label>
                <input
                  type="text"
                  value={formData.description}
                  onChange={(e) => setFormData({...formData, description: e.target.value})}
                />
              </div>

              <div className="form-group">
                <label>Vendor</label>
                <input
                  type="text"
                  value={formData.vendor}
                  onChange={(e) => setFormData({...formData, vendor: e.target.value})}
                />
              </div>

              <div className="form-group">
                <label>Date</label>
                <input
                  type="date"
                  value={formData.expenseDate}
                  onChange={(e) => setFormData({...formData, expenseDate: e.target.value})}
                  required
                />
              </div>
            </div>

            <div className="form-actions">
              <button type="submit" className="save-btn">
                {editingExpense ? 'Update Expense' : 'Add Expense'}
              </button>
              <button
                type="button"
                onClick={() => {
                  setShowAddForm(false);
                  setEditingExpense(null);
                }}
                className="cancel-btn"
              >
                Cancel
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Expenses Grid */}
      <div className="expenses-grid">
        <div className="ag-theme-alpine" style={{ height: 400, width: '100%' }}>
          <AgGridReact
            rowData={expenses}
            columnDefs={columnDefs}
            defaultColDef={defaultColDef}
            onGridReady={onGridReady}
            onCellClicked={onCellClicked}
            rowSelection="multiple"
            suppressRowClickSelection={true}
            pagination={true}
            paginationPageSize={15}
            enableBrowserTooltips={true}
            headerHeight={40}
            rowHeight={45}
          />
        </div>
      </div>
    </div>
  );
};

export default ExpensesTab;