import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Search, X } from 'lucide-react';
import { bookingDocumentsApi, bookingsApi, clientsApi, medicalArtifactsApi, medicalReviewRequestsApi, paymentRequestsApi, paymentsApi, retreatsApi } from '../services/api';

type SearchRecord = { id: string; type: string; title: string; detail: string; path: string; terms: string; score?: number; parentRetreatId?: string };
const idOf = (value: any) => typeof value === 'object' ? String(value?._id || '') : String(value || '');
const text = (...values: any[]) => values.filter(Boolean).join(' ');
const display = (value: any) => value?.display_id || value?.displayId || value?.bookingNumber || '';
const clientName = (value: any) => text(value?.firstName || value?.fname, value?.lastName || value?.lname) || value?.fullName || value?.email || 'Unknown client';
const retreatName = (value: any) => value?.retreatCode || value?.code || value?.name || 'Unknown retreat';
const score = (record: SearchRecord, query: string) => {
  const q = query.toLowerCase(); const title = record.title.toLowerCase(); const terms = record.terms.toLowerCase();
  if (title === q || terms.split(/\s+/).includes(q)) return 100;
  if (title.startsWith(q)) return 80;
  if (title.includes(q)) return 60;
  return terms.includes(q) ? 35 : 0;
};

const GlobalSearch: React.FC<{ routePrefix: string; onNavigate: (path: string) => void }> = ({ routePrefix, onNavigate }) => {
  const [query, setQuery] = useState(''); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [records, setRecords] = useState<SearchRecord[]>([]); const loaded = useRef(false); const root = useRef<HTMLDivElement>(null); const input = useRef<HTMLInputElement>(null);
  useEffect(() => { const close = (event: MouseEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, []);
  useEffect(() => { const shortcut = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); input.current?.focus(); setOpen(true); void load(); } if (event.key === 'Escape') setOpen(false); }; document.addEventListener('keydown', shortcut); return () => document.removeEventListener('keydown', shortcut); });
  const load = async () => {
    if (loaded.current) return; setLoading(true);
    const calls = [clientsApi.getAll(), bookingsApi.getAll(), retreatsApi.getAll(), medicalArtifactsApi.getAll(), medicalReviewRequestsApi.getAll(), paymentsApi.getAll(), paymentRequestsApi.getAll(), bookingDocumentsApi.getAll()];
    const results = await Promise.allSettled(calls); const data = (index: number): any[] => results[index].status === 'fulfilled' ? (results[index] as PromiseFulfilledResult<any>).value.data || [] : [];
    const [clients, bookings, retreats, artifacts, reviews, payments, requests, documents] = [0,1,2,3,4,5,6,7].map(data);
    const next: SearchRecord[] = [];
    clients.forEach(client => next.push({ id: idOf(client), type: 'Client', title: `${display(client) ? `${display(client)} · ` : ''}${clientName(client)}`, detail: text(client.email, client.phone), path: `/${routePrefix}/clients/${idOf(client)}`, terms: text(display(client), idOf(client), clientName(client), client.email, client.phone) }));
    bookings.forEach(booking => { const client = booking.clientId || booking.clientDetails; const retreat = booking.retreatId || booking.retreatDetails; next.push({ id: idOf(booking), type: 'Booking', title: `${display(booking) ? `#${display(booking)} · ` : ''}${clientName(client)}`, detail: retreatName(retreat), path: `/${routePrefix}/bookings/${idOf(booking)}`, parentRetreatId: idOf(retreat), terms: text(display(booking), idOf(booking), clientName(client), display(client), retreatName(retreat), booking.status) }); });
    retreats.forEach(retreat => next.push({ id: idOf(retreat), type: 'Retreat', title: retreatName(retreat), detail: text(retreat.name, retreat.location_town, retreat.startDate && new Date(retreat.startDate).toLocaleDateString()), path: `/${routePrefix}/retreats/${idOf(retreat)}`, terms: text(display(retreat), idOf(retreat), retreatName(retreat), retreat.name, retreat.location, retreat.location_town) }));
    artifacts.forEach(item => next.push({ id: idOf(item), type: 'Medical artifact', title: `${display(item) ? `#${display(item)} · ` : ''}${item.title || item.documentType || item.artifactType || 'Medical artifact'}`, detail: text(clientName(item.clientId), retreatName(item.retreatId), item.documentStage), path: `/${routePrefix}/medical-artifacts/${idOf(item)}`, terms: text(display(item), idOf(item), item.title, item.documentType, item.artifactType, clientName(item.clientId), retreatName(item.retreatId)) }));
    reviews.forEach(item => next.push({ id: idOf(item), type: 'Medical review', title: `${display(item) ? `#${display(item)} · ` : ''}${item.requestType || 'Medical review'}`, detail: text(clientName(item.clientId), item.status), path: `/${routePrefix}/medical-review-requests/${idOf(item)}`, terms: text(display(item), idOf(item), item.requestType, clientName(item.clientId), item.status) }));
    payments.forEach(item => next.push({ id: idOf(item), type: 'Payment', title: `${display(item) ? `#${display(item)} · ` : ''}${item.amount || ''} ${item.currency || ''}`, detail: text(clientName(item.clientId), item.paymentMethod, item.status), path: `/${routePrefix}/payments/${idOf(item)}/edit`, terms: text(display(item), idOf(item), item.transactionReference, item.amount, item.currency, clientName(item.clientId)) }));
    requests.forEach(item => next.push({ id: idOf(item), type: 'Payment request', title: `${item.invoiceNumber || display(item) || idOf(item)} · ${item.requestedAmount || ''} ${item.currency || ''}`, detail: text(clientName(item.clientId), item.status), path: `/${routePrefix}/payment-requests/${idOf(item)}/edit`, terms: text(item.invoiceNumber, display(item), idOf(item), clientName(item.clientId), item.status) }));
    documents.forEach(item => next.push({ id: idOf(item), type: 'Document', title: `${display(item) ? `#${display(item)} · ` : ''}${item.title || item.documentType || 'Document'}`, detail: text(clientName(item.clientId), retreatName(item.retreatId)), path: `/${routePrefix}/booking-documents`, terms: text(display(item), idOf(item), item.title, item.documentType, clientName(item.clientId), retreatName(item.retreatId)) }));
    setRecords(next); loaded.current = true; setLoading(false);
  };
  const matches = useMemo(() => { const q = query.trim(); if (!q) return []; const direct = records.map(record => ({ ...record, score: score(record, q) })).filter(record => record.score! > 0).sort((a,b) => b.score! - a.score! || a.type.localeCompare(b.type)); const retreatIds = new Set(direct.filter(record => record.type === 'Retreat').map(record => record.id)); const children = records.filter(record => record.type === 'Booking' && record.parentRetreatId && retreatIds.has(record.parentRetreatId) && !direct.some(match => match.id === record.id && match.type === record.type)).map(record => ({ ...record, score: 20 })); return [...direct, ...children].slice(0, 30); }, [query, records]);
  const choose = (path: string) => { onNavigate(path); setOpen(false); setQuery(''); };
  return <div ref={root} className="relative w-full max-w-xl"><div className="flex h-10 items-center rounded-xl border border-slate-200 bg-white/90 px-3 shadow-sm"><Search className="h-4 w-4 shrink-0 text-slate-400" /><input ref={input} aria-label="Global search" value={query} onFocus={() => { setOpen(true); void load(); }} onChange={event => { setQuery(event.target.value); setOpen(true); void load(); }} placeholder="Search clients, bookings, retreats, medical IDs…" className="min-w-0 flex-1 border-0 bg-transparent px-2 text-sm outline-none" /><span className="hidden text-[11px] font-semibold text-slate-400 xl:inline">⌘K</span>{query && <button type="button" onClick={() => setQuery('')} aria-label="Clear global search"><X className="h-4 w-4 text-slate-400" /></button>}</div>{open && query.trim() && <div className="absolute left-0 right-0 top-12 z-[80] max-h-[70vh] overflow-auto rounded-xl border border-slate-200 bg-white p-2 shadow-2xl">{loading ? <div className="p-4 text-sm text-slate-500">Searching…</div> : matches.length ? matches.map((record, index) => <button type="button" key={`${record.type}-${record.id}-${index}`} onClick={() => choose(record.path)} className="flex w-full items-start gap-3 rounded-lg px-3 py-2.5 text-left hover:bg-blue-50"><span className="mt-0.5 min-w-28 rounded-md bg-slate-100 px-2 py-1 text-center text-[11px] font-bold uppercase text-slate-600">{record.type}</span><span className="min-w-0"><strong className="block truncate text-sm text-slate-900">{record.title}</strong><span className="block truncate text-xs text-slate-500">{record.detail}</span></span></button>) : <div className="p-4 text-sm text-slate-500">No relevant records found.</div>}</div>}</div>;
};
export default GlobalSearch;
