import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { FiArrowLeft, FiEdit2, FiEye, FiSend, FiTrash2, FiX } from 'react-icons/fi';
import { paymentsApi } from '../services/api';
import { Payment, PaymentReceipt, PaymentRequest } from '../types';
import LoadingSpinner from './LoadingSpinner';
import CurrencyDisplay from './CurrencyDisplay';
import { formatCalendarDate } from '../utils/dateFormat';

const Icon: React.FC<{ icon: any }> = ({ icon: Component }) => <Component className="h-4 w-4" />;

const PaymentReceiptsPage: React.FC = () => {
  const navigate = useNavigate();
  const [receipts, setReceipts] = useState<PaymentReceipt[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [detail, setDetail] = useState<PaymentReceipt | null>(null);
  const [editing, setEditing] = useState<PaymentReceipt | null>(null);
  const [busy, setBusy] = useState('');
  const [editForm, setEditForm] = useState({ payerName: '', transactionReference: '', transactionId: '', receivedDate: '', paymentMethod: 'bank_transfer', status: 'received', description: '', notes: '' });
  const loadReceipts = () => paymentsApi.getReceipts().then((response) => setReceipts(response.data || []));
  useEffect(() => {
    loadReceipts()
      .catch(() => setError('Unable to load payment receipts.')).finally(() => setLoading(false));
  }, []);
  const viewReceipt = async (receipt: PaymentReceipt) => { if (!receipt._id) return; setBusy(`view:${receipt._id}`); setError(''); try { setDetail((await paymentsApi.getReceipt(receipt._id)).data); } catch (err: any) { setError(err?.response?.data?.message || 'Unable to load this receipt.'); } finally { setBusy(''); } };
  const openEdit = (receipt: PaymentReceipt) => { setEditing(receipt); setEditForm({ payerName: receipt.payerName || '', transactionReference: receipt.transactionReference || '', transactionId: receipt.transactionId || '', receivedDate: receipt.receivedDate ? new Date(receipt.receivedDate).toISOString().slice(0, 10) : '', paymentMethod: receipt.paymentMethod || 'bank_transfer', status: receipt.status || 'received', description: receipt.description || '', notes: receipt.notes || '' }); };
  const saveReceipt = async () => { if (!editing?._id) return; setBusy(`edit:${editing._id}`); setError(''); try { await paymentsApi.updateReceipt(editing._id, editForm as any); setEditing(null); await loadReceipts(); if (detail?._id === editing._id) setDetail((await paymentsApi.getReceipt(editing._id)).data); } catch (err: any) { setError(err?.response?.data?.message || 'Unable to update this receipt.'); } finally { setBusy(''); } };
  const deleteReceipt = async (receipt: PaymentReceipt) => { if (!receipt._id || !window.confirm(`Delete receipt ${receipt.transactionReference || receipt._id.slice(-8)}? Receipts with linked allocations cannot be deleted.`)) return; setBusy(`delete:${receipt._id}`); setError(''); try { await paymentsApi.deleteReceipt(receipt._id); if (detail?._id === receipt._id) setDetail(null); await loadReceipts(); } catch (err: any) { setError(err?.response?.data?.message || 'Unable to delete this receipt.'); } finally { setBusy(''); } };
  const sendReceipt = async (receipt: PaymentReceipt, allocation: Payment) => { if (!receipt._id || !allocation._id) return; const client: any = allocation.clientId; const name = typeof client === 'object' ? `${client.firstName || ''} ${client.lastName || ''}`.trim() : 'this client'; if (!window.confirm(`Email receipt #${receipt.display_id || ''} to ${name}? Attachments will follow your Payment settings.`)) return; setBusy(`send:${allocation._id}`); setError(''); try { const response = await paymentsApi.sendReceipt(receipt._id, { allocationId: allocation._id }); alert(`Receipt sent to ${response.data.to}.`); setDetail((await paymentsApi.getReceipt(receipt._id)).data); await loadReceipts(); } catch (err: any) { setError(err?.response?.data?.message || 'Unable to send this receipt.'); } finally { setBusy(''); } };
  if (loading) return <LoadingSpinner message="Loading payment receipts..." />;
  return <div className="h-full p-6">
    <div className="mb-6 flex items-center gap-4"><button onClick={() => navigate('/admin/payments')} className="inline-flex items-center gap-2 text-gray-600 hover:text-gray-900"><Icon icon={FiArrowLeft} /> Back</button><div><h1 className="text-2xl font-semibold text-gray-900">Payment Receipts</h1><p className="text-sm text-gray-600">Actual received transactions and their booking allocation totals.</p></div></div>
    {error && <div className="mb-4 rounded-md border border-red-200 bg-red-50 p-3 text-red-700">{error}</div>}
    <div className="overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr>{['Receipt', 'Received', 'Payer / reference', 'Payment request', 'Total received', 'Allocated', 'Allocations', 'Status', 'Actions'].map((label) => <th key={label} className="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">{label}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{receipts.map((receipt) => {
      const request = typeof receipt.paymentRequestId === 'object' ? receipt.paymentRequestId as PaymentRequest : null;
      return <tr key={receipt._id} className="hover:bg-gray-50"><td className="px-5 py-4 text-sm font-semibold text-blue-700">#{receipt.display_id || '—'}</td><td className="px-5 py-4 text-sm text-gray-800">{formatCalendarDate(receipt.receivedDate)}</td><td className="px-5 py-4 text-sm"><strong className="block text-gray-900">{receipt.payerName || '—'}</strong><span className="text-gray-500">{receipt.transactionReference || receipt.transactionId || `Receipt #${receipt.display_id || receipt._id?.slice(-8)}`}</span></td><td className="px-5 py-4 text-sm text-gray-800">{request ? request.invoiceNumber || `#${request.display_id}` : receipt.paymentRequestId ? String(receipt.paymentRequestId).slice(-8) : '—'}</td><td className="px-5 py-4 text-sm font-semibold"><CurrencyDisplay amount={receipt.totalAmount} currency={receipt.currency} /></td><td className="px-5 py-4 text-sm"><CurrencyDisplay amount={receipt.allocatedAmount || 0} currency={receipt.currency} /></td><td className="px-5 py-4 text-sm text-gray-800">{receipt.allocationCount || 0}</td><td className="px-5 py-4"><span className="rounded-full bg-green-100 px-2 py-1 text-xs font-semibold text-green-800">{receipt.status}</span></td><td className="px-5 py-4"><div className="flex gap-2"><button title="View receipt" onClick={() => viewReceipt(receipt)} className="rounded border border-blue-200 p-2 text-blue-700 hover:bg-blue-50"><Icon icon={FiEye}/></button><button title="Edit receipt" onClick={() => openEdit(receipt)} className="rounded border border-gray-300 p-2 text-gray-700 hover:bg-gray-50"><Icon icon={FiEdit2}/></button><button title="Delete receipt" disabled={busy === `delete:${receipt._id}`} onClick={() => deleteReceipt(receipt)} className="rounded border border-red-200 p-2 text-red-700 hover:bg-red-50 disabled:opacity-50"><Icon icon={FiTrash2}/></button></div></td></tr>;
    })}</tbody></table>{!receipts.length && <div className="p-8 text-center text-gray-500">No receipt-backed payments yet. Existing historical payments remain available in Payments.</div>}</div></div>
    {detail && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-lg bg-white shadow-xl">
      <div className="flex items-center justify-between border-b p-4"><div><h2 className="text-xl font-semibold">Receipt #{detail.display_id}</h2><p className="text-sm text-gray-500">{detail.transactionReference || detail._id}{detail.lastSentAt ? ` · Last sent to ${detail.lastSentTo}` : ''}</p></div><button onClick={() => setDetail(null)} className="p-2"><Icon icon={FiX}/></button></div>
      <div className="grid gap-3 p-4 sm:grid-cols-3"><div>Total: <strong><CurrencyDisplay amount={detail.totalAmount} currency={detail.currency}/></strong></div><div>Allocated: <strong><CurrencyDisplay amount={detail.allocatedAmount} currency={detail.currency}/></strong></div><div>Unallocated: <strong><CurrencyDisplay amount={detail.unallocatedAmount || 0} currency={detail.currency}/></strong></div></div>
      <div className="border-t"><h3 className="p-4 font-semibold">Allocations and recipients</h3><div className="divide-y">{(detail.allocations || []).map((payment: any) => <div key={payment._id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><strong>{typeof payment.clientId === 'object' ? `${payment.clientId.firstName || ''} ${payment.clientId.lastName || ''}`.trim() : payment.clientId}</strong><div className="text-xs text-gray-500">Booking #{typeof payment.bookingId === 'object' ? payment.bookingId.bookingNumber : String(payment.bookingId || '').slice(-8)} · {typeof payment.clientId === 'object' ? payment.clientId.email || 'No email' : ''}</div></div><CurrencyDisplay amount={payment.amount} currency={payment.currency}/><div className="flex gap-2"><button onClick={() => sendReceipt(detail, payment)} disabled={busy === `send:${payment._id}`} className="inline-flex items-center gap-2 rounded bg-blue-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50"><Icon icon={FiSend}/>{busy === `send:${payment._id}` ? 'Sending…' : 'Email receipt'}</button><button onClick={() => navigate(`/admin/payments/${payment._id}`)} className="rounded border border-gray-300 px-3 py-2 text-sm font-semibold">View payment</button></div></div>)}{!detail.allocations?.length && <p className="p-4 text-gray-500">No allocations.</p>}</div></div>
    </div></div>}
    {editing && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-2xl rounded-lg bg-white shadow-xl"><div className="flex items-center justify-between border-b p-4"><h2 className="text-xl font-semibold">Edit receipt metadata</h2><button onClick={() => setEditing(null)} className="p-2"><Icon icon={FiX}/></button></div><div className="grid gap-4 p-4 sm:grid-cols-2">{[['payerName','Payer name'],['transactionReference','Reference'],['transactionId','Transaction ID'],['receivedDate','Received date']].map(([key,label]) => <label key={key} className="text-sm font-medium text-gray-700">{label}<input type={key === 'receivedDate' ? 'date' : 'text'} value={(editForm as any)[key]} onChange={event => setEditForm(current => ({...current,[key]:event.target.value}))} className="mt-1 w-full rounded border border-gray-300 px-3 py-2"/></label>)}<label className="text-sm font-medium text-gray-700">Method<select value={editForm.paymentMethod} onChange={event => setEditForm(current => ({...current,paymentMethod:event.target.value}))} className="mt-1 w-full rounded border border-gray-300 px-3 py-2">{['bank_transfer','card','cash','paypal','crypto','stripe','wise','revolut','other'].map(value => <option key={value} value={value}>{value.replace('_',' ')}</option>)}</select></label><label className="text-sm font-medium text-gray-700">Status<select value={editForm.status} onChange={event => setEditForm(current => ({...current,status:event.target.value}))} className="mt-1 w-full rounded border border-gray-300 px-3 py-2">{['pending','received','failed','refunded'].map(value => <option key={value}>{value}</option>)}</select></label><label className="sm:col-span-2 text-sm font-medium text-gray-700">Description<textarea value={editForm.description} onChange={event => setEditForm(current => ({...current,description:event.target.value}))} className="mt-1 w-full rounded border border-gray-300 px-3 py-2"/></label><label className="sm:col-span-2 text-sm font-medium text-gray-700">Notes<textarea value={editForm.notes} onChange={event => setEditForm(current => ({...current,notes:event.target.value}))} className="mt-1 w-full rounded border border-gray-300 px-3 py-2"/></label></div><div className="flex justify-end gap-2 border-t p-4"><button onClick={() => setEditing(null)} className="rounded border px-4 py-2">Cancel</button><button onClick={saveReceipt} disabled={busy.startsWith('edit:')} className="rounded bg-blue-700 px-4 py-2 font-semibold text-white disabled:opacity-50">Save receipt</button></div></div></div>}
  </div>;
};

export default PaymentReceiptsPage;
