import React from 'react';
import { ReferralCommissionPackage } from '../types';

const field = 'mt-1 w-full rounded border border-slate-300 p-2';
export const ReferralPackagesEditor: React.FC<{ value: ReferralCommissionPackage[]; onChange: (rules: ReferralCommissionPackage[]) => void }> = ({ value, onChange }) => {
  const update = (index: number, patch: Partial<ReferralCommissionPackage>) => onChange(value.map((rule, i) => i === index ? { ...rule, ...patch } : rule));
  return <section className="my-4 rounded-xl border border-slate-200 p-4"><h3 className="font-bold">Commission packages by booking date</h3><p className="my-2 text-sm text-slate-500">Packages use the booking registration date in Prague time. End dates are inclusive. Configured packages replace legacy percentages; unmatched bookings require configuration. Paid amounts remain unchanged.</p>
    {value.map((rule, index) => <fieldset key={index} className="my-4 rounded-lg bg-slate-50 p-4"><legend className="font-semibold">Package {index + 1}</legend><div className="grid gap-3 sm:grid-cols-3">
      <label>Key<input className={field} value={rule.key} required onChange={e => update(index, { key: e.target.value })} /></label>
      <label>Name<input className={field} value={rule.name} required onChange={e => update(index, { name: e.target.value })} /></label>
      <label>Calculation<select className={field} value={rule.kind} onChange={e => update(index, { kind: e.target.value as 'percentage' | 'fixed', tiers: [], ratePercent: 0, amount: 0, currency: 'USD' })}><option value="percentage">Percentage</option><option value="fixed">Fixed amount</option></select></label>
      <label>From<input className={field} type="date" required value={rule.effectiveFrom} onChange={e => update(index, { effectiveFrom: e.target.value })} /></label>
      <label>Through (inclusive)<input className={field} type="date" value={rule.effectiveTo || ''} onChange={e => update(index, { effectiveTo: e.target.value })} /></label>
      <label>Booking currency<select className={field} value={rule.bookingCurrency} onChange={e => update(index, { bookingCurrency: e.target.value })}>{['*', 'PLN', 'EUR', 'USD', 'CZK', 'GBP'].map(currency => <option key={currency} value={currency}>{currency === '*' ? 'All currencies' : currency}</option>)}</select></label>
      {rule.kind === 'fixed' ? <><label>Amount<input className={field} type="number" min="0" step="0.01" required value={rule.amount ?? 0} onChange={e => update(index, { amount: Number(e.target.value) })} /></label><label>Payout currency<select className={field} value={rule.currency || 'USD'} onChange={e => update(index, { currency: e.target.value })}>{['PLN', 'EUR', 'USD', 'CZK', 'GBP'].map(currency => <option key={currency}>{currency}</option>)}</select></label></> : !rule.tiers?.length && <label>Rate %<input className={field} type="number" min="0" max="100" step="0.01" required value={rule.ratePercent ?? 0} onChange={e => update(index, { ratePercent: Number(e.target.value) })} /></label>}
    </div>{rule.kind === 'percentage' && <div className="my-3">{rule.tiers?.map((tier, tierIndex) => <div key={tierIndex} className="my-2 flex flex-wrap gap-3"><label>From price<input className={field} type="number" min="0" step="0.01" value={tier.minPrice} onChange={e => update(index, { tiers: rule.tiers!.map((t, i) => i === tierIndex ? { ...t, minPrice: Number(e.target.value) } : t) })} /></label><label>Rate %<input className={field} type="number" min="0" max="100" step="0.01" value={tier.ratePercent} onChange={e => update(index, { tiers: rule.tiers!.map((t, i) => i === tierIndex ? { ...t, ratePercent: Number(e.target.value) } : t) })} /></label><button type="button" onClick={() => update(index, { tiers: rule.tiers!.filter((_, i) => i !== tierIndex) })}>Remove tier</button></div>)}<button type="button" className="text-blue-700" onClick={() => update(index, { tiers: [...(rule.tiers || []), { minPrice: 0, ratePercent: 0 }] })}>Add price tier</button></div>}<button type="button" className="mt-3 text-red-700" onClick={() => onChange(value.filter((_, i) => i !== index))}>Remove package</button></fieldset>)}
    <button type="button" className="rounded border px-3 py-2" onClick={() => onChange([...value, { key: '', name: '', effectiveFrom: '', bookingCurrency: '*', kind: 'percentage', ratePercent: 0 }])}>Add commission package</button>
  </section>;
};
