import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { FiBell, FiCheck, FiExternalLink, FiRefreshCw, FiSearch } from 'react-icons/fi';
import { useNavigate } from 'react-router-dom';
import { api } from '../services/api';

const BellIcon = FiBell as any; const CheckIcon = FiCheck as any; const ExternalLinkIcon = FiExternalLink as any; const RefreshIcon = FiRefreshCw as any; const SearchIcon = FiSearch as any;

type Related = { _id?: string; display_id?: number; firstName?: string; lastName?: string; name?: string; bookingNumber?: number };
type Notice = { _id: string; name: string; description?: string; status?: string; sourceId?: string; sourceRoute?: string; notificationReadAt?: string; createdAt?: string; dueDate?: string; clientId?: Related; retreatId?: Related; bookingId?: Related };
const clientName = (client?: Related) => client ? [client.firstName, client.lastName].filter(Boolean).join(' ') || `Client #${client.display_id || ''}` : 'Unknown client';
const fallbackRoute = (row: Notice) => row.description?.match(/(\/admin\/[A-Za-z0-9_?=&/.-]+)/)?.[1] || '';

const SubmissionNotificationsPage: React.FC = () => {
  const navigate = useNavigate();
  const [rows, setRows] = useState<Notice[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [unreadOnly, setUnreadOnly] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await api.get('/submission-notifications', { params: { search: search || undefined, status: status || undefined, unreadOnly: unreadOnly || undefined } }); setRows(response.data || []); } catch (e: any) { setError(e.response?.data?.message || 'Unable to load IR notifications.'); } finally { setLoading(false); } }, [search, status, unreadOnly]);
  useEffect(() => { const timer = window.setTimeout(load, 200); return () => window.clearTimeout(timer); }, [load]);
  const unread = useMemo(() => rows.filter(row => !row.notificationReadAt).length, [rows]);
  const markRead = async (row: Notice) => { if (row.notificationReadAt) return; await api.patch(`/submission-notifications/${row._id}/read`); setRows(current => current.map(item => item._id === row._id ? { ...item, notificationReadAt: new Date().toISOString() } : item)); };
  const open = async (row: Notice) => { await markRead(row); const route = row.sourceRoute || fallbackRoute(row); navigate(route || (row.clientId?._id ? `/admin/clients/${row.clientId._id}` : '/admin/tasks')); };
  const complete = async (row: Notice) => { await api.patch(`/tasks/${row._id}/complete`); setRows(current => current.map(item => item._id === row._id ? { ...item, status: 'completed', notificationReadAt: item.notificationReadAt || new Date().toISOString() } : item)); };
  return <div className="min-h-full bg-slate-50 p-4 md:p-7"><div className="mx-auto max-w-7xl space-y-5">
    <header className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-100 text-blue-700"><BellIcon size={22}/></span><div><h1 className="text-2xl font-bold text-slate-900">IR Notifications</h1><p className="text-sm text-slate-500">Documents and forms submitted through IbogaReady.</p></div></div><div className="flex items-center gap-3"><span className="rounded-full bg-blue-100 px-3 py-1 text-sm font-semibold text-blue-700">{unread} unread</span><button onClick={load} className="inline-flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm font-semibold"><RefreshIcon/> Refresh</button></div></header>
    <section className="grid gap-3 rounded-xl border bg-white p-4 shadow-sm md:grid-cols-[minmax(260px,1fr)_180px_auto]"><label className="relative"><SearchIcon className="absolute left-3 top-3 text-slate-400"/><input className="w-full rounded-lg border py-2.5 pl-10 pr-3" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search client, retreat, booking, or submission…"/></label><select className="rounded-lg border px-3 py-2.5" value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option><option value="pending">Pending</option><option value="in_progress">In progress</option><option value="completed">Completed</option></select><label className="flex items-center gap-2 rounded-lg bg-slate-50 px-3 py-2 text-sm font-semibold"><input type="checkbox" checked={unreadOnly} onChange={e => setUnreadOnly(e.target.checked)}/> Unread only</label></section>
    {error && <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}
    <section className="overflow-hidden rounded-xl border bg-white shadow-sm">{loading ? <p className="p-8 text-center text-slate-500">Loading notifications…</p> : !rows.length ? <p className="p-8 text-center text-slate-500">No IR submission notifications match these filters.</p> : <div className="divide-y">{rows.map(row => <article key={row._id} className={`grid gap-4 p-4 md:grid-cols-[minmax(0,1fr)_auto] md:items-center ${!row.notificationReadAt ? 'bg-blue-50/60' : ''}`}><div className="flex min-w-0 gap-3"><span className={`mt-2 h-2.5 w-2.5 shrink-0 rounded-full ${row.notificationReadAt ? 'bg-slate-300' : 'bg-blue-600'}`}/><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-slate-900">{row.name}</h2><span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs capitalize">{String(row.sourceId || '').split(':')[0].replace(/_/g,' ')}</span><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${row.status === 'completed' ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'}`}>{row.status || 'pending'}</span></div><p className="mt-1 text-sm text-slate-700">{clientName(row.clientId)}{row.clientId?.display_id ? ` · #${row.clientId.display_id}` : ''}{row.retreatId?.name ? ` · ${row.retreatId.name}` : ''}{row.bookingId?.bookingNumber ? ` · Booking #${row.bookingId.bookingNumber}` : ''}</p><p className="mt-1 text-xs text-slate-500">Received {row.createdAt ? new Date(row.createdAt).toLocaleString() : 'recently'}{row.dueDate ? ` · Review due ${new Date(row.dueDate).toLocaleString()}` : ''}</p></div></div><div className="flex flex-wrap gap-2 md:justify-end">{!row.notificationReadAt && <button onClick={() => markRead(row)} className="rounded-lg border px-3 py-2 text-sm font-semibold">Mark read</button>}<button onClick={() => open(row)} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white"><ExternalLinkIcon/> Open source</button>{row.status !== 'completed' && <button onClick={() => complete(row)} className="inline-flex items-center gap-2 rounded-lg border border-green-300 bg-green-50 px-3 py-2 text-sm font-semibold text-green-700"><CheckIcon/> Reviewed</button>}</div></article>)}</div>}</section>
  </div></div>;
};
export default SubmissionNotificationsPage;
