import React, { useState, useEffect } from 'react';
import { BookingFlowItem } from '../../types';
import { bookingFlowApi } from '../../services/api';
import { Task, TaskFilters, taskService } from '../../services/taskService';
import { TaskList } from '../../components/Tasks/TaskList';
import { TaskForm } from '../../components/Tasks/TaskForm';
import { TaskFiltersPanel } from '../../components/Tasks/TaskFiltersPanel';
import TasksCalendarView from '../../components/Tasks/TasksCalendarView';
import { SprintBoard } from '../../components/Tasks/SprintBoard';
import RemindersPage from '../../components/RemindersPage';
import './Tasks.css';
import { focusGroups, TaskTab, taskBelongsToTab } from './taskOrganization';

const TASK_TAB_KEY = 'retreatengine.tasks.activeTab';
const taskTabs: Array<{ key: TaskTab; label: string; help: string }> = [
  { key:'focus', label:'Focus now', help:'Only overdue, due today, in-progress, urgent, and high-priority work.' },
  { key:'retreats', label:'Retreats', help:'Work to complete for a retreat.' },
  { key:'clients', label:'Clients', help:'Work to complete for individual clients.' },
  { key:'other', label:'Other', help:'General active work that is not linked to a client or retreat.' },
  { key:'system', label:'System', help:'Generated by booking steps and automation. Resolve the linked source.' },
  { key:'done', label:'Done', help:'Completed and cancelled work, kept away from your active workload.' },
  { key:'reminders', label:'Reminders', help:'Timed prompts. Use tasks for work that must be completed.' },
];

export const Tasks: React.FC = () => {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [deadlines, setDeadlines] = useState<BookingFlowItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [editingTask, setEditingTask] = useState<Task | null>(null);
  const [formError, setFormError] = useState<string | null>(null);
  const [viewMode, setViewMode] = useState<'list' | 'board' | 'calendar'>('list');
  const [activeTab, setActiveTab] = useState<TaskTab>(() => {
    const saved = localStorage.getItem(TASK_TAB_KEY) as TaskTab | null;
    return taskTabs.some((tab) => tab.key === saved) ? saved! : 'focus';
  });
  const [filters, setFilters] = useState<TaskFilters>({
    sortBy: 'dueDate',
    sortOrder: 'asc'
  });

  const loadTasks = async () => {
    try {
      setLoading(true);
      setError(null);
      const [tasksData, deadlinesResponse] = await Promise.all([
        taskService.getTasks(filters),
        bookingFlowApi.getItems({}).catch(() => ({ data: [] as BookingFlowItem[] })),
      ]);
      setTasks(tasksData);
      setDeadlines(deadlinesResponse.data || []);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load tasks');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadTasks();
  }, [filters]);

  const handleCreateTask = () => {
    setEditingTask(null);
    setFormError(null);
    setShowForm(true);
  };

  const handleEditTask = (task: Task) => {
    setEditingTask(task);
    setFormError(null);
    setShowForm(true);
  };

  const handleFormSubmit = async (taskData: any) => {
    try {
      if (editingTask) {
        await taskService.updateTask(editingTask.id, taskData);
      } else {
        await taskService.createTask(taskData);
      }
      setShowForm(false);
      setEditingTask(null);
      setFormError(null);
      await loadTasks();
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to save task';
      setFormError(message);
      setError(message);
    }
  };

  const handleFormCancel = () => {
    setShowForm(false);
    setEditingTask(null);
    setFormError(null);
  };

  const handleDeleteTask = async (taskId: string) => {
    if (!window.confirm('Are you sure you want to delete this task?')) {
      return;
    }

    try {
      await taskService.deleteTask(taskId);
      await loadTasks();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to delete task');
    }
  };

  const handleCompleteTask = async (taskId: string) => {
    try {
      await taskService.completeTask(taskId);
      await loadTasks();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to complete task');
    }
  };

  const handleFiltersChange = (newFilters: TaskFilters) => {
    setFilters(newFilters);
  };

  const counts = Object.fromEntries(taskTabs.map((tab) => [tab.key, tab.key === 'reminders' ? null : tasks.filter((task) => taskBelongsToTab(task, tab.key)).length])) as Record<TaskTab, number | null>;
  const visibleTasks = tasks.filter((task) => taskBelongsToTab(task, activeTab));
  const activeTabConfig = taskTabs.find((tab) => tab.key === activeTab)!;
  const changeTab = (tab: TaskTab) => {
    setActiveTab(tab); localStorage.setItem(TASK_TAB_KEY, tab);
    if (['system','done','reminders'].includes(tab) && viewMode === 'board') setViewMode('list');
  };

  const getTaskStats = () => {
    const stats = {
      total: visibleTasks.length,
      pending: visibleTasks.filter(t => t.status === 'pending').length,
      inProgress: visibleTasks.filter(t => t.status === 'in_progress').length,
      completed: visibleTasks.filter(t => t.status === 'completed').length,
      overdue: visibleTasks.filter(t => t.dueDate && taskService.isOverdue(t.dueDate, t.status)).length,
      urgent: visibleTasks.filter(t => t.urgency === 'urgent').length,
    };
    return stats;
  };

  const stats = getTaskStats();

  if (loading) {
    return (
      <div className="tasks-page">
        <div className="loading">Loading tasks...</div>
      </div>
    );
  }

  return (
    <div className="tasks-page">
      <div className="tasks-header">
        <div className="header-content">
          <h1>Tasks</h1>
          <div className="task-header-actions">
            {activeTab !== 'reminders' && <div className="tasks-view-toggle" aria-label="Task view">
              <button type="button" className={viewMode === 'list' ? 'active' : ''} onClick={() => setViewMode('list')}>List</button>
              {!['system','done'].includes(activeTab) && <button type="button" className={viewMode === 'board' ? 'active' : ''} onClick={() => setViewMode('board')}>Sprints</button>}
              <button type="button" className={viewMode === 'calendar' ? 'active' : ''} onClick={() => setViewMode('calendar')}>Calendar</button>
            </div>}
            {!['system','done','reminders'].includes(activeTab) && (
            <button
              className="btn btn-primary"
              onClick={handleCreateTask}
            >
              Create Task
            </button>
            )}
          </div>
        </div>
      </div>

      {error && (
        <div className="error-message">
          {error}
          <button onClick={() => setError(null)} className="error-close">×</button>
        </div>
      )}

      <div className="tasks-source-tabs" role="tablist" aria-label="Task groups">{taskTabs.map((tab) => <button key={tab.key} type="button" role="tab" aria-selected={activeTab === tab.key} className={activeTab === tab.key ? 'active' : ''} onClick={() => changeTab(tab.key)}>{tab.label}{counts[tab.key] != null && <span>{counts[tab.key]}</span>}</button>)}</div>
      <div className={`tasks-source-help ${activeTab}`}>{activeTabConfig.help}</div>

      {activeTab !== 'reminders' && <TaskFiltersPanel
        filters={filters}
        onFiltersChange={handleFiltersChange}
      />}

      <div className="tasks-main-content">
        {activeTab === 'reminders' ? (
          <RemindersPage />
        ) : viewMode === 'list' && activeTab === 'focus' ? (
          <div className="focus-task-groups">{focusGroups(visibleTasks).map((group) => <section className={`focus-task-group ${group.key}`} key={group.key}><header><h2>{group.title}</h2><span>{group.tasks.length}</span></header><TaskList tasks={group.tasks} onEditTask={handleEditTask} onDeleteTask={handleDeleteTask} onCompleteTask={handleCompleteTask} /></section>)}{visibleTasks.length === 0 && <div className="focus-empty"><strong>Nothing needs immediate attention.</strong><span>Choose Retreats, Clients, or Other when you are ready to plan ahead.</span></div>}</div>
        ) : viewMode === 'list' ? (
          <TaskList
            tasks={visibleTasks}
            onEditTask={handleEditTask}
            onDeleteTask={handleDeleteTask}
            onCompleteTask={handleCompleteTask}
            systemManaged={activeTab === 'system'}
          />
        ) : viewMode === 'board' ? (
          <SprintBoard tasks={visibleTasks} onChanged={loadTasks} onEdit={handleEditTask} />
        ) : (
          <TasksCalendarView tasks={visibleTasks} deadlines={activeTab === 'system' ? deadlines : []} />
        )}
      </div>

      {activeTab !== 'reminders' && (
      <div className="task-stats-footer">
        <div className="stat-item">
          <span className="stat-label">Total</span>
          <span className="stat-value">{stats.total}</span>
        </div>
        <div className="stat-item">
          <span className="stat-label">Pending</span>
          <span className="stat-value pending">{stats.pending}</span>
        </div>
        <div className="stat-item">
          <span className="stat-label">In Progress</span>
          <span className="stat-value in-progress">{stats.inProgress}</span>
        </div>
        <div className="stat-item">
          <span className="stat-label">Completed</span>
          <span className="stat-value completed">{stats.completed}</span>
        </div>
        <div className="stat-item">
          <span className="stat-label">Overdue</span>
          <span className="stat-value overdue">{stats.overdue}</span>
        </div>
        <div className="stat-item">
          <span className="stat-label">Urgent</span>
          <span className="stat-value urgent">{stats.urgent}</span>
        </div>
      </div>
      )}

      {showForm && (
        <TaskForm
          task={editingTask}
          onSubmit={handleFormSubmit}
          onCancel={handleFormCancel}
          error={formError}
        />
      )}
    </div>
  );
};
